/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.famocom.erpcloud.model.AppraisalGoalDetails;
import com.liferay.famocom.erpcloud.model.AppraisalGoalDetailsModel;
import com.liferay.famocom.erpcloud.model.AppraisalGoalDetailsSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AppraisalGoalDetails service. Represents a row in the &quot;appraisalGoalDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AppraisalGoalDetailsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalGoalDetailsImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AppraisalGoalDetailsImpl
 * @see AppraisalGoalDetails
 * @see AppraisalGoalDetailsModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AppraisalGoalDetailsModelImpl extends BaseModelImpl<AppraisalGoalDetails>
	implements AppraisalGoalDetailsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal goal details model instance should use the {@link AppraisalGoalDetails} interface instead.
	 */
	public static final String TABLE_NAME = "appraisalGoalDetails";
	public static final Object[][] TABLE_COLUMNS = {
			{ "appraisalGoalDetailsId", Types.BIGINT },
			{ "appraisalGoalMasterId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "appraisalId", Types.BIGINT },
			{ "employeeId", Types.BIGINT },
			{ "projectId", Types.BIGINT },
			{ "evaluationId", Types.BIGINT },
			{ "goaldetailId", Types.BIGINT },
			{ "ratingIdEmp", Types.BIGINT },
			{ "ratingIdMan", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "createdBy", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "modifiedBy", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("appraisalGoalDetailsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalGoalMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("evaluationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("goaldetailId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ratingIdEmp", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ratingIdMan", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table appraisalGoalDetails (appraisalGoalDetailsId LONG not null primary key,appraisalGoalMasterId LONG,companyId LONG,appraisalId LONG,employeeId LONG,projectId LONG,evaluationId LONG,goaldetailId LONG,ratingIdEmp LONG,ratingIdMan LONG,createdDate DATE null,createdBy LONG,modifiedDate DATE null,modifiedBy LONG)";
	public static final String TABLE_SQL_DROP = "drop table appraisalGoalDetails";
	public static final String ORDER_BY_JPQL = " ORDER BY appraisalGoalDetails.appraisalGoalDetailsId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY appraisalGoalDetails.appraisalGoalDetailsId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.famocom.erpcloud.model.AppraisalGoalDetails"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.famocom.erpcloud.model.AppraisalGoalDetails"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.famocom.erpcloud.model.AppraisalGoalDetails"),
			true);
	public static final long APPRAISALID_COLUMN_BITMASK = 1L;
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;
	public static final long EVALUATIONID_COLUMN_BITMASK = 4L;
	public static final long GOALDETAILID_COLUMN_BITMASK = 8L;
	public static final long PROJECTID_COLUMN_BITMASK = 16L;
	public static final long APPRAISALGOALDETAILSID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AppraisalGoalDetails toModel(
		AppraisalGoalDetailsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AppraisalGoalDetails model = new AppraisalGoalDetailsImpl();

		model.setAppraisalGoalDetailsId(soapModel.getAppraisalGoalDetailsId());
		model.setAppraisalGoalMasterId(soapModel.getAppraisalGoalMasterId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setAppraisalId(soapModel.getAppraisalId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setProjectId(soapModel.getProjectId());
		model.setEvaluationId(soapModel.getEvaluationId());
		model.setGoaldetailId(soapModel.getGoaldetailId());
		model.setRatingIdEmp(soapModel.getRatingIdEmp());
		model.setRatingIdMan(soapModel.getRatingIdMan());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AppraisalGoalDetails> toModels(
		AppraisalGoalDetailsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AppraisalGoalDetails> models = new ArrayList<AppraisalGoalDetails>(soapModels.length);

		for (AppraisalGoalDetailsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.famocom.erpcloud.model.AppraisalGoalDetails"));

	public AppraisalGoalDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalGoalDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalGoalDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalGoalDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalGoalDetails.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalGoalDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("appraisalGoalDetailsId", getAppraisalGoalDetailsId());
		attributes.put("appraisalGoalMasterId", getAppraisalGoalMasterId());
		attributes.put("companyId", getCompanyId());
		attributes.put("appraisalId", getAppraisalId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("projectId", getProjectId());
		attributes.put("evaluationId", getEvaluationId());
		attributes.put("goaldetailId", getGoaldetailId());
		attributes.put("ratingIdEmp", getRatingIdEmp());
		attributes.put("ratingIdMan", getRatingIdMan());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("modifiedBy", getModifiedBy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long appraisalGoalDetailsId = (Long)attributes.get(
				"appraisalGoalDetailsId");

		if (appraisalGoalDetailsId != null) {
			setAppraisalGoalDetailsId(appraisalGoalDetailsId);
		}

		Long appraisalGoalMasterId = (Long)attributes.get(
				"appraisalGoalMasterId");

		if (appraisalGoalMasterId != null) {
			setAppraisalGoalMasterId(appraisalGoalMasterId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long appraisalId = (Long)attributes.get("appraisalId");

		if (appraisalId != null) {
			setAppraisalId(appraisalId);
		}

		Long employeeId = (Long)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Long projectId = (Long)attributes.get("projectId");

		if (projectId != null) {
			setProjectId(projectId);
		}

		Long evaluationId = (Long)attributes.get("evaluationId");

		if (evaluationId != null) {
			setEvaluationId(evaluationId);
		}

		Long goaldetailId = (Long)attributes.get("goaldetailId");

		if (goaldetailId != null) {
			setGoaldetailId(goaldetailId);
		}

		Long ratingIdEmp = (Long)attributes.get("ratingIdEmp");

		if (ratingIdEmp != null) {
			setRatingIdEmp(ratingIdEmp);
		}

		Long ratingIdMan = (Long)attributes.get("ratingIdMan");

		if (ratingIdMan != null) {
			setRatingIdMan(ratingIdMan);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Long createdBy = (Long)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long modifiedBy = (Long)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}
	}

	@JSON
	@Override
	public long getAppraisalGoalDetailsId() {
		return _appraisalGoalDetailsId;
	}

	@Override
	public void setAppraisalGoalDetailsId(long appraisalGoalDetailsId) {
		_appraisalGoalDetailsId = appraisalGoalDetailsId;
	}

	@JSON
	@Override
	public long getAppraisalGoalMasterId() {
		return _appraisalGoalMasterId;
	}

	@Override
	public void setAppraisalGoalMasterId(long appraisalGoalMasterId) {
		_appraisalGoalMasterId = appraisalGoalMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getAppraisalId() {
		return _appraisalId;
	}

	@Override
	public void setAppraisalId(long appraisalId) {
		_columnBitmask |= APPRAISALID_COLUMN_BITMASK;

		if (!_setOriginalAppraisalId) {
			_setOriginalAppraisalId = true;

			_originalAppraisalId = _appraisalId;
		}

		_appraisalId = appraisalId;
	}

	public long getOriginalAppraisalId() {
		return _originalAppraisalId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_columnBitmask |= EMPLOYEEID_COLUMN_BITMASK;

		if (!_setOriginalEmployeeId) {
			_setOriginalEmployeeId = true;

			_originalEmployeeId = _employeeId;
		}

		_employeeId = employeeId;
	}

	public long getOriginalEmployeeId() {
		return _originalEmployeeId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getEvaluationId() {
		return _evaluationId;
	}

	@Override
	public void setEvaluationId(long evaluationId) {
		_columnBitmask |= EVALUATIONID_COLUMN_BITMASK;

		if (!_setOriginalEvaluationId) {
			_setOriginalEvaluationId = true;

			_originalEvaluationId = _evaluationId;
		}

		_evaluationId = evaluationId;
	}

	public long getOriginalEvaluationId() {
		return _originalEvaluationId;
	}

	@JSON
	@Override
	public long getGoaldetailId() {
		return _goaldetailId;
	}

	@Override
	public void setGoaldetailId(long goaldetailId) {
		_columnBitmask |= GOALDETAILID_COLUMN_BITMASK;

		if (!_setOriginalGoaldetailId) {
			_setOriginalGoaldetailId = true;

			_originalGoaldetailId = _goaldetailId;
		}

		_goaldetailId = goaldetailId;
	}

	public long getOriginalGoaldetailId() {
		return _originalGoaldetailId;
	}

	@JSON
	@Override
	public long getRatingIdEmp() {
		return _ratingIdEmp;
	}

	@Override
	public void setRatingIdEmp(long ratingIdEmp) {
		_ratingIdEmp = ratingIdEmp;
	}

	@JSON
	@Override
	public long getRatingIdMan() {
		return _ratingIdMan;
	}

	@Override
	public void setRatingIdMan(long ratingIdMan) {
		_ratingIdMan = ratingIdMan;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AppraisalGoalDetails.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalGoalDetails toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AppraisalGoalDetails)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalGoalDetailsImpl appraisalGoalDetailsImpl = new AppraisalGoalDetailsImpl();

		appraisalGoalDetailsImpl.setAppraisalGoalDetailsId(getAppraisalGoalDetailsId());
		appraisalGoalDetailsImpl.setAppraisalGoalMasterId(getAppraisalGoalMasterId());
		appraisalGoalDetailsImpl.setCompanyId(getCompanyId());
		appraisalGoalDetailsImpl.setAppraisalId(getAppraisalId());
		appraisalGoalDetailsImpl.setEmployeeId(getEmployeeId());
		appraisalGoalDetailsImpl.setProjectId(getProjectId());
		appraisalGoalDetailsImpl.setEvaluationId(getEvaluationId());
		appraisalGoalDetailsImpl.setGoaldetailId(getGoaldetailId());
		appraisalGoalDetailsImpl.setRatingIdEmp(getRatingIdEmp());
		appraisalGoalDetailsImpl.setRatingIdMan(getRatingIdMan());
		appraisalGoalDetailsImpl.setCreatedDate(getCreatedDate());
		appraisalGoalDetailsImpl.setCreatedBy(getCreatedBy());
		appraisalGoalDetailsImpl.setModifiedDate(getModifiedDate());
		appraisalGoalDetailsImpl.setModifiedBy(getModifiedBy());

		appraisalGoalDetailsImpl.resetOriginalValues();

		return appraisalGoalDetailsImpl;
	}

	@Override
	public int compareTo(AppraisalGoalDetails appraisalGoalDetails) {
		long primaryKey = appraisalGoalDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AppraisalGoalDetails)) {
			return false;
		}

		AppraisalGoalDetails appraisalGoalDetails = (AppraisalGoalDetails)obj;

		long primaryKey = appraisalGoalDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AppraisalGoalDetailsModelImpl appraisalGoalDetailsModelImpl = this;

		appraisalGoalDetailsModelImpl._originalAppraisalId = appraisalGoalDetailsModelImpl._appraisalId;

		appraisalGoalDetailsModelImpl._setOriginalAppraisalId = false;

		appraisalGoalDetailsModelImpl._originalEmployeeId = appraisalGoalDetailsModelImpl._employeeId;

		appraisalGoalDetailsModelImpl._setOriginalEmployeeId = false;

		appraisalGoalDetailsModelImpl._originalProjectId = appraisalGoalDetailsModelImpl._projectId;

		appraisalGoalDetailsModelImpl._setOriginalProjectId = false;

		appraisalGoalDetailsModelImpl._originalEvaluationId = appraisalGoalDetailsModelImpl._evaluationId;

		appraisalGoalDetailsModelImpl._setOriginalEvaluationId = false;

		appraisalGoalDetailsModelImpl._originalGoaldetailId = appraisalGoalDetailsModelImpl._goaldetailId;

		appraisalGoalDetailsModelImpl._setOriginalGoaldetailId = false;

		appraisalGoalDetailsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalGoalDetails> toCacheModel() {
		AppraisalGoalDetailsCacheModel appraisalGoalDetailsCacheModel = new AppraisalGoalDetailsCacheModel();

		appraisalGoalDetailsCacheModel.appraisalGoalDetailsId = getAppraisalGoalDetailsId();

		appraisalGoalDetailsCacheModel.appraisalGoalMasterId = getAppraisalGoalMasterId();

		appraisalGoalDetailsCacheModel.companyId = getCompanyId();

		appraisalGoalDetailsCacheModel.appraisalId = getAppraisalId();

		appraisalGoalDetailsCacheModel.employeeId = getEmployeeId();

		appraisalGoalDetailsCacheModel.projectId = getProjectId();

		appraisalGoalDetailsCacheModel.evaluationId = getEvaluationId();

		appraisalGoalDetailsCacheModel.goaldetailId = getGoaldetailId();

		appraisalGoalDetailsCacheModel.ratingIdEmp = getRatingIdEmp();

		appraisalGoalDetailsCacheModel.ratingIdMan = getRatingIdMan();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			appraisalGoalDetailsCacheModel.createdDate = createdDate.getTime();
		}
		else {
			appraisalGoalDetailsCacheModel.createdDate = Long.MIN_VALUE;
		}

		appraisalGoalDetailsCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalGoalDetailsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appraisalGoalDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalGoalDetailsCacheModel.modifiedBy = getModifiedBy();

		return appraisalGoalDetailsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{appraisalGoalDetailsId=");
		sb.append(getAppraisalGoalDetailsId());
		sb.append(", appraisalGoalMasterId=");
		sb.append(getAppraisalGoalMasterId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", appraisalId=");
		sb.append(getAppraisalId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", projectId=");
		sb.append(getProjectId());
		sb.append(", evaluationId=");
		sb.append(getEvaluationId());
		sb.append(", goaldetailId=");
		sb.append(getGoaldetailId());
		sb.append(", ratingIdEmp=");
		sb.append(getRatingIdEmp());
		sb.append(", ratingIdMan=");
		sb.append(getRatingIdMan());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.liferay.famocom.erpcloud.model.AppraisalGoalDetails");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>appraisalGoalDetailsId</column-name><column-value><![CDATA[");
		sb.append(getAppraisalGoalDetailsId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>appraisalGoalMasterId</column-name><column-value><![CDATA[");
		sb.append(getAppraisalGoalMasterId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>appraisalId</column-name><column-value><![CDATA[");
		sb.append(getAppraisalId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectId</column-name><column-value><![CDATA[");
		sb.append(getProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evaluationId</column-name><column-value><![CDATA[");
		sb.append(getEvaluationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>goaldetailId</column-name><column-value><![CDATA[");
		sb.append(getGoaldetailId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ratingIdEmp</column-name><column-value><![CDATA[");
		sb.append(getRatingIdEmp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ratingIdMan</column-name><column-value><![CDATA[");
		sb.append(getRatingIdMan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AppraisalGoalDetails.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AppraisalGoalDetails.class, ModelWrapper.class
		};
	private long _appraisalGoalDetailsId;
	private long _appraisalGoalMasterId;
	private long _companyId;
	private long _appraisalId;
	private long _originalAppraisalId;
	private boolean _setOriginalAppraisalId;
	private long _employeeId;
	private long _originalEmployeeId;
	private boolean _setOriginalEmployeeId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _evaluationId;
	private long _originalEvaluationId;
	private boolean _setOriginalEvaluationId;
	private long _goaldetailId;
	private long _originalGoaldetailId;
	private boolean _setOriginalGoaldetailId;
	private long _ratingIdEmp;
	private long _ratingIdMan;
	private Date _createdDate;
	private long _createdBy;
	private Date _modifiedDate;
	private long _modifiedBy;
	private long _columnBitmask;
	private AppraisalGoalDetails _escapedModel;
}