/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.famocom.erpcloud.model.AttendanceBio;
import com.liferay.famocom.erpcloud.model.AttendanceBioModel;
import com.liferay.famocom.erpcloud.model.AttendanceBioSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AttendanceBio service. Represents a row in the &quot;attendanceBio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AttendanceBioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttendanceBioImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AttendanceBioImpl
 * @see AttendanceBio
 * @see AttendanceBioModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AttendanceBioModelImpl extends BaseModelImpl<AttendanceBio>
	implements AttendanceBioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a attendance bio model instance should use the {@link AttendanceBio} interface instead.
	 */
	public static final String TABLE_NAME = "attendanceBio";
	public static final Object[][] TABLE_COLUMNS = {
			{ "attendanceBioId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "employeeId", Types.BIGINT },
			{ "attDate", Types.TIMESTAMP },
			{ "attTime", Types.VARCHAR },
			{ "uploadDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("attendanceBioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("attDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("attTime", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uploadDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table attendanceBio (attendanceBioId LONG not null primary key,companyId LONG,employeeId LONG,attDate DATE null,attTime VARCHAR(75) null,uploadDate DATE null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table attendanceBio";
	public static final String ORDER_BY_JPQL = " ORDER BY attendanceBio.attendanceBioId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY attendanceBio.attendanceBioId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.famocom.erpcloud.model.AttendanceBio"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.famocom.erpcloud.model.AttendanceBio"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.famocom.erpcloud.model.AttendanceBio"),
			true);
	public static final long ATTDATE_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long EMPLOYEEID_COLUMN_BITMASK = 4L;
	public static final long ATTENDANCEBIOID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AttendanceBio toModel(AttendanceBioSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AttendanceBio model = new AttendanceBioImpl();

		model.setAttendanceBioId(soapModel.getAttendanceBioId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setAttDate(soapModel.getAttDate());
		model.setAttTime(soapModel.getAttTime());
		model.setUploadDate(soapModel.getUploadDate());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AttendanceBio> toModels(AttendanceBioSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AttendanceBio> models = new ArrayList<AttendanceBio>(soapModels.length);

		for (AttendanceBioSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.famocom.erpcloud.model.AttendanceBio"));

	public AttendanceBioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _attendanceBioId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAttendanceBioId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _attendanceBioId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AttendanceBio.class;
	}

	@Override
	public String getModelClassName() {
		return AttendanceBio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("attendanceBioId", getAttendanceBioId());
		attributes.put("companyId", getCompanyId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("attDate", getAttDate());
		attributes.put("attTime", getAttTime());
		attributes.put("uploadDate", getUploadDate());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long attendanceBioId = (Long)attributes.get("attendanceBioId");

		if (attendanceBioId != null) {
			setAttendanceBioId(attendanceBioId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long employeeId = (Long)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Date attDate = (Date)attributes.get("attDate");

		if (attDate != null) {
			setAttDate(attDate);
		}

		String attTime = (String)attributes.get("attTime");

		if (attTime != null) {
			setAttTime(attTime);
		}

		Date uploadDate = (Date)attributes.get("uploadDate");

		if (uploadDate != null) {
			setUploadDate(uploadDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getAttendanceBioId() {
		return _attendanceBioId;
	}

	@Override
	public void setAttendanceBioId(long attendanceBioId) {
		_attendanceBioId = attendanceBioId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_columnBitmask |= EMPLOYEEID_COLUMN_BITMASK;

		if (!_setOriginalEmployeeId) {
			_setOriginalEmployeeId = true;

			_originalEmployeeId = _employeeId;
		}

		_employeeId = employeeId;
	}

	public long getOriginalEmployeeId() {
		return _originalEmployeeId;
	}

	@JSON
	@Override
	public Date getAttDate() {
		return _attDate;
	}

	@Override
	public void setAttDate(Date attDate) {
		_columnBitmask |= ATTDATE_COLUMN_BITMASK;

		if (_originalAttDate == null) {
			_originalAttDate = _attDate;
		}

		_attDate = attDate;
	}

	public Date getOriginalAttDate() {
		return _originalAttDate;
	}

	@JSON
	@Override
	public String getAttTime() {
		if (_attTime == null) {
			return "";
		}
		else {
			return _attTime;
		}
	}

	@Override
	public void setAttTime(String attTime) {
		_attTime = attTime;
	}

	@JSON
	@Override
	public Date getUploadDate() {
		return _uploadDate;
	}

	@Override
	public void setUploadDate(Date uploadDate) {
		_uploadDate = uploadDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AttendanceBio.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AttendanceBio toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AttendanceBio)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AttendanceBioImpl attendanceBioImpl = new AttendanceBioImpl();

		attendanceBioImpl.setAttendanceBioId(getAttendanceBioId());
		attendanceBioImpl.setCompanyId(getCompanyId());
		attendanceBioImpl.setEmployeeId(getEmployeeId());
		attendanceBioImpl.setAttDate(getAttDate());
		attendanceBioImpl.setAttTime(getAttTime());
		attendanceBioImpl.setUploadDate(getUploadDate());
		attendanceBioImpl.setStatus(getStatus());

		attendanceBioImpl.resetOriginalValues();

		return attendanceBioImpl;
	}

	@Override
	public int compareTo(AttendanceBio attendanceBio) {
		long primaryKey = attendanceBio.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AttendanceBio)) {
			return false;
		}

		AttendanceBio attendanceBio = (AttendanceBio)obj;

		long primaryKey = attendanceBio.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AttendanceBioModelImpl attendanceBioModelImpl = this;

		attendanceBioModelImpl._originalCompanyId = attendanceBioModelImpl._companyId;

		attendanceBioModelImpl._setOriginalCompanyId = false;

		attendanceBioModelImpl._originalEmployeeId = attendanceBioModelImpl._employeeId;

		attendanceBioModelImpl._setOriginalEmployeeId = false;

		attendanceBioModelImpl._originalAttDate = attendanceBioModelImpl._attDate;

		attendanceBioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AttendanceBio> toCacheModel() {
		AttendanceBioCacheModel attendanceBioCacheModel = new AttendanceBioCacheModel();

		attendanceBioCacheModel.attendanceBioId = getAttendanceBioId();

		attendanceBioCacheModel.companyId = getCompanyId();

		attendanceBioCacheModel.employeeId = getEmployeeId();

		Date attDate = getAttDate();

		if (attDate != null) {
			attendanceBioCacheModel.attDate = attDate.getTime();
		}
		else {
			attendanceBioCacheModel.attDate = Long.MIN_VALUE;
		}

		attendanceBioCacheModel.attTime = getAttTime();

		String attTime = attendanceBioCacheModel.attTime;

		if ((attTime != null) && (attTime.length() == 0)) {
			attendanceBioCacheModel.attTime = null;
		}

		Date uploadDate = getUploadDate();

		if (uploadDate != null) {
			attendanceBioCacheModel.uploadDate = uploadDate.getTime();
		}
		else {
			attendanceBioCacheModel.uploadDate = Long.MIN_VALUE;
		}

		attendanceBioCacheModel.status = getStatus();

		return attendanceBioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{attendanceBioId=");
		sb.append(getAttendanceBioId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", attDate=");
		sb.append(getAttDate());
		sb.append(", attTime=");
		sb.append(getAttTime());
		sb.append(", uploadDate=");
		sb.append(getUploadDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.liferay.famocom.erpcloud.model.AttendanceBio");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>attendanceBioId</column-name><column-value><![CDATA[");
		sb.append(getAttendanceBioId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attDate</column-name><column-value><![CDATA[");
		sb.append(getAttDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attTime</column-name><column-value><![CDATA[");
		sb.append(getAttTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uploadDate</column-name><column-value><![CDATA[");
		sb.append(getUploadDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AttendanceBio.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AttendanceBio.class, ModelWrapper.class
		};
	private long _attendanceBioId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _employeeId;
	private long _originalEmployeeId;
	private boolean _setOriginalEmployeeId;
	private Date _attDate;
	private Date _originalAttDate;
	private String _attTime;
	private Date _uploadDate;
	private int _status;
	private long _columnBitmask;
	private AttendanceBio _escapedModel;
}