/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.famocom.erpcloud.model.BillDocumentUploadFile;
import com.liferay.famocom.erpcloud.model.BillDocumentUploadFileModel;
import com.liferay.famocom.erpcloud.model.BillDocumentUploadFileSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BillDocumentUploadFile service. Represents a row in the &quot;billDocumentUploadFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link BillDocumentUploadFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BillDocumentUploadFileImpl}.
 * </p>
 *
 * @author Samaresh
 * @see BillDocumentUploadFileImpl
 * @see BillDocumentUploadFile
 * @see BillDocumentUploadFileModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class BillDocumentUploadFileModelImpl extends BaseModelImpl<BillDocumentUploadFile>
	implements BillDocumentUploadFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bill document upload file model instance should use the {@link BillDocumentUploadFile} interface instead.
	 */
	public static final String TABLE_NAME = "billDocumentUploadFile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "documentId", Types.BIGINT },
			{ "dlFileEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "billingId", Types.BIGINT },
			{ "documentName", Types.VARCHAR },
			{ "documentPath", Types.VARCHAR },
			{ "uploadDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("documentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dlFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("billingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentPath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uploadDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table billDocumentUploadFile (documentId LONG not null primary key,dlFileEntryId LONG,companyId LONG,billingId LONG,documentName VARCHAR(75) null,documentPath VARCHAR(75) null,uploadDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table billDocumentUploadFile";
	public static final String ORDER_BY_JPQL = " ORDER BY billDocumentUploadFile.documentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY billDocumentUploadFile.documentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.famocom.erpcloud.model.BillDocumentUploadFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.famocom.erpcloud.model.BillDocumentUploadFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BillDocumentUploadFile toModel(
		BillDocumentUploadFileSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BillDocumentUploadFile model = new BillDocumentUploadFileImpl();

		model.setDocumentId(soapModel.getDocumentId());
		model.setDlFileEntryId(soapModel.getDlFileEntryId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setBillingId(soapModel.getBillingId());
		model.setDocumentName(soapModel.getDocumentName());
		model.setDocumentPath(soapModel.getDocumentPath());
		model.setUploadDate(soapModel.getUploadDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BillDocumentUploadFile> toModels(
		BillDocumentUploadFileSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BillDocumentUploadFile> models = new ArrayList<BillDocumentUploadFile>(soapModels.length);

		for (BillDocumentUploadFileSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.famocom.erpcloud.model.BillDocumentUploadFile"));

	public BillDocumentUploadFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _documentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDocumentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _documentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BillDocumentUploadFile.class;
	}

	@Override
	public String getModelClassName() {
		return BillDocumentUploadFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("documentId", getDocumentId());
		attributes.put("dlFileEntryId", getDlFileEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("billingId", getBillingId());
		attributes.put("documentName", getDocumentName());
		attributes.put("documentPath", getDocumentPath());
		attributes.put("uploadDate", getUploadDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long documentId = (Long)attributes.get("documentId");

		if (documentId != null) {
			setDocumentId(documentId);
		}

		Long dlFileEntryId = (Long)attributes.get("dlFileEntryId");

		if (dlFileEntryId != null) {
			setDlFileEntryId(dlFileEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long billingId = (Long)attributes.get("billingId");

		if (billingId != null) {
			setBillingId(billingId);
		}

		String documentName = (String)attributes.get("documentName");

		if (documentName != null) {
			setDocumentName(documentName);
		}

		String documentPath = (String)attributes.get("documentPath");

		if (documentPath != null) {
			setDocumentPath(documentPath);
		}

		Date uploadDate = (Date)attributes.get("uploadDate");

		if (uploadDate != null) {
			setUploadDate(uploadDate);
		}
	}

	@JSON
	@Override
	public long getDocumentId() {
		return _documentId;
	}

	@Override
	public void setDocumentId(long documentId) {
		_documentId = documentId;
	}

	@JSON
	@Override
	public long getDlFileEntryId() {
		return _dlFileEntryId;
	}

	@Override
	public void setDlFileEntryId(long dlFileEntryId) {
		_dlFileEntryId = dlFileEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getBillingId() {
		return _billingId;
	}

	@Override
	public void setBillingId(long billingId) {
		_billingId = billingId;
	}

	@JSON
	@Override
	public String getDocumentName() {
		if (_documentName == null) {
			return "";
		}
		else {
			return _documentName;
		}
	}

	@Override
	public void setDocumentName(String documentName) {
		_documentName = documentName;
	}

	@JSON
	@Override
	public String getDocumentPath() {
		if (_documentPath == null) {
			return "";
		}
		else {
			return _documentPath;
		}
	}

	@Override
	public void setDocumentPath(String documentPath) {
		_documentPath = documentPath;
	}

	@JSON
	@Override
	public Date getUploadDate() {
		return _uploadDate;
	}

	@Override
	public void setUploadDate(Date uploadDate) {
		_uploadDate = uploadDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			BillDocumentUploadFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BillDocumentUploadFile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BillDocumentUploadFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BillDocumentUploadFileImpl billDocumentUploadFileImpl = new BillDocumentUploadFileImpl();

		billDocumentUploadFileImpl.setDocumentId(getDocumentId());
		billDocumentUploadFileImpl.setDlFileEntryId(getDlFileEntryId());
		billDocumentUploadFileImpl.setCompanyId(getCompanyId());
		billDocumentUploadFileImpl.setBillingId(getBillingId());
		billDocumentUploadFileImpl.setDocumentName(getDocumentName());
		billDocumentUploadFileImpl.setDocumentPath(getDocumentPath());
		billDocumentUploadFileImpl.setUploadDate(getUploadDate());

		billDocumentUploadFileImpl.resetOriginalValues();

		return billDocumentUploadFileImpl;
	}

	@Override
	public int compareTo(BillDocumentUploadFile billDocumentUploadFile) {
		long primaryKey = billDocumentUploadFile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BillDocumentUploadFile)) {
			return false;
		}

		BillDocumentUploadFile billDocumentUploadFile = (BillDocumentUploadFile)obj;

		long primaryKey = billDocumentUploadFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<BillDocumentUploadFile> toCacheModel() {
		BillDocumentUploadFileCacheModel billDocumentUploadFileCacheModel = new BillDocumentUploadFileCacheModel();

		billDocumentUploadFileCacheModel.documentId = getDocumentId();

		billDocumentUploadFileCacheModel.dlFileEntryId = getDlFileEntryId();

		billDocumentUploadFileCacheModel.companyId = getCompanyId();

		billDocumentUploadFileCacheModel.billingId = getBillingId();

		billDocumentUploadFileCacheModel.documentName = getDocumentName();

		String documentName = billDocumentUploadFileCacheModel.documentName;

		if ((documentName != null) && (documentName.length() == 0)) {
			billDocumentUploadFileCacheModel.documentName = null;
		}

		billDocumentUploadFileCacheModel.documentPath = getDocumentPath();

		String documentPath = billDocumentUploadFileCacheModel.documentPath;

		if ((documentPath != null) && (documentPath.length() == 0)) {
			billDocumentUploadFileCacheModel.documentPath = null;
		}

		Date uploadDate = getUploadDate();

		if (uploadDate != null) {
			billDocumentUploadFileCacheModel.uploadDate = uploadDate.getTime();
		}
		else {
			billDocumentUploadFileCacheModel.uploadDate = Long.MIN_VALUE;
		}

		return billDocumentUploadFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{documentId=");
		sb.append(getDocumentId());
		sb.append(", dlFileEntryId=");
		sb.append(getDlFileEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", billingId=");
		sb.append(getBillingId());
		sb.append(", documentName=");
		sb.append(getDocumentName());
		sb.append(", documentPath=");
		sb.append(getDocumentPath());
		sb.append(", uploadDate=");
		sb.append(getUploadDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.liferay.famocom.erpcloud.model.BillDocumentUploadFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>documentId</column-name><column-value><![CDATA[");
		sb.append(getDocumentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dlFileEntryId</column-name><column-value><![CDATA[");
		sb.append(getDlFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>billingId</column-name><column-value><![CDATA[");
		sb.append(getBillingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentName</column-name><column-value><![CDATA[");
		sb.append(getDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentPath</column-name><column-value><![CDATA[");
		sb.append(getDocumentPath());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uploadDate</column-name><column-value><![CDATA[");
		sb.append(getUploadDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = BillDocumentUploadFile.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			BillDocumentUploadFile.class, ModelWrapper.class
		};
	private long _documentId;
	private long _dlFileEntryId;
	private long _companyId;
	private long _billingId;
	private String _documentName;
	private String _documentPath;
	private Date _uploadDate;
	private BillDocumentUploadFile _escapedModel;
}