/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.famocom.erpcloud.model.DocumentUploadFile;
import com.liferay.famocom.erpcloud.model.DocumentUploadFileModel;
import com.liferay.famocom.erpcloud.model.DocumentUploadFileSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DocumentUploadFile service. Represents a row in the &quot;documentUploadFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DocumentUploadFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentUploadFileImpl}.
 * </p>
 *
 * @author Samaresh
 * @see DocumentUploadFileImpl
 * @see DocumentUploadFile
 * @see DocumentUploadFileModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DocumentUploadFileModelImpl extends BaseModelImpl<DocumentUploadFile>
	implements DocumentUploadFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document upload file model instance should use the {@link DocumentUploadFile} interface instead.
	 */
	public static final String TABLE_NAME = "documentUploadFile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "documentId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "employeeId", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT },
			{ "documentName", Types.VARCHAR },
			{ "documentPath", Types.VARCHAR },
			{ "uploadDate", Types.TIMESTAMP },
			{ "travelDetailsId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("documentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentPath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uploadDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("travelDetailsId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table documentUploadFile (documentId LONG not null primary key,companyId LONG,employeeId LONG,fileEntryId LONG,documentName VARCHAR(75) null,documentPath VARCHAR(75) null,uploadDate DATE null,travelDetailsId LONG)";
	public static final String TABLE_SQL_DROP = "drop table documentUploadFile";
	public static final String ORDER_BY_JPQL = " ORDER BY documentUploadFile.documentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY documentUploadFile.documentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.famocom.erpcloud.model.DocumentUploadFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.famocom.erpcloud.model.DocumentUploadFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DocumentUploadFile toModel(DocumentUploadFileSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DocumentUploadFile model = new DocumentUploadFileImpl();

		model.setDocumentId(soapModel.getDocumentId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setDocumentName(soapModel.getDocumentName());
		model.setDocumentPath(soapModel.getDocumentPath());
		model.setUploadDate(soapModel.getUploadDate());
		model.setTravelDetailsId(soapModel.getTravelDetailsId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DocumentUploadFile> toModels(
		DocumentUploadFileSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DocumentUploadFile> models = new ArrayList<DocumentUploadFile>(soapModels.length);

		for (DocumentUploadFileSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.famocom.erpcloud.model.DocumentUploadFile"));

	public DocumentUploadFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _documentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDocumentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _documentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DocumentUploadFile.class;
	}

	@Override
	public String getModelClassName() {
		return DocumentUploadFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("documentId", getDocumentId());
		attributes.put("companyId", getCompanyId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("documentName", getDocumentName());
		attributes.put("documentPath", getDocumentPath());
		attributes.put("uploadDate", getUploadDate());
		attributes.put("travelDetailsId", getTravelDetailsId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long documentId = (Long)attributes.get("documentId");

		if (documentId != null) {
			setDocumentId(documentId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long employeeId = (Long)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		String documentName = (String)attributes.get("documentName");

		if (documentName != null) {
			setDocumentName(documentName);
		}

		String documentPath = (String)attributes.get("documentPath");

		if (documentPath != null) {
			setDocumentPath(documentPath);
		}

		Date uploadDate = (Date)attributes.get("uploadDate");

		if (uploadDate != null) {
			setUploadDate(uploadDate);
		}

		Long travelDetailsId = (Long)attributes.get("travelDetailsId");

		if (travelDetailsId != null) {
			setTravelDetailsId(travelDetailsId);
		}
	}

	@JSON
	@Override
	public long getDocumentId() {
		return _documentId;
	}

	@Override
	public void setDocumentId(long documentId) {
		_documentId = documentId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_fileEntryId = fileEntryId;
	}

	@JSON
	@Override
	public String getDocumentName() {
		if (_documentName == null) {
			return "";
		}
		else {
			return _documentName;
		}
	}

	@Override
	public void setDocumentName(String documentName) {
		_documentName = documentName;
	}

	@JSON
	@Override
	public String getDocumentPath() {
		if (_documentPath == null) {
			return "";
		}
		else {
			return _documentPath;
		}
	}

	@Override
	public void setDocumentPath(String documentPath) {
		_documentPath = documentPath;
	}

	@JSON
	@Override
	public Date getUploadDate() {
		return _uploadDate;
	}

	@Override
	public void setUploadDate(Date uploadDate) {
		_uploadDate = uploadDate;
	}

	@JSON
	@Override
	public long getTravelDetailsId() {
		return _travelDetailsId;
	}

	@Override
	public void setTravelDetailsId(long travelDetailsId) {
		_travelDetailsId = travelDetailsId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DocumentUploadFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DocumentUploadFile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DocumentUploadFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DocumentUploadFileImpl documentUploadFileImpl = new DocumentUploadFileImpl();

		documentUploadFileImpl.setDocumentId(getDocumentId());
		documentUploadFileImpl.setCompanyId(getCompanyId());
		documentUploadFileImpl.setEmployeeId(getEmployeeId());
		documentUploadFileImpl.setFileEntryId(getFileEntryId());
		documentUploadFileImpl.setDocumentName(getDocumentName());
		documentUploadFileImpl.setDocumentPath(getDocumentPath());
		documentUploadFileImpl.setUploadDate(getUploadDate());
		documentUploadFileImpl.setTravelDetailsId(getTravelDetailsId());

		documentUploadFileImpl.resetOriginalValues();

		return documentUploadFileImpl;
	}

	@Override
	public int compareTo(DocumentUploadFile documentUploadFile) {
		long primaryKey = documentUploadFile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DocumentUploadFile)) {
			return false;
		}

		DocumentUploadFile documentUploadFile = (DocumentUploadFile)obj;

		long primaryKey = documentUploadFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DocumentUploadFile> toCacheModel() {
		DocumentUploadFileCacheModel documentUploadFileCacheModel = new DocumentUploadFileCacheModel();

		documentUploadFileCacheModel.documentId = getDocumentId();

		documentUploadFileCacheModel.companyId = getCompanyId();

		documentUploadFileCacheModel.employeeId = getEmployeeId();

		documentUploadFileCacheModel.fileEntryId = getFileEntryId();

		documentUploadFileCacheModel.documentName = getDocumentName();

		String documentName = documentUploadFileCacheModel.documentName;

		if ((documentName != null) && (documentName.length() == 0)) {
			documentUploadFileCacheModel.documentName = null;
		}

		documentUploadFileCacheModel.documentPath = getDocumentPath();

		String documentPath = documentUploadFileCacheModel.documentPath;

		if ((documentPath != null) && (documentPath.length() == 0)) {
			documentUploadFileCacheModel.documentPath = null;
		}

		Date uploadDate = getUploadDate();

		if (uploadDate != null) {
			documentUploadFileCacheModel.uploadDate = uploadDate.getTime();
		}
		else {
			documentUploadFileCacheModel.uploadDate = Long.MIN_VALUE;
		}

		documentUploadFileCacheModel.travelDetailsId = getTravelDetailsId();

		return documentUploadFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{documentId=");
		sb.append(getDocumentId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", documentName=");
		sb.append(getDocumentName());
		sb.append(", documentPath=");
		sb.append(getDocumentPath());
		sb.append(", uploadDate=");
		sb.append(getUploadDate());
		sb.append(", travelDetailsId=");
		sb.append(getTravelDetailsId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.famocom.erpcloud.model.DocumentUploadFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>documentId</column-name><column-value><![CDATA[");
		sb.append(getDocumentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentName</column-name><column-value><![CDATA[");
		sb.append(getDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentPath</column-name><column-value><![CDATA[");
		sb.append(getDocumentPath());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uploadDate</column-name><column-value><![CDATA[");
		sb.append(getUploadDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>travelDetailsId</column-name><column-value><![CDATA[");
		sb.append(getTravelDetailsId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = DocumentUploadFile.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			DocumentUploadFile.class, ModelWrapper.class
		};
	private long _documentId;
	private long _companyId;
	private long _employeeId;
	private long _fileEntryId;
	private String _documentName;
	private String _documentPath;
	private Date _uploadDate;
	private long _travelDetailsId;
	private DocumentUploadFile _escapedModel;
}