/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.famocom.erpcloud.model.ExpProofFiles;
import com.liferay.famocom.erpcloud.model.ExpProofFilesModel;
import com.liferay.famocom.erpcloud.model.ExpProofFilesSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ExpProofFiles service. Represents a row in the &quot;expProofFiles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ExpProofFilesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExpProofFilesImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ExpProofFilesImpl
 * @see ExpProofFiles
 * @see ExpProofFilesModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ExpProofFilesModelImpl extends BaseModelImpl<ExpProofFiles>
	implements ExpProofFilesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a exp proof files model instance should use the {@link ExpProofFiles} interface instead.
	 */
	public static final String TABLE_NAME = "expProofFiles";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fileId", Types.BIGINT },
			{ "financialYear", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "employeeId", Types.BIGINT },
			{ "expenseId", Types.BIGINT },
			{ "fileName", Types.VARCHAR },
			{ "fileOrigName", Types.VARCHAR },
			{ "filePath", Types.VARCHAR },
			{ "proofName", Types.VARCHAR },
			{ "uploadDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("financialYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("expenseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileOrigName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("filePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("proofName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uploadDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table expProofFiles (fileId LONG not null primary key,financialYear VARCHAR(75) null,companyId LONG,employeeId LONG,expenseId LONG,fileName VARCHAR(75) null,fileOrigName VARCHAR(75) null,filePath VARCHAR(75) null,proofName VARCHAR(75) null,uploadDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table expProofFiles";
	public static final String ORDER_BY_JPQL = " ORDER BY expProofFiles.fileId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY expProofFiles.fileId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.famocom.erpcloud.model.ExpProofFiles"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.famocom.erpcloud.model.ExpProofFiles"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.famocom.erpcloud.model.ExpProofFiles"),
			true);
	public static final long EXPENSEID_COLUMN_BITMASK = 1L;
	public static final long FILEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ExpProofFiles toModel(ExpProofFilesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ExpProofFiles model = new ExpProofFilesImpl();

		model.setFileId(soapModel.getFileId());
		model.setFinancialYear(soapModel.getFinancialYear());
		model.setCompanyId(soapModel.getCompanyId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setExpenseId(soapModel.getExpenseId());
		model.setFileName(soapModel.getFileName());
		model.setFileOrigName(soapModel.getFileOrigName());
		model.setFilePath(soapModel.getFilePath());
		model.setProofName(soapModel.getProofName());
		model.setUploadDate(soapModel.getUploadDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ExpProofFiles> toModels(ExpProofFilesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ExpProofFiles> models = new ArrayList<ExpProofFiles>(soapModels.length);

		for (ExpProofFilesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.famocom.erpcloud.model.ExpProofFiles"));

	public ExpProofFilesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExpProofFiles.class;
	}

	@Override
	public String getModelClassName() {
		return ExpProofFiles.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fileId", getFileId());
		attributes.put("financialYear", getFinancialYear());
		attributes.put("companyId", getCompanyId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("expenseId", getExpenseId());
		attributes.put("fileName", getFileName());
		attributes.put("fileOrigName", getFileOrigName());
		attributes.put("filePath", getFilePath());
		attributes.put("proofName", getProofName());
		attributes.put("uploadDate", getUploadDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fileId = (Long)attributes.get("fileId");

		if (fileId != null) {
			setFileId(fileId);
		}

		String financialYear = (String)attributes.get("financialYear");

		if (financialYear != null) {
			setFinancialYear(financialYear);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long employeeId = (Long)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Long expenseId = (Long)attributes.get("expenseId");

		if (expenseId != null) {
			setExpenseId(expenseId);
		}

		String fileName = (String)attributes.get("fileName");

		if (fileName != null) {
			setFileName(fileName);
		}

		String fileOrigName = (String)attributes.get("fileOrigName");

		if (fileOrigName != null) {
			setFileOrigName(fileOrigName);
		}

		String filePath = (String)attributes.get("filePath");

		if (filePath != null) {
			setFilePath(filePath);
		}

		String proofName = (String)attributes.get("proofName");

		if (proofName != null) {
			setProofName(proofName);
		}

		Date uploadDate = (Date)attributes.get("uploadDate");

		if (uploadDate != null) {
			setUploadDate(uploadDate);
		}
	}

	@JSON
	@Override
	public long getFileId() {
		return _fileId;
	}

	@Override
	public void setFileId(long fileId) {
		_fileId = fileId;
	}

	@JSON
	@Override
	public String getFinancialYear() {
		if (_financialYear == null) {
			return "";
		}
		else {
			return _financialYear;
		}
	}

	@Override
	public void setFinancialYear(String financialYear) {
		_financialYear = financialYear;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getExpenseId() {
		return _expenseId;
	}

	@Override
	public void setExpenseId(long expenseId) {
		_columnBitmask |= EXPENSEID_COLUMN_BITMASK;

		if (!_setOriginalExpenseId) {
			_setOriginalExpenseId = true;

			_originalExpenseId = _expenseId;
		}

		_expenseId = expenseId;
	}

	public long getOriginalExpenseId() {
		return _originalExpenseId;
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_fileName = fileName;
	}

	@JSON
	@Override
	public String getFileOrigName() {
		if (_fileOrigName == null) {
			return "";
		}
		else {
			return _fileOrigName;
		}
	}

	@Override
	public void setFileOrigName(String fileOrigName) {
		_fileOrigName = fileOrigName;
	}

	@JSON
	@Override
	public String getFilePath() {
		if (_filePath == null) {
			return "";
		}
		else {
			return _filePath;
		}
	}

	@Override
	public void setFilePath(String filePath) {
		_filePath = filePath;
	}

	@JSON
	@Override
	public String getProofName() {
		if (_proofName == null) {
			return "";
		}
		else {
			return _proofName;
		}
	}

	@Override
	public void setProofName(String proofName) {
		_proofName = proofName;
	}

	@JSON
	@Override
	public Date getUploadDate() {
		return _uploadDate;
	}

	@Override
	public void setUploadDate(Date uploadDate) {
		_uploadDate = uploadDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ExpProofFiles.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExpProofFiles toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ExpProofFiles)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExpProofFilesImpl expProofFilesImpl = new ExpProofFilesImpl();

		expProofFilesImpl.setFileId(getFileId());
		expProofFilesImpl.setFinancialYear(getFinancialYear());
		expProofFilesImpl.setCompanyId(getCompanyId());
		expProofFilesImpl.setEmployeeId(getEmployeeId());
		expProofFilesImpl.setExpenseId(getExpenseId());
		expProofFilesImpl.setFileName(getFileName());
		expProofFilesImpl.setFileOrigName(getFileOrigName());
		expProofFilesImpl.setFilePath(getFilePath());
		expProofFilesImpl.setProofName(getProofName());
		expProofFilesImpl.setUploadDate(getUploadDate());

		expProofFilesImpl.resetOriginalValues();

		return expProofFilesImpl;
	}

	@Override
	public int compareTo(ExpProofFiles expProofFiles) {
		long primaryKey = expProofFiles.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ExpProofFiles)) {
			return false;
		}

		ExpProofFiles expProofFiles = (ExpProofFiles)obj;

		long primaryKey = expProofFiles.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ExpProofFilesModelImpl expProofFilesModelImpl = this;

		expProofFilesModelImpl._originalExpenseId = expProofFilesModelImpl._expenseId;

		expProofFilesModelImpl._setOriginalExpenseId = false;

		expProofFilesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ExpProofFiles> toCacheModel() {
		ExpProofFilesCacheModel expProofFilesCacheModel = new ExpProofFilesCacheModel();

		expProofFilesCacheModel.fileId = getFileId();

		expProofFilesCacheModel.financialYear = getFinancialYear();

		String financialYear = expProofFilesCacheModel.financialYear;

		if ((financialYear != null) && (financialYear.length() == 0)) {
			expProofFilesCacheModel.financialYear = null;
		}

		expProofFilesCacheModel.companyId = getCompanyId();

		expProofFilesCacheModel.employeeId = getEmployeeId();

		expProofFilesCacheModel.expenseId = getExpenseId();

		expProofFilesCacheModel.fileName = getFileName();

		String fileName = expProofFilesCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			expProofFilesCacheModel.fileName = null;
		}

		expProofFilesCacheModel.fileOrigName = getFileOrigName();

		String fileOrigName = expProofFilesCacheModel.fileOrigName;

		if ((fileOrigName != null) && (fileOrigName.length() == 0)) {
			expProofFilesCacheModel.fileOrigName = null;
		}

		expProofFilesCacheModel.filePath = getFilePath();

		String filePath = expProofFilesCacheModel.filePath;

		if ((filePath != null) && (filePath.length() == 0)) {
			expProofFilesCacheModel.filePath = null;
		}

		expProofFilesCacheModel.proofName = getProofName();

		String proofName = expProofFilesCacheModel.proofName;

		if ((proofName != null) && (proofName.length() == 0)) {
			expProofFilesCacheModel.proofName = null;
		}

		Date uploadDate = getUploadDate();

		if (uploadDate != null) {
			expProofFilesCacheModel.uploadDate = uploadDate.getTime();
		}
		else {
			expProofFilesCacheModel.uploadDate = Long.MIN_VALUE;
		}

		return expProofFilesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{fileId=");
		sb.append(getFileId());
		sb.append(", financialYear=");
		sb.append(getFinancialYear());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", expenseId=");
		sb.append(getExpenseId());
		sb.append(", fileName=");
		sb.append(getFileName());
		sb.append(", fileOrigName=");
		sb.append(getFileOrigName());
		sb.append(", filePath=");
		sb.append(getFilePath());
		sb.append(", proofName=");
		sb.append(getProofName());
		sb.append(", uploadDate=");
		sb.append(getUploadDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.famocom.erpcloud.model.ExpProofFiles");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fileId</column-name><column-value><![CDATA[");
		sb.append(getFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>financialYear</column-name><column-value><![CDATA[");
		sb.append(getFinancialYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>expenseId</column-name><column-value><![CDATA[");
		sb.append(getExpenseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileName</column-name><column-value><![CDATA[");
		sb.append(getFileName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileOrigName</column-name><column-value><![CDATA[");
		sb.append(getFileOrigName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>filePath</column-name><column-value><![CDATA[");
		sb.append(getFilePath());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>proofName</column-name><column-value><![CDATA[");
		sb.append(getProofName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uploadDate</column-name><column-value><![CDATA[");
		sb.append(getUploadDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ExpProofFiles.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ExpProofFiles.class, ModelWrapper.class
		};
	private long _fileId;
	private String _financialYear;
	private long _companyId;
	private long _employeeId;
	private long _expenseId;
	private long _originalExpenseId;
	private boolean _setOriginalExpenseId;
	private String _fileName;
	private String _fileOrigName;
	private String _filePath;
	private String _proofName;
	private Date _uploadDate;
	private long _columnBitmask;
	private ExpProofFiles _escapedModel;
}