/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.famocom.erpcloud.model.Milestone;
import com.liferay.famocom.erpcloud.model.MilestoneModel;
import com.liferay.famocom.erpcloud.model.MilestoneSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Milestone service. Represents a row in the &quot;Milestone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MilestoneModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MilestoneImpl}.
 * </p>
 *
 * @author Samaresh
 * @see MilestoneImpl
 * @see Milestone
 * @see MilestoneModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MilestoneModelImpl extends BaseModelImpl<Milestone>
	implements MilestoneModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a milestone model instance should use the {@link Milestone} interface instead.
	 */
	public static final String TABLE_NAME = "Milestone";
	public static final Object[][] TABLE_COLUMNS = {
			{ "milestoneId", Types.BIGINT },
			{ "projectId", Types.BIGINT },
			{ "clientId", Types.BIGINT },
			{ "milestoneName", Types.VARCHAR },
			{ "dueDate", Types.TIMESTAMP },
			{ "checkGST", Types.INTEGER },
			{ "amount", Types.DOUBLE },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("milestoneId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("clientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("milestoneName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("checkGST", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("amount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table Milestone (milestoneId LONG not null primary key,projectId LONG,clientId LONG,milestoneName VARCHAR(75) null,dueDate DATE null,checkGST INTEGER,amount DOUBLE,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table Milestone";
	public static final String ORDER_BY_JPQL = " ORDER BY milestone.milestoneId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Milestone.milestoneId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.famocom.erpcloud.model.Milestone"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.famocom.erpcloud.model.Milestone"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Milestone toModel(MilestoneSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Milestone model = new MilestoneImpl();

		model.setMilestoneId(soapModel.getMilestoneId());
		model.setProjectId(soapModel.getProjectId());
		model.setClientId(soapModel.getClientId());
		model.setMilestoneName(soapModel.getMilestoneName());
		model.setDueDate(soapModel.getDueDate());
		model.setCheckGST(soapModel.getCheckGST());
		model.setAmount(soapModel.getAmount());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Milestone> toModels(MilestoneSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Milestone> models = new ArrayList<Milestone>(soapModels.length);

		for (MilestoneSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.famocom.erpcloud.model.Milestone"));

	public MilestoneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _milestoneId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMilestoneId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _milestoneId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Milestone.class;
	}

	@Override
	public String getModelClassName() {
		return Milestone.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("milestoneId", getMilestoneId());
		attributes.put("projectId", getProjectId());
		attributes.put("clientId", getClientId());
		attributes.put("milestoneName", getMilestoneName());
		attributes.put("dueDate", getDueDate());
		attributes.put("checkGST", getCheckGST());
		attributes.put("amount", getAmount());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long milestoneId = (Long)attributes.get("milestoneId");

		if (milestoneId != null) {
			setMilestoneId(milestoneId);
		}

		Long projectId = (Long)attributes.get("projectId");

		if (projectId != null) {
			setProjectId(projectId);
		}

		Long clientId = (Long)attributes.get("clientId");

		if (clientId != null) {
			setClientId(clientId);
		}

		String milestoneName = (String)attributes.get("milestoneName");

		if (milestoneName != null) {
			setMilestoneName(milestoneName);
		}

		Date dueDate = (Date)attributes.get("dueDate");

		if (dueDate != null) {
			setDueDate(dueDate);
		}

		Integer checkGST = (Integer)attributes.get("checkGST");

		if (checkGST != null) {
			setCheckGST(checkGST);
		}

		Double amount = (Double)attributes.get("amount");

		if (amount != null) {
			setAmount(amount);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getMilestoneId() {
		return _milestoneId;
	}

	@Override
	public void setMilestoneId(long milestoneId) {
		_milestoneId = milestoneId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_projectId = projectId;
	}

	@JSON
	@Override
	public long getClientId() {
		return _clientId;
	}

	@Override
	public void setClientId(long clientId) {
		_clientId = clientId;
	}

	@JSON
	@Override
	public String getMilestoneName() {
		if (_milestoneName == null) {
			return "";
		}
		else {
			return _milestoneName;
		}
	}

	@Override
	public void setMilestoneName(String milestoneName) {
		_milestoneName = milestoneName;
	}

	@JSON
	@Override
	public Date getDueDate() {
		return _dueDate;
	}

	@Override
	public void setDueDate(Date dueDate) {
		_dueDate = dueDate;
	}

	@JSON
	@Override
	public int getCheckGST() {
		return _checkGST;
	}

	@Override
	public void setCheckGST(int checkGST) {
		_checkGST = checkGST;
	}

	@JSON
	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		_amount = amount;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Milestone.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Milestone toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Milestone)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MilestoneImpl milestoneImpl = new MilestoneImpl();

		milestoneImpl.setMilestoneId(getMilestoneId());
		milestoneImpl.setProjectId(getProjectId());
		milestoneImpl.setClientId(getClientId());
		milestoneImpl.setMilestoneName(getMilestoneName());
		milestoneImpl.setDueDate(getDueDate());
		milestoneImpl.setCheckGST(getCheckGST());
		milestoneImpl.setAmount(getAmount());
		milestoneImpl.setStatus(getStatus());

		milestoneImpl.resetOriginalValues();

		return milestoneImpl;
	}

	@Override
	public int compareTo(Milestone milestone) {
		long primaryKey = milestone.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Milestone)) {
			return false;
		}

		Milestone milestone = (Milestone)obj;

		long primaryKey = milestone.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Milestone> toCacheModel() {
		MilestoneCacheModel milestoneCacheModel = new MilestoneCacheModel();

		milestoneCacheModel.milestoneId = getMilestoneId();

		milestoneCacheModel.projectId = getProjectId();

		milestoneCacheModel.clientId = getClientId();

		milestoneCacheModel.milestoneName = getMilestoneName();

		String milestoneName = milestoneCacheModel.milestoneName;

		if ((milestoneName != null) && (milestoneName.length() == 0)) {
			milestoneCacheModel.milestoneName = null;
		}

		Date dueDate = getDueDate();

		if (dueDate != null) {
			milestoneCacheModel.dueDate = dueDate.getTime();
		}
		else {
			milestoneCacheModel.dueDate = Long.MIN_VALUE;
		}

		milestoneCacheModel.checkGST = getCheckGST();

		milestoneCacheModel.amount = getAmount();

		milestoneCacheModel.status = getStatus();

		return milestoneCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{milestoneId=");
		sb.append(getMilestoneId());
		sb.append(", projectId=");
		sb.append(getProjectId());
		sb.append(", clientId=");
		sb.append(getClientId());
		sb.append(", milestoneName=");
		sb.append(getMilestoneName());
		sb.append(", dueDate=");
		sb.append(getDueDate());
		sb.append(", checkGST=");
		sb.append(getCheckGST());
		sb.append(", amount=");
		sb.append(getAmount());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.famocom.erpcloud.model.Milestone");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>milestoneId</column-name><column-value><![CDATA[");
		sb.append(getMilestoneId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectId</column-name><column-value><![CDATA[");
		sb.append(getProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>clientId</column-name><column-value><![CDATA[");
		sb.append(getClientId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>milestoneName</column-name><column-value><![CDATA[");
		sb.append(getMilestoneName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dueDate</column-name><column-value><![CDATA[");
		sb.append(getDueDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>checkGST</column-name><column-value><![CDATA[");
		sb.append(getCheckGST());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>amount</column-name><column-value><![CDATA[");
		sb.append(getAmount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Milestone.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Milestone.class, ModelWrapper.class
		};
	private long _milestoneId;
	private long _projectId;
	private long _clientId;
	private String _milestoneName;
	private Date _dueDate;
	private int _checkGST;
	private double _amount;
	private int _status;
	private Milestone _escapedModel;
}