/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.famocom.erpcloud.model.PerformanceMaster;
import com.liferay.famocom.erpcloud.model.PerformanceMasterModel;
import com.liferay.famocom.erpcloud.model.PerformanceMasterSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PerformanceMaster service. Represents a row in the &quot;performanceMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PerformanceMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PerformanceMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see PerformanceMasterImpl
 * @see PerformanceMaster
 * @see PerformanceMasterModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PerformanceMasterModelImpl extends BaseModelImpl<PerformanceMaster>
	implements PerformanceMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a performance master model instance should use the {@link PerformanceMaster} interface instead.
	 */
	public static final String TABLE_NAME = "performanceMaster";
	public static final Object[][] TABLE_COLUMNS = {
			{ "performanceId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "performanceHeading", Types.VARCHAR },
			{ "performanceDescription", Types.VARCHAR },
			{ "addedDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("performanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("performanceHeading", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("performanceDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table performanceMaster (performanceId LONG not null primary key,companyId LONG,performanceHeading VARCHAR(75) null,performanceDescription VARCHAR(75) null,addedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table performanceMaster";
	public static final String ORDER_BY_JPQL = " ORDER BY performanceMaster.performanceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY performanceMaster.performanceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.famocom.erpcloud.model.PerformanceMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.famocom.erpcloud.model.PerformanceMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PerformanceMaster toModel(PerformanceMasterSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PerformanceMaster model = new PerformanceMasterImpl();

		model.setPerformanceId(soapModel.getPerformanceId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setPerformanceHeading(soapModel.getPerformanceHeading());
		model.setPerformanceDescription(soapModel.getPerformanceDescription());
		model.setAddedDate(soapModel.getAddedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PerformanceMaster> toModels(
		PerformanceMasterSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PerformanceMaster> models = new ArrayList<PerformanceMaster>(soapModels.length);

		for (PerformanceMasterSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.famocom.erpcloud.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.famocom.erpcloud.model.PerformanceMaster"));

	public PerformanceMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _performanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPerformanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _performanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PerformanceMaster.class;
	}

	@Override
	public String getModelClassName() {
		return PerformanceMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("performanceId", getPerformanceId());
		attributes.put("companyId", getCompanyId());
		attributes.put("performanceHeading", getPerformanceHeading());
		attributes.put("performanceDescription", getPerformanceDescription());
		attributes.put("addedDate", getAddedDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long performanceId = (Long)attributes.get("performanceId");

		if (performanceId != null) {
			setPerformanceId(performanceId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String performanceHeading = (String)attributes.get("performanceHeading");

		if (performanceHeading != null) {
			setPerformanceHeading(performanceHeading);
		}

		String performanceDescription = (String)attributes.get(
				"performanceDescription");

		if (performanceDescription != null) {
			setPerformanceDescription(performanceDescription);
		}

		Date addedDate = (Date)attributes.get("addedDate");

		if (addedDate != null) {
			setAddedDate(addedDate);
		}
	}

	@JSON
	@Override
	public long getPerformanceId() {
		return _performanceId;
	}

	@Override
	public void setPerformanceId(long performanceId) {
		_performanceId = performanceId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public String getPerformanceHeading() {
		if (_performanceHeading == null) {
			return "";
		}
		else {
			return _performanceHeading;
		}
	}

	@Override
	public void setPerformanceHeading(String performanceHeading) {
		_performanceHeading = performanceHeading;
	}

	@JSON
	@Override
	public String getPerformanceDescription() {
		if (_performanceDescription == null) {
			return "";
		}
		else {
			return _performanceDescription;
		}
	}

	@Override
	public void setPerformanceDescription(String performanceDescription) {
		_performanceDescription = performanceDescription;
	}

	@JSON
	@Override
	public Date getAddedDate() {
		return _addedDate;
	}

	@Override
	public void setAddedDate(Date addedDate) {
		_addedDate = addedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PerformanceMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PerformanceMaster toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PerformanceMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PerformanceMasterImpl performanceMasterImpl = new PerformanceMasterImpl();

		performanceMasterImpl.setPerformanceId(getPerformanceId());
		performanceMasterImpl.setCompanyId(getCompanyId());
		performanceMasterImpl.setPerformanceHeading(getPerformanceHeading());
		performanceMasterImpl.setPerformanceDescription(getPerformanceDescription());
		performanceMasterImpl.setAddedDate(getAddedDate());

		performanceMasterImpl.resetOriginalValues();

		return performanceMasterImpl;
	}

	@Override
	public int compareTo(PerformanceMaster performanceMaster) {
		long primaryKey = performanceMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PerformanceMaster)) {
			return false;
		}

		PerformanceMaster performanceMaster = (PerformanceMaster)obj;

		long primaryKey = performanceMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PerformanceMaster> toCacheModel() {
		PerformanceMasterCacheModel performanceMasterCacheModel = new PerformanceMasterCacheModel();

		performanceMasterCacheModel.performanceId = getPerformanceId();

		performanceMasterCacheModel.companyId = getCompanyId();

		performanceMasterCacheModel.performanceHeading = getPerformanceHeading();

		String performanceHeading = performanceMasterCacheModel.performanceHeading;

		if ((performanceHeading != null) && (performanceHeading.length() == 0)) {
			performanceMasterCacheModel.performanceHeading = null;
		}

		performanceMasterCacheModel.performanceDescription = getPerformanceDescription();

		String performanceDescription = performanceMasterCacheModel.performanceDescription;

		if ((performanceDescription != null) &&
				(performanceDescription.length() == 0)) {
			performanceMasterCacheModel.performanceDescription = null;
		}

		Date addedDate = getAddedDate();

		if (addedDate != null) {
			performanceMasterCacheModel.addedDate = addedDate.getTime();
		}
		else {
			performanceMasterCacheModel.addedDate = Long.MIN_VALUE;
		}

		return performanceMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{performanceId=");
		sb.append(getPerformanceId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", performanceHeading=");
		sb.append(getPerformanceHeading());
		sb.append(", performanceDescription=");
		sb.append(getPerformanceDescription());
		sb.append(", addedDate=");
		sb.append(getAddedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.famocom.erpcloud.model.PerformanceMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>performanceId</column-name><column-value><![CDATA[");
		sb.append(getPerformanceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>performanceHeading</column-name><column-value><![CDATA[");
		sb.append(getPerformanceHeading());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>performanceDescription</column-name><column-value><![CDATA[");
		sb.append(getPerformanceDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>addedDate</column-name><column-value><![CDATA[");
		sb.append(getAddedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = PerformanceMaster.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			PerformanceMaster.class, ModelWrapper.class
		};
	private long _performanceId;
	private long _companyId;
	private String _performanceHeading;
	private String _performanceDescription;
	private Date _addedDate;
	private PerformanceMaster _escapedModel;
}