/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppraisalGoalMaster service. Represents a row in the &quot;appraisalGoalMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.AppraisalGoalMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.AppraisalGoalMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AppraisalGoalMaster
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalGoalMasterImpl
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalGoalMasterModelImpl
 * @generated
 */
@ProviderType
public interface AppraisalGoalMasterModel extends BaseModel<AppraisalGoalMaster>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appraisal goal master model instance should use the {@link AppraisalGoalMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this appraisal goal master.
	 *
	 * @return the primary key of this appraisal goal master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appraisal goal master.
	 *
	 * @param primaryKey the primary key of this appraisal goal master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the appraisal goal master ID of this appraisal goal master.
	 *
	 * @return the appraisal goal master ID of this appraisal goal master
	 */
	public long getAppraisalGoalMasterId();

	/**
	 * Sets the appraisal goal master ID of this appraisal goal master.
	 *
	 * @param appraisalGoalMasterId the appraisal goal master ID of this appraisal goal master
	 */
	public void setAppraisalGoalMasterId(long appraisalGoalMasterId);

	/**
	 * Returns the company ID of this appraisal goal master.
	 *
	 * @return the company ID of this appraisal goal master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appraisal goal master.
	 *
	 * @param companyId the company ID of this appraisal goal master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the appraisal ID of this appraisal goal master.
	 *
	 * @return the appraisal ID of this appraisal goal master
	 */
	public long getAppraisalId();

	/**
	 * Sets the appraisal ID of this appraisal goal master.
	 *
	 * @param appraisalId the appraisal ID of this appraisal goal master
	 */
	public void setAppraisalId(long appraisalId);

	/**
	 * Returns the appraisal project ID of this appraisal goal master.
	 *
	 * @return the appraisal project ID of this appraisal goal master
	 */
	public long getAppraisalProjectId();

	/**
	 * Sets the appraisal project ID of this appraisal goal master.
	 *
	 * @param appraisalProjectId the appraisal project ID of this appraisal goal master
	 */
	public void setAppraisalProjectId(long appraisalProjectId);

	/**
	 * Returns the employee ID of this appraisal goal master.
	 *
	 * @return the employee ID of this appraisal goal master
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this appraisal goal master.
	 *
	 * @param employeeId the employee ID of this appraisal goal master
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the project ID of this appraisal goal master.
	 *
	 * @return the project ID of this appraisal goal master
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this appraisal goal master.
	 *
	 * @param projectId the project ID of this appraisal goal master
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the evaluation ID of this appraisal goal master.
	 *
	 * @return the evaluation ID of this appraisal goal master
	 */
	public long getEvaluationId();

	/**
	 * Sets the evaluation ID of this appraisal goal master.
	 *
	 * @param evaluationId the evaluation ID of this appraisal goal master
	 */
	public void setEvaluationId(long evaluationId);

	/**
	 * Returns the employee comment of this appraisal goal master.
	 *
	 * @return the employee comment of this appraisal goal master
	 */
	@AutoEscape
	public String getEmployeeComment();

	/**
	 * Sets the employee comment of this appraisal goal master.
	 *
	 * @param employeeComment the employee comment of this appraisal goal master
	 */
	public void setEmployeeComment(String employeeComment);

	/**
	 * Returns the employee overall rat of this appraisal goal master.
	 *
	 * @return the employee overall rat of this appraisal goal master
	 */
	public long getEmployeeOverallRat();

	/**
	 * Sets the employee overall rat of this appraisal goal master.
	 *
	 * @param employeeOverallRat the employee overall rat of this appraisal goal master
	 */
	public void setEmployeeOverallRat(long employeeOverallRat);

	/**
	 * Returns the manager comment of this appraisal goal master.
	 *
	 * @return the manager comment of this appraisal goal master
	 */
	@AutoEscape
	public String getManagerComment();

	/**
	 * Sets the manager comment of this appraisal goal master.
	 *
	 * @param managerComment the manager comment of this appraisal goal master
	 */
	public void setManagerComment(String managerComment);

	/**
	 * Returns the manager overall rat of this appraisal goal master.
	 *
	 * @return the manager overall rat of this appraisal goal master
	 */
	public long getManagerOverallRat();

	/**
	 * Sets the manager overall rat of this appraisal goal master.
	 *
	 * @param managerOverallRat the manager overall rat of this appraisal goal master
	 */
	public void setManagerOverallRat(long managerOverallRat);

	/**
	 * Returns the created date of this appraisal goal master.
	 *
	 * @return the created date of this appraisal goal master
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this appraisal goal master.
	 *
	 * @param createdDate the created date of this appraisal goal master
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this appraisal goal master.
	 *
	 * @return the created by of this appraisal goal master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this appraisal goal master.
	 *
	 * @param createdBy the created by of this appraisal goal master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this appraisal goal master.
	 *
	 * @return the modified date of this appraisal goal master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appraisal goal master.
	 *
	 * @param modifiedDate the modified date of this appraisal goal master
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this appraisal goal master.
	 *
	 * @return the modified by of this appraisal goal master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this appraisal goal master.
	 *
	 * @param modifiedBy the modified by of this appraisal goal master
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AppraisalGoalMaster appraisalGoalMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AppraisalGoalMaster> toCacheModel();

	@Override
	public AppraisalGoalMaster toEscapedModel();

	@Override
	public AppraisalGoalMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}