/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppraisalProjectMaster service. Represents a row in the &quot;appraisalProjectMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.AppraisalProjectMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.AppraisalProjectMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AppraisalProjectMaster
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalProjectMasterImpl
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalProjectMasterModelImpl
 * @generated
 */
@ProviderType
public interface AppraisalProjectMasterModel extends BaseModel<AppraisalProjectMaster>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appraisal project master model instance should use the {@link AppraisalProjectMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this appraisal project master.
	 *
	 * @return the primary key of this appraisal project master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appraisal project master.
	 *
	 * @param primaryKey the primary key of this appraisal project master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the appraisal project ID of this appraisal project master.
	 *
	 * @return the appraisal project ID of this appraisal project master
	 */
	public long getAppraisalProjectId();

	/**
	 * Sets the appraisal project ID of this appraisal project master.
	 *
	 * @param appraisalProjectId the appraisal project ID of this appraisal project master
	 */
	public void setAppraisalProjectId(long appraisalProjectId);

	/**
	 * Returns the company ID of this appraisal project master.
	 *
	 * @return the company ID of this appraisal project master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appraisal project master.
	 *
	 * @param companyId the company ID of this appraisal project master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the appraisal ID of this appraisal project master.
	 *
	 * @return the appraisal ID of this appraisal project master
	 */
	public long getAppraisalId();

	/**
	 * Sets the appraisal ID of this appraisal project master.
	 *
	 * @param appraisalId the appraisal ID of this appraisal project master
	 */
	public void setAppraisalId(long appraisalId);

	/**
	 * Returns the appraisal setting ID of this appraisal project master.
	 *
	 * @return the appraisal setting ID of this appraisal project master
	 */
	public long getAppraisalSettingId();

	/**
	 * Sets the appraisal setting ID of this appraisal project master.
	 *
	 * @param appraisalSettingId the appraisal setting ID of this appraisal project master
	 */
	public void setAppraisalSettingId(long appraisalSettingId);

	/**
	 * Returns the employee ID of this appraisal project master.
	 *
	 * @return the employee ID of this appraisal project master
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this appraisal project master.
	 *
	 * @param employeeId the employee ID of this appraisal project master
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the project ID of this appraisal project master.
	 *
	 * @return the project ID of this appraisal project master
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this appraisal project master.
	 *
	 * @param projectId the project ID of this appraisal project master
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the project description of this appraisal project master.
	 *
	 * @return the project description of this appraisal project master
	 */
	@AutoEscape
	public String getProjectDescription();

	/**
	 * Sets the project description of this appraisal project master.
	 *
	 * @param projectDescription the project description of this appraisal project master
	 */
	public void setProjectDescription(String projectDescription);

	/**
	 * Returns the start date of this appraisal project master.
	 *
	 * @return the start date of this appraisal project master
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this appraisal project master.
	 *
	 * @param startDate the start date of this appraisal project master
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this appraisal project master.
	 *
	 * @return the end date of this appraisal project master
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this appraisal project master.
	 *
	 * @param endDate the end date of this appraisal project master
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the submit step of this appraisal project master.
	 *
	 * @return the submit step of this appraisal project master
	 */
	public long getSubmitStep();

	/**
	 * Sets the submit step of this appraisal project master.
	 *
	 * @param submitStep the submit step of this appraisal project master
	 */
	public void setSubmitStep(long submitStep);

	/**
	 * Returns the added date of this appraisal project master.
	 *
	 * @return the added date of this appraisal project master
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this appraisal project master.
	 *
	 * @param addedDate the added date of this appraisal project master
	 */
	public void setAddedDate(Date addedDate);

	/**
	 * Returns the created by of this appraisal project master.
	 *
	 * @return the created by of this appraisal project master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this appraisal project master.
	 *
	 * @param createdBy the created by of this appraisal project master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this appraisal project master.
	 *
	 * @return the modified date of this appraisal project master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appraisal project master.
	 *
	 * @param modifiedDate the modified date of this appraisal project master
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this appraisal project master.
	 *
	 * @return the modified by of this appraisal project master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this appraisal project master.
	 *
	 * @param modifiedBy the modified by of this appraisal project master
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AppraisalProjectMaster appraisalProjectMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AppraisalProjectMaster> toCacheModel();

	@Override
	public AppraisalProjectMaster toEscapedModel();

	@Override
	public AppraisalProjectMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}