/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppraisalSetup service. Represents a row in the &quot;appraisalSetup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.AppraisalSetupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.AppraisalSetupImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AppraisalSetup
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalSetupImpl
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalSetupModelImpl
 * @generated
 */
@ProviderType
public interface AppraisalSetupModel extends BaseModel<AppraisalSetup>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appraisal setup model instance should use the {@link AppraisalSetup} interface instead.
	 */

	/**
	 * Returns the primary key of this appraisal setup.
	 *
	 * @return the primary key of this appraisal setup
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appraisal setup.
	 *
	 * @param primaryKey the primary key of this appraisal setup
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the appraisal setting ID of this appraisal setup.
	 *
	 * @return the appraisal setting ID of this appraisal setup
	 */
	public long getAppraisalSettingId();

	/**
	 * Sets the appraisal setting ID of this appraisal setup.
	 *
	 * @param appraisalSettingId the appraisal setting ID of this appraisal setup
	 */
	public void setAppraisalSettingId(long appraisalSettingId);

	/**
	 * Returns the company ID of this appraisal setup.
	 *
	 * @return the company ID of this appraisal setup
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appraisal setup.
	 *
	 * @param companyId the company ID of this appraisal setup
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the financial year of this appraisal setup.
	 *
	 * @return the financial year of this appraisal setup
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this appraisal setup.
	 *
	 * @param financialYear the financial year of this appraisal setup
	 */
	public void setFinancialYear(String financialYear);

	/**
	 * Returns the from date cycle of this appraisal setup.
	 *
	 * @return the from date cycle of this appraisal setup
	 */
	public Date getFromDateCycle();

	/**
	 * Sets the from date cycle of this appraisal setup.
	 *
	 * @param fromDateCycle the from date cycle of this appraisal setup
	 */
	public void setFromDateCycle(Date fromDateCycle);

	/**
	 * Returns the to date cycle of this appraisal setup.
	 *
	 * @return the to date cycle of this appraisal setup
	 */
	public Date getToDateCycle();

	/**
	 * Sets the to date cycle of this appraisal setup.
	 *
	 * @param toDateCycle the to date cycle of this appraisal setup
	 */
	public void setToDateCycle(Date toDateCycle);

	/**
	 * Returns the from date submission of this appraisal setup.
	 *
	 * @return the from date submission of this appraisal setup
	 */
	public Date getFromDateSubmission();

	/**
	 * Sets the from date submission of this appraisal setup.
	 *
	 * @param fromDateSubmission the from date submission of this appraisal setup
	 */
	public void setFromDateSubmission(Date fromDateSubmission);

	/**
	 * Returns the to date submission of this appraisal setup.
	 *
	 * @return the to date submission of this appraisal setup
	 */
	public Date getToDateSubmission();

	/**
	 * Sets the to date submission of this appraisal setup.
	 *
	 * @param toDateSubmission the to date submission of this appraisal setup
	 */
	public void setToDateSubmission(Date toDateSubmission);

	/**
	 * Returns the appraisal period of this appraisal setup.
	 *
	 * @return the appraisal period of this appraisal setup
	 */
	public long getAppraisalPeriod();

	/**
	 * Sets the appraisal period of this appraisal setup.
	 *
	 * @param appraisalPeriod the appraisal period of this appraisal setup
	 */
	public void setAppraisalPeriod(long appraisalPeriod);

	/**
	 * Returns the total emp of this appraisal setup.
	 *
	 * @return the total emp of this appraisal setup
	 */
	public long getTotalEmp();

	/**
	 * Sets the total emp of this appraisal setup.
	 *
	 * @param totalEmp the total emp of this appraisal setup
	 */
	public void setTotalEmp(long totalEmp);

	/**
	 * Returns the before ctc all of this appraisal setup.
	 *
	 * @return the before ctc all of this appraisal setup
	 */
	public long getBeforeCtcAll();

	/**
	 * Sets the before ctc all of this appraisal setup.
	 *
	 * @param beforeCtcAll the before ctc all of this appraisal setup
	 */
	public void setBeforeCtcAll(long beforeCtcAll);

	/**
	 * Returns the appraisal emp of this appraisal setup.
	 *
	 * @return the appraisal emp of this appraisal setup
	 */
	public long getAppraisalEmp();

	/**
	 * Sets the appraisal emp of this appraisal setup.
	 *
	 * @param appraisalEmp the appraisal emp of this appraisal setup
	 */
	public void setAppraisalEmp(long appraisalEmp);

	/**
	 * Returns the before ctc of this appraisal setup.
	 *
	 * @return the before ctc of this appraisal setup
	 */
	public long getBeforeCtc();

	/**
	 * Sets the before ctc of this appraisal setup.
	 *
	 * @param beforeCtc the before ctc of this appraisal setup
	 */
	public void setBeforeCtc(long beforeCtc);

	/**
	 * Returns the after ctc of this appraisal setup.
	 *
	 * @return the after ctc of this appraisal setup
	 */
	public long getAfterCtc();

	/**
	 * Sets the after ctc of this appraisal setup.
	 *
	 * @param afterCtc the after ctc of this appraisal setup
	 */
	public void setAfterCtc(long afterCtc);

	/**
	 * Returns the total areas of this appraisal setup.
	 *
	 * @return the total areas of this appraisal setup
	 */
	public long getTotalAreas();

	/**
	 * Sets the total areas of this appraisal setup.
	 *
	 * @param totalAreas the total areas of this appraisal setup
	 */
	public void setTotalAreas(long totalAreas);

	/**
	 * Returns the total bonus of this appraisal setup.
	 *
	 * @return the total bonus of this appraisal setup
	 */
	public long getTotalBonus();

	/**
	 * Sets the total bonus of this appraisal setup.
	 *
	 * @param totalBonus the total bonus of this appraisal setup
	 */
	public void setTotalBonus(long totalBonus);

	/**
	 * Returns the total ctc after of this appraisal setup.
	 *
	 * @return the total ctc after of this appraisal setup
	 */
	public long getTotalCtcAfter();

	/**
	 * Sets the total ctc after of this appraisal setup.
	 *
	 * @param totalCtcAfter the total ctc after of this appraisal setup
	 */
	public void setTotalCtcAfter(long totalCtcAfter);

	/**
	 * Returns the is locked of this appraisal setup.
	 *
	 * @return the is locked of this appraisal setup
	 */
	public long getIsLocked();

	/**
	 * Sets the is locked of this appraisal setup.
	 *
	 * @param isLocked the is locked of this appraisal setup
	 */
	public void setIsLocked(long isLocked);

	/**
	 * Returns the is active of this appraisal setup.
	 *
	 * @return the is active of this appraisal setup
	 */
	public long getIsActive();

	/**
	 * Sets the is active of this appraisal setup.
	 *
	 * @param isActive the is active of this appraisal setup
	 */
	public void setIsActive(long isActive);

	/**
	 * Returns the employee type of this appraisal setup.
	 *
	 * @return the employee type of this appraisal setup
	 */
	@AutoEscape
	public String getEmployeeType();

	/**
	 * Sets the employee type of this appraisal setup.
	 *
	 * @param employeeType the employee type of this appraisal setup
	 */
	public void setEmployeeType(String employeeType);

	/**
	 * Returns the added date of this appraisal setup.
	 *
	 * @return the added date of this appraisal setup
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this appraisal setup.
	 *
	 * @param addedDate the added date of this appraisal setup
	 */
	public void setAddedDate(Date addedDate);

	/**
	 * Returns the created by of this appraisal setup.
	 *
	 * @return the created by of this appraisal setup
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this appraisal setup.
	 *
	 * @param createdBy the created by of this appraisal setup
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this appraisal setup.
	 *
	 * @return the modified date of this appraisal setup
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appraisal setup.
	 *
	 * @param modifiedDate the modified date of this appraisal setup
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this appraisal setup.
	 *
	 * @return the modified by of this appraisal setup
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this appraisal setup.
	 *
	 * @param modifiedBy the modified by of this appraisal setup
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AppraisalSetup appraisalSetup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AppraisalSetup> toCacheModel();

	@Override
	public AppraisalSetup toEscapedModel();

	@Override
	public AppraisalSetup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}