/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppraisalGoalDetails service. Represents a row in the &quot;appraisalGoalDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.AppraisalGoalDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.AppraisalGoalDetailsImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AppraisalGoalDetails
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalGoalDetailsImpl
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalGoalDetailsModelImpl
 * @generated
 */
@ProviderType
public interface AppraisalGoalDetailsModel extends BaseModel<AppraisalGoalDetails>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appraisal goal details model instance should use the {@link AppraisalGoalDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this appraisal goal details.
	 *
	 * @return the primary key of this appraisal goal details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appraisal goal details.
	 *
	 * @param primaryKey the primary key of this appraisal goal details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the appraisal goal details ID of this appraisal goal details.
	 *
	 * @return the appraisal goal details ID of this appraisal goal details
	 */
	public long getAppraisalGoalDetailsId();

	/**
	 * Sets the appraisal goal details ID of this appraisal goal details.
	 *
	 * @param appraisalGoalDetailsId the appraisal goal details ID of this appraisal goal details
	 */
	public void setAppraisalGoalDetailsId(long appraisalGoalDetailsId);

	/**
	 * Returns the appraisal goal master ID of this appraisal goal details.
	 *
	 * @return the appraisal goal master ID of this appraisal goal details
	 */
	public long getAppraisalGoalMasterId();

	/**
	 * Sets the appraisal goal master ID of this appraisal goal details.
	 *
	 * @param appraisalGoalMasterId the appraisal goal master ID of this appraisal goal details
	 */
	public void setAppraisalGoalMasterId(long appraisalGoalMasterId);

	/**
	 * Returns the company ID of this appraisal goal details.
	 *
	 * @return the company ID of this appraisal goal details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appraisal goal details.
	 *
	 * @param companyId the company ID of this appraisal goal details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the appraisal ID of this appraisal goal details.
	 *
	 * @return the appraisal ID of this appraisal goal details
	 */
	public long getAppraisalId();

	/**
	 * Sets the appraisal ID of this appraisal goal details.
	 *
	 * @param appraisalId the appraisal ID of this appraisal goal details
	 */
	public void setAppraisalId(long appraisalId);

	/**
	 * Returns the employee ID of this appraisal goal details.
	 *
	 * @return the employee ID of this appraisal goal details
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this appraisal goal details.
	 *
	 * @param employeeId the employee ID of this appraisal goal details
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the project ID of this appraisal goal details.
	 *
	 * @return the project ID of this appraisal goal details
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this appraisal goal details.
	 *
	 * @param projectId the project ID of this appraisal goal details
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the evaluation ID of this appraisal goal details.
	 *
	 * @return the evaluation ID of this appraisal goal details
	 */
	public long getEvaluationId();

	/**
	 * Sets the evaluation ID of this appraisal goal details.
	 *
	 * @param evaluationId the evaluation ID of this appraisal goal details
	 */
	public void setEvaluationId(long evaluationId);

	/**
	 * Returns the goaldetail ID of this appraisal goal details.
	 *
	 * @return the goaldetail ID of this appraisal goal details
	 */
	public long getGoaldetailId();

	/**
	 * Sets the goaldetail ID of this appraisal goal details.
	 *
	 * @param goaldetailId the goaldetail ID of this appraisal goal details
	 */
	public void setGoaldetailId(long goaldetailId);

	/**
	 * Returns the rating ID emp of this appraisal goal details.
	 *
	 * @return the rating ID emp of this appraisal goal details
	 */
	public long getRatingIdEmp();

	/**
	 * Sets the rating ID emp of this appraisal goal details.
	 *
	 * @param ratingIdEmp the rating ID emp of this appraisal goal details
	 */
	public void setRatingIdEmp(long ratingIdEmp);

	/**
	 * Returns the rating ID man of this appraisal goal details.
	 *
	 * @return the rating ID man of this appraisal goal details
	 */
	public long getRatingIdMan();

	/**
	 * Sets the rating ID man of this appraisal goal details.
	 *
	 * @param ratingIdMan the rating ID man of this appraisal goal details
	 */
	public void setRatingIdMan(long ratingIdMan);

	/**
	 * Returns the created date of this appraisal goal details.
	 *
	 * @return the created date of this appraisal goal details
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this appraisal goal details.
	 *
	 * @param createdDate the created date of this appraisal goal details
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this appraisal goal details.
	 *
	 * @return the created by of this appraisal goal details
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this appraisal goal details.
	 *
	 * @param createdBy the created by of this appraisal goal details
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this appraisal goal details.
	 *
	 * @return the modified date of this appraisal goal details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appraisal goal details.
	 *
	 * @param modifiedDate the modified date of this appraisal goal details
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this appraisal goal details.
	 *
	 * @return the modified by of this appraisal goal details
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this appraisal goal details.
	 *
	 * @param modifiedBy the modified by of this appraisal goal details
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AppraisalGoalDetails appraisalGoalDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AppraisalGoalDetails> toCacheModel();

	@Override
	public AppraisalGoalDetails toEscapedModel();

	@Override
	public AppraisalGoalDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}