/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppraisalMaster service. Represents a row in the &quot;appraisalMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.AppraisalMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.AppraisalMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AppraisalMaster
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalMasterImpl
 * @see com.liferay.famocom.erpcloud.model.impl.AppraisalMasterModelImpl
 * @generated
 */
@ProviderType
public interface AppraisalMasterModel extends BaseModel<AppraisalMaster>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appraisal master model instance should use the {@link AppraisalMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this appraisal master.
	 *
	 * @return the primary key of this appraisal master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appraisal master.
	 *
	 * @param primaryKey the primary key of this appraisal master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the appraisal ID of this appraisal master.
	 *
	 * @return the appraisal ID of this appraisal master
	 */
	public long getAppraisalId();

	/**
	 * Sets the appraisal ID of this appraisal master.
	 *
	 * @param appraisalId the appraisal ID of this appraisal master
	 */
	public void setAppraisalId(long appraisalId);

	/**
	 * Returns the company ID of this appraisal master.
	 *
	 * @return the company ID of this appraisal master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appraisal master.
	 *
	 * @param companyId the company ID of this appraisal master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the appraisal setting ID of this appraisal master.
	 *
	 * @return the appraisal setting ID of this appraisal master
	 */
	public long getAppraisalSettingId();

	/**
	 * Sets the appraisal setting ID of this appraisal master.
	 *
	 * @param appraisalSettingId the appraisal setting ID of this appraisal master
	 */
	public void setAppraisalSettingId(long appraisalSettingId);

	/**
	 * Returns the employee ID of this appraisal master.
	 *
	 * @return the employee ID of this appraisal master
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this appraisal master.
	 *
	 * @param employeeId the employee ID of this appraisal master
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the accomplishments emp of this appraisal master.
	 *
	 * @return the accomplishments emp of this appraisal master
	 */
	@AutoEscape
	public String getAccomplishmentsEmp();

	/**
	 * Sets the accomplishments emp of this appraisal master.
	 *
	 * @param accomplishmentsEmp the accomplishments emp of this appraisal master
	 */
	public void setAccomplishmentsEmp(String accomplishmentsEmp);

	/**
	 * Returns the strengths emp of this appraisal master.
	 *
	 * @return the strengths emp of this appraisal master
	 */
	@AutoEscape
	public String getStrengthsEmp();

	/**
	 * Sets the strengths emp of this appraisal master.
	 *
	 * @param strengthsEmp the strengths emp of this appraisal master
	 */
	public void setStrengthsEmp(String strengthsEmp);

	/**
	 * Returns the development emp of this appraisal master.
	 *
	 * @return the development emp of this appraisal master
	 */
	@AutoEscape
	public String getDevelopmentEmp();

	/**
	 * Sets the development emp of this appraisal master.
	 *
	 * @param developmentEmp the development emp of this appraisal master
	 */
	public void setDevelopmentEmp(String developmentEmp);

	/**
	 * Returns the career emp of this appraisal master.
	 *
	 * @return the career emp of this appraisal master
	 */
	@AutoEscape
	public String getCareerEmp();

	/**
	 * Sets the career emp of this appraisal master.
	 *
	 * @param careerEmp the career emp of this appraisal master
	 */
	public void setCareerEmp(String careerEmp);

	/**
	 * Returns the overall rating emp of this appraisal master.
	 *
	 * @return the overall rating emp of this appraisal master
	 */
	public long getOverallRatingEmp();

	/**
	 * Sets the overall rating emp of this appraisal master.
	 *
	 * @param overallRatingEmp the overall rating emp of this appraisal master
	 */
	public void setOverallRatingEmp(long overallRatingEmp);

	/**
	 * Returns the overall comment emp of this appraisal master.
	 *
	 * @return the overall comment emp of this appraisal master
	 */
	@AutoEscape
	public String getOverallCommentEmp();

	/**
	 * Sets the overall comment emp of this appraisal master.
	 *
	 * @param overallCommentEmp the overall comment emp of this appraisal master
	 */
	public void setOverallCommentEmp(String overallCommentEmp);

	/**
	 * Returns the accomplishments man of this appraisal master.
	 *
	 * @return the accomplishments man of this appraisal master
	 */
	@AutoEscape
	public String getAccomplishmentsMan();

	/**
	 * Sets the accomplishments man of this appraisal master.
	 *
	 * @param accomplishmentsMan the accomplishments man of this appraisal master
	 */
	public void setAccomplishmentsMan(String accomplishmentsMan);

	/**
	 * Returns the strengths man of this appraisal master.
	 *
	 * @return the strengths man of this appraisal master
	 */
	@AutoEscape
	public String getStrengthsMan();

	/**
	 * Sets the strengths man of this appraisal master.
	 *
	 * @param strengthsMan the strengths man of this appraisal master
	 */
	public void setStrengthsMan(String strengthsMan);

	/**
	 * Returns the development man of this appraisal master.
	 *
	 * @return the development man of this appraisal master
	 */
	@AutoEscape
	public String getDevelopmentMan();

	/**
	 * Sets the development man of this appraisal master.
	 *
	 * @param developmentMan the development man of this appraisal master
	 */
	public void setDevelopmentMan(String developmentMan);

	/**
	 * Returns the career man of this appraisal master.
	 *
	 * @return the career man of this appraisal master
	 */
	@AutoEscape
	public String getCareerMan();

	/**
	 * Sets the career man of this appraisal master.
	 *
	 * @param careerMan the career man of this appraisal master
	 */
	public void setCareerMan(String careerMan);

	/**
	 * Returns the company value of this appraisal master.
	 *
	 * @return the company value of this appraisal master
	 */
	@AutoEscape
	public String getCompanyValue();

	/**
	 * Sets the company value of this appraisal master.
	 *
	 * @param companyValue the company value of this appraisal master
	 */
	public void setCompanyValue(String companyValue);

	/**
	 * Returns the development plan of this appraisal master.
	 *
	 * @return the development plan of this appraisal master
	 */
	@AutoEscape
	public String getDevelopmentPlan();

	/**
	 * Sets the development plan of this appraisal master.
	 *
	 * @param developmentPlan the development plan of this appraisal master
	 */
	public void setDevelopmentPlan(String developmentPlan);

	/**
	 * Returns the overall rating man of this appraisal master.
	 *
	 * @return the overall rating man of this appraisal master
	 */
	public long getOverallRatingMan();

	/**
	 * Sets the overall rating man of this appraisal master.
	 *
	 * @param overallRatingMan the overall rating man of this appraisal master
	 */
	public void setOverallRatingMan(long overallRatingMan);

	/**
	 * Returns the overall comment man of this appraisal master.
	 *
	 * @return the overall comment man of this appraisal master
	 */
	@AutoEscape
	public String getOverallCommentMan();

	/**
	 * Sets the overall comment man of this appraisal master.
	 *
	 * @param overallCommentMan the overall comment man of this appraisal master
	 */
	public void setOverallCommentMan(String overallCommentMan);

	/**
	 * Returns the submit step of this appraisal master.
	 *
	 * @return the submit step of this appraisal master
	 */
	public long getSubmitStep();

	/**
	 * Sets the submit step of this appraisal master.
	 *
	 * @param submitStep the submit step of this appraisal master
	 */
	public void setSubmitStep(long submitStep);

	/**
	 * Returns the added date of this appraisal master.
	 *
	 * @return the added date of this appraisal master
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this appraisal master.
	 *
	 * @param addedDate the added date of this appraisal master
	 */
	public void setAddedDate(Date addedDate);

	/**
	 * Returns the created by of this appraisal master.
	 *
	 * @return the created by of this appraisal master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this appraisal master.
	 *
	 * @param createdBy the created by of this appraisal master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this appraisal master.
	 *
	 * @return the modified date of this appraisal master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appraisal master.
	 *
	 * @param modifiedDate the modified date of this appraisal master
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this appraisal master.
	 *
	 * @return the modified by of this appraisal master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this appraisal master.
	 *
	 * @param modifiedBy the modified by of this appraisal master
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AppraisalMaster appraisalMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AppraisalMaster> toCacheModel();

	@Override
	public AppraisalMaster toEscapedModel();

	@Override
	public AppraisalMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}