/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Attendance service. Represents a row in the &quot;attendance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.AttendanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.AttendanceImpl}.
 * </p>
 *
 * @author Samaresh
 * @see Attendance
 * @see com.liferay.famocom.erpcloud.model.impl.AttendanceImpl
 * @see com.liferay.famocom.erpcloud.model.impl.AttendanceModelImpl
 * @generated
 */
@ProviderType
public interface AttendanceModel extends BaseModel<Attendance>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attendance model instance should use the {@link Attendance} interface instead.
	 */

	/**
	 * Returns the primary key of this attendance.
	 *
	 * @return the primary key of this attendance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this attendance.
	 *
	 * @param primaryKey the primary key of this attendance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the attendance ID of this attendance.
	 *
	 * @return the attendance ID of this attendance
	 */
	public long getAttendanceId();

	/**
	 * Sets the attendance ID of this attendance.
	 *
	 * @param attendanceId the attendance ID of this attendance
	 */
	public void setAttendanceId(long attendanceId);

	/**
	 * Returns the company ID of this attendance.
	 *
	 * @return the company ID of this attendance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this attendance.
	 *
	 * @param companyId the company ID of this attendance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee code of this attendance.
	 *
	 * @return the employee code of this attendance
	 */
	public long getEmployeeCode();

	/**
	 * Sets the employee code of this attendance.
	 *
	 * @param employeeCode the employee code of this attendance
	 */
	public void setEmployeeCode(long employeeCode);

	/**
	 * Returns the employee ID of this attendance.
	 *
	 * @return the employee ID of this attendance
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this attendance.
	 *
	 * @param employeeId the employee ID of this attendance
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the att date of this attendance.
	 *
	 * @return the att date of this attendance
	 */
	public Date getAttDate();

	/**
	 * Sets the att date of this attendance.
	 *
	 * @param attDate the att date of this attendance
	 */
	public void setAttDate(Date attDate);

	/**
	 * Returns the in time hour of this attendance.
	 *
	 * @return the in time hour of this attendance
	 */
	@AutoEscape
	public String getInTimeHour();

	/**
	 * Sets the in time hour of this attendance.
	 *
	 * @param inTimeHour the in time hour of this attendance
	 */
	public void setInTimeHour(String inTimeHour);

	/**
	 * Returns the in time min of this attendance.
	 *
	 * @return the in time min of this attendance
	 */
	@AutoEscape
	public String getInTimeMin();

	/**
	 * Sets the in time min of this attendance.
	 *
	 * @param inTimeMin the in time min of this attendance
	 */
	public void setInTimeMin(String inTimeMin);

	/**
	 * Returns the out time hour of this attendance.
	 *
	 * @return the out time hour of this attendance
	 */
	@AutoEscape
	public String getOutTimeHour();

	/**
	 * Sets the out time hour of this attendance.
	 *
	 * @param outTimeHour the out time hour of this attendance
	 */
	public void setOutTimeHour(String outTimeHour);

	/**
	 * Returns the out time min of this attendance.
	 *
	 * @return the out time min of this attendance
	 */
	@AutoEscape
	public String getOutTimeMin();

	/**
	 * Sets the out time min of this attendance.
	 *
	 * @param outTimeMin the out time min of this attendance
	 */
	public void setOutTimeMin(String outTimeMin);

	/**
	 * Returns the in time of this attendance.
	 *
	 * @return the in time of this attendance
	 */
	@AutoEscape
	public String getInTime();

	/**
	 * Sets the in time of this attendance.
	 *
	 * @param inTime the in time of this attendance
	 */
	public void setInTime(String inTime);

	/**
	 * Returns the out time of this attendance.
	 *
	 * @return the out time of this attendance
	 */
	@AutoEscape
	public String getOutTime();

	/**
	 * Sets the out time of this attendance.
	 *
	 * @param outTime the out time of this attendance
	 */
	public void setOutTime(String outTime);

	/**
	 * Returns the in date pc of this attendance.
	 *
	 * @return the in date pc of this attendance
	 */
	public Date getInDatePc();

	/**
	 * Sets the in date pc of this attendance.
	 *
	 * @param inDatePc the in date pc of this attendance
	 */
	public void setInDatePc(Date inDatePc);

	/**
	 * Returns the out date pc of this attendance.
	 *
	 * @return the out date pc of this attendance
	 */
	public Date getOutDatePc();

	/**
	 * Sets the out date pc of this attendance.
	 *
	 * @param outDatePc the out date pc of this attendance
	 */
	public void setOutDatePc(Date outDatePc);

	/**
	 * Returns the total of this attendance.
	 *
	 * @return the total of this attendance
	 */
	@AutoEscape
	public String getTotal();

	/**
	 * Sets the total of this attendance.
	 *
	 * @param total the total of this attendance
	 */
	public void setTotal(String total);

	/**
	 * Returns the status of this attendance.
	 *
	 * @return the status of this attendance
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this attendance.
	 *
	 * @param status the status of this attendance
	 */
	public void setStatus(String status);

	/**
	 * Returns the ip pc of this attendance.
	 *
	 * @return the ip pc of this attendance
	 */
	@AutoEscape
	public String getIpPc();

	/**
	 * Sets the ip pc of this attendance.
	 *
	 * @param ipPc the ip pc of this attendance
	 */
	public void setIpPc(String ipPc);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Attendance attendance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Attendance> toCacheModel();

	@Override
	public Attendance toEscapedModel();

	@Override
	public Attendance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}