/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AttendanceBio service. Represents a row in the &quot;attendanceBio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.AttendanceBioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.AttendanceBioImpl}.
 * </p>
 *
 * @author Samaresh
 * @see AttendanceBio
 * @see com.liferay.famocom.erpcloud.model.impl.AttendanceBioImpl
 * @see com.liferay.famocom.erpcloud.model.impl.AttendanceBioModelImpl
 * @generated
 */
@ProviderType
public interface AttendanceBioModel extends BaseModel<AttendanceBio>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attendance bio model instance should use the {@link AttendanceBio} interface instead.
	 */

	/**
	 * Returns the primary key of this attendance bio.
	 *
	 * @return the primary key of this attendance bio
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this attendance bio.
	 *
	 * @param primaryKey the primary key of this attendance bio
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the attendance bio ID of this attendance bio.
	 *
	 * @return the attendance bio ID of this attendance bio
	 */
	public long getAttendanceBioId();

	/**
	 * Sets the attendance bio ID of this attendance bio.
	 *
	 * @param attendanceBioId the attendance bio ID of this attendance bio
	 */
	public void setAttendanceBioId(long attendanceBioId);

	/**
	 * Returns the company ID of this attendance bio.
	 *
	 * @return the company ID of this attendance bio
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this attendance bio.
	 *
	 * @param companyId the company ID of this attendance bio
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee ID of this attendance bio.
	 *
	 * @return the employee ID of this attendance bio
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this attendance bio.
	 *
	 * @param employeeId the employee ID of this attendance bio
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the att date of this attendance bio.
	 *
	 * @return the att date of this attendance bio
	 */
	public Date getAttDate();

	/**
	 * Sets the att date of this attendance bio.
	 *
	 * @param attDate the att date of this attendance bio
	 */
	public void setAttDate(Date attDate);

	/**
	 * Returns the att time of this attendance bio.
	 *
	 * @return the att time of this attendance bio
	 */
	@AutoEscape
	public String getAttTime();

	/**
	 * Sets the att time of this attendance bio.
	 *
	 * @param attTime the att time of this attendance bio
	 */
	public void setAttTime(String attTime);

	/**
	 * Returns the upload date of this attendance bio.
	 *
	 * @return the upload date of this attendance bio
	 */
	public Date getUploadDate();

	/**
	 * Sets the upload date of this attendance bio.
	 *
	 * @param uploadDate the upload date of this attendance bio
	 */
	public void setUploadDate(Date uploadDate);

	/**
	 * Returns the status of this attendance bio.
	 *
	 * @return the status of this attendance bio
	 */
	public int getStatus();

	/**
	 * Sets the status of this attendance bio.
	 *
	 * @param status the status of this attendance bio
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AttendanceBio attendanceBio);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AttendanceBio> toCacheModel();

	@Override
	public AttendanceBio toEscapedModel();

	@Override
	public AttendanceBio toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}