/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Billing service. Represents a row in the &quot;billing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.BillingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.BillingImpl}.
 * </p>
 *
 * @author Samaresh
 * @see Billing
 * @see com.liferay.famocom.erpcloud.model.impl.BillingImpl
 * @see com.liferay.famocom.erpcloud.model.impl.BillingModelImpl
 * @generated
 */
@ProviderType
public interface BillingModel extends BaseModel<Billing> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a billing model instance should use the {@link Billing} interface instead.
	 */

	/**
	 * Returns the primary key of this billing.
	 *
	 * @return the primary key of this billing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this billing.
	 *
	 * @param primaryKey the primary key of this billing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the billing ID of this billing.
	 *
	 * @return the billing ID of this billing
	 */
	public long getBillingId();

	/**
	 * Sets the billing ID of this billing.
	 *
	 * @param billingId the billing ID of this billing
	 */
	public void setBillingId(long billingId);

	/**
	 * Returns the milestone ID of this billing.
	 *
	 * @return the milestone ID of this billing
	 */
	public long getMilestoneId();

	/**
	 * Sets the milestone ID of this billing.
	 *
	 * @param milestoneId the milestone ID of this billing
	 */
	public void setMilestoneId(long milestoneId);

	/**
	 * Returns the billing number of this billing.
	 *
	 * @return the billing number of this billing
	 */
	@AutoEscape
	public String getBillingNumber();

	/**
	 * Sets the billing number of this billing.
	 *
	 * @param billingNumber the billing number of this billing
	 */
	public void setBillingNumber(String billingNumber);

	/**
	 * Returns the billing date of this billing.
	 *
	 * @return the billing date of this billing
	 */
	@AutoEscape
	public String getBillingDate();

	/**
	 * Sets the billing date of this billing.
	 *
	 * @param billingDate the billing date of this billing
	 */
	public void setBillingDate(String billingDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Billing billing);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Billing> toCacheModel();

	@Override
	public Billing toEscapedModel();

	@Override
	public Billing toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}