/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BookingRoom service. Represents a row in the &quot;BookingRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.BookingRoomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.BookingRoomImpl}.
 * </p>
 *
 * @author Samaresh
 * @see BookingRoom
 * @see com.liferay.famocom.erpcloud.model.impl.BookingRoomImpl
 * @see com.liferay.famocom.erpcloud.model.impl.BookingRoomModelImpl
 * @generated
 */
@ProviderType
public interface BookingRoomModel extends BaseModel<BookingRoom> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a booking room model instance should use the {@link BookingRoom} interface instead.
	 */

	/**
	 * Returns the primary key of this booking room.
	 *
	 * @return the primary key of this booking room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this booking room.
	 *
	 * @param primaryKey the primary key of this booking room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the booking ID of this booking room.
	 *
	 * @return the booking ID of this booking room
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this booking room.
	 *
	 * @param bookingId the booking ID of this booking room
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the room ID of this booking room.
	 *
	 * @return the room ID of this booking room
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this booking room.
	 *
	 * @param roomId the room ID of this booking room
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the booking date of this booking room.
	 *
	 * @return the booking date of this booking room
	 */
	public Date getBookingDate();

	/**
	 * Sets the booking date of this booking room.
	 *
	 * @param bookingDate the booking date of this booking room
	 */
	public void setBookingDate(Date bookingDate);

	/**
	 * Returns the from time of this booking room.
	 *
	 * @return the from time of this booking room
	 */
	@AutoEscape
	public String getFromTime();

	/**
	 * Sets the from time of this booking room.
	 *
	 * @param fromTime the from time of this booking room
	 */
	public void setFromTime(String fromTime);

	/**
	 * Returns the to time of this booking room.
	 *
	 * @return the to time of this booking room
	 */
	@AutoEscape
	public String getToTime();

	/**
	 * Sets the to time of this booking room.
	 *
	 * @param toTime the to time of this booking room
	 */
	public void setToTime(String toTime);

	/**
	 * Returns the booked by of this booking room.
	 *
	 * @return the booked by of this booking room
	 */
	public long getBookedBy();

	/**
	 * Sets the booked by of this booking room.
	 *
	 * @param bookedBy the booked by of this booking room
	 */
	public void setBookedBy(long bookedBy);

	/**
	 * Returns the note of this booking room.
	 *
	 * @return the note of this booking room
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this booking room.
	 *
	 * @param note the note of this booking room
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BookingRoom bookingRoom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BookingRoom> toCacheModel();

	@Override
	public BookingRoom toEscapedModel();

	@Override
	public BookingRoom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}