/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CandidateReview service. Represents a row in the &quot;CandidateReview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.CandidateReviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.CandidateReviewImpl}.
 * </p>
 *
 * @author Samaresh
 * @see CandidateReview
 * @see com.liferay.famocom.erpcloud.model.impl.CandidateReviewImpl
 * @see com.liferay.famocom.erpcloud.model.impl.CandidateReviewModelImpl
 * @generated
 */
@ProviderType
public interface CandidateReviewModel extends BaseModel<CandidateReview> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate review model instance should use the {@link CandidateReview} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate review.
	 *
	 * @return the primary key of this candidate review
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate review.
	 *
	 * @param primaryKey the primary key of this candidate review
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the candidate review ID of this candidate review.
	 *
	 * @return the candidate review ID of this candidate review
	 */
	public long getCandidateReviewId();

	/**
	 * Sets the candidate review ID of this candidate review.
	 *
	 * @param candidateReviewId the candidate review ID of this candidate review
	 */
	public void setCandidateReviewId(long candidateReviewId);

	/**
	 * Returns the recruit process ID of this candidate review.
	 *
	 * @return the recruit process ID of this candidate review
	 */
	public long getRecruitProcessId();

	/**
	 * Sets the recruit process ID of this candidate review.
	 *
	 * @param recruitProcessId the recruit process ID of this candidate review
	 */
	public void setRecruitProcessId(long recruitProcessId);

	/**
	 * Returns the evaluation ID of this candidate review.
	 *
	 * @return the evaluation ID of this candidate review
	 */
	public long getEvaluationId();

	/**
	 * Sets the evaluation ID of this candidate review.
	 *
	 * @param evaluationId the evaluation ID of this candidate review
	 */
	public void setEvaluationId(long evaluationId);

	/**
	 * Returns the scroring of this candidate review.
	 *
	 * @return the scroring of this candidate review
	 */
	@AutoEscape
	public String getScroring();

	/**
	 * Sets the scroring of this candidate review.
	 *
	 * @param scroring the scroring of this candidate review
	 */
	public void setScroring(String scroring);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CandidateReview candidateReview);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidateReview> toCacheModel();

	@Override
	public CandidateReview toEscapedModel();

	@Override
	public CandidateReview toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}