/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CandidateEvaluation service. Represents a row in the &quot;CandidateEvaluation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.CandidateEvaluationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.CandidateEvaluationImpl}.
 * </p>
 *
 * @author Samaresh
 * @see CandidateEvaluation
 * @see com.liferay.famocom.erpcloud.model.impl.CandidateEvaluationImpl
 * @see com.liferay.famocom.erpcloud.model.impl.CandidateEvaluationModelImpl
 * @generated
 */
@ProviderType
public interface CandidateEvaluationModel extends BaseModel<CandidateEvaluation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate evaluation model instance should use the {@link CandidateEvaluation} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate evaluation.
	 *
	 * @return the primary key of this candidate evaluation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate evaluation.
	 *
	 * @param primaryKey the primary key of this candidate evaluation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the candidate evaluation ID of this candidate evaluation.
	 *
	 * @return the candidate evaluation ID of this candidate evaluation
	 */
	public long getCandidateEvaluationId();

	/**
	 * Sets the candidate evaluation ID of this candidate evaluation.
	 *
	 * @param candidateEvaluationId the candidate evaluation ID of this candidate evaluation
	 */
	public void setCandidateEvaluationId(long candidateEvaluationId);

	/**
	 * Returns the interviewer ID of this candidate evaluation.
	 *
	 * @return the interviewer ID of this candidate evaluation
	 */
	public long getInterviewerId();

	/**
	 * Sets the interviewer ID of this candidate evaluation.
	 *
	 * @param interviewerId the interviewer ID of this candidate evaluation
	 */
	public void setInterviewerId(long interviewerId);

	/**
	 * Returns the job post ID of this candidate evaluation.
	 *
	 * @return the job post ID of this candidate evaluation
	 */
	public long getJobPostId();

	/**
	 * Sets the job post ID of this candidate evaluation.
	 *
	 * @param jobPostId the job post ID of this candidate evaluation
	 */
	public void setJobPostId(long jobPostId);

	/**
	 * Returns the post evaluation ID of this candidate evaluation.
	 *
	 * @return the post evaluation ID of this candidate evaluation
	 */
	public long getPostEvaluationId();

	/**
	 * Sets the post evaluation ID of this candidate evaluation.
	 *
	 * @param postEvaluationId the post evaluation ID of this candidate evaluation
	 */
	public void setPostEvaluationId(long postEvaluationId);

	/**
	 * Returns the apply candidate ID of this candidate evaluation.
	 *
	 * @return the apply candidate ID of this candidate evaluation
	 */
	public long getApplyCandidateId();

	/**
	 * Sets the apply candidate ID of this candidate evaluation.
	 *
	 * @param applyCandidateId the apply candidate ID of this candidate evaluation
	 */
	public void setApplyCandidateId(long applyCandidateId);

	/**
	 * Returns the interviewer rating of this candidate evaluation.
	 *
	 * @return the interviewer rating of this candidate evaluation
	 */
	public int getInterviewerRating();

	/**
	 * Sets the interviewer rating of this candidate evaluation.
	 *
	 * @param interviewerRating the interviewer rating of this candidate evaluation
	 */
	public void setInterviewerRating(int interviewerRating);

	/**
	 * Returns the interviewer remarks of this candidate evaluation.
	 *
	 * @return the interviewer remarks of this candidate evaluation
	 */
	@AutoEscape
	public String getInterviewerRemarks();

	/**
	 * Sets the interviewer remarks of this candidate evaluation.
	 *
	 * @param interviewerRemarks the interviewer remarks of this candidate evaluation
	 */
	public void setInterviewerRemarks(String interviewerRemarks);

	/**
	 * Returns the hr remarks of this candidate evaluation.
	 *
	 * @return the hr remarks of this candidate evaluation
	 */
	@AutoEscape
	public String getHrRemarks();

	/**
	 * Sets the hr remarks of this candidate evaluation.
	 *
	 * @param hrRemarks the hr remarks of this candidate evaluation
	 */
	public void setHrRemarks(String hrRemarks);

	/**
	 * Returns the create date of this candidate evaluation.
	 *
	 * @return the create date of this candidate evaluation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate evaluation.
	 *
	 * @param createDate the create date of this candidate evaluation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate evaluation.
	 *
	 * @return the modified date of this candidate evaluation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate evaluation.
	 *
	 * @param modifiedDate the modified date of this candidate evaluation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the recruitment process ID of this candidate evaluation.
	 *
	 * @return the recruitment process ID of this candidate evaluation
	 */
	public long getRecruitmentProcessId();

	/**
	 * Sets the recruitment process ID of this candidate evaluation.
	 *
	 * @param recruitmentProcessId the recruitment process ID of this candidate evaluation
	 */
	public void setRecruitmentProcessId(long recruitmentProcessId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CandidateEvaluation candidateEvaluation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidateEvaluation> toCacheModel();

	@Override
	public CandidateEvaluation toEscapedModel();

	@Override
	public CandidateEvaluation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}