/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CandidatePayStructureMaster service. Represents a row in the &quot;candidatePayStructureMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.CandidatePayStructureMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.CandidatePayStructureMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see CandidatePayStructureMaster
 * @see com.liferay.famocom.erpcloud.model.impl.CandidatePayStructureMasterImpl
 * @see com.liferay.famocom.erpcloud.model.impl.CandidatePayStructureMasterModelImpl
 * @generated
 */
@ProviderType
public interface CandidatePayStructureMasterModel extends BaseModel<CandidatePayStructureMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate pay structure master model instance should use the {@link CandidatePayStructureMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate pay structure master.
	 *
	 * @return the primary key of this candidate pay structure master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate pay structure master.
	 *
	 * @param primaryKey the primary key of this candidate pay structure master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the candidate pay structure master ID of this candidate pay structure master.
	 *
	 * @return the candidate pay structure master ID of this candidate pay structure master
	 */
	public long getCandidatePayStructureMasterId();

	/**
	 * Sets the candidate pay structure master ID of this candidate pay structure master.
	 *
	 * @param candidatePayStructureMasterId the candidate pay structure master ID of this candidate pay structure master
	 */
	public void setCandidatePayStructureMasterId(
		long candidatePayStructureMasterId);

	/**
	 * Returns the recruitment process ID of this candidate pay structure master.
	 *
	 * @return the recruitment process ID of this candidate pay structure master
	 */
	public long getRecruitmentProcessId();

	/**
	 * Sets the recruitment process ID of this candidate pay structure master.
	 *
	 * @param recruitmentProcessId the recruitment process ID of this candidate pay structure master
	 */
	public void setRecruitmentProcessId(long recruitmentProcessId);

	/**
	 * Returns the total amount of this candidate pay structure master.
	 *
	 * @return the total amount of this candidate pay structure master
	 */
	public double getTotalAmount();

	/**
	 * Sets the total amount of this candidate pay structure master.
	 *
	 * @param totalAmount the total amount of this candidate pay structure master
	 */
	public void setTotalAmount(double totalAmount);

	/**
	 * Returns the total bonus of this candidate pay structure master.
	 *
	 * @return the total bonus of this candidate pay structure master
	 */
	public double getTotalBonus();

	/**
	 * Sets the total bonus of this candidate pay structure master.
	 *
	 * @param totalBonus the total bonus of this candidate pay structure master
	 */
	public void setTotalBonus(double totalBonus);

	/**
	 * Returns the pay master status of this candidate pay structure master.
	 *
	 * @return the pay master status of this candidate pay structure master
	 */
	public int getPayMasterStatus();

	/**
	 * Sets the pay master status of this candidate pay structure master.
	 *
	 * @param payMasterStatus the pay master status of this candidate pay structure master
	 */
	public void setPayMasterStatus(int payMasterStatus);

	/**
	 * Returns the joining date of this candidate pay structure master.
	 *
	 * @return the joining date of this candidate pay structure master
	 */
	public Date getJoiningDate();

	/**
	 * Sets the joining date of this candidate pay structure master.
	 *
	 * @param joiningDate the joining date of this candidate pay structure master
	 */
	public void setJoiningDate(Date joiningDate);

	/**
	 * Returns the candidate bond of this candidate pay structure master.
	 *
	 * @return the candidate bond of this candidate pay structure master
	 */
	@AutoEscape
	public String getCandidateBond();

	/**
	 * Sets the candidate bond of this candidate pay structure master.
	 *
	 * @param candidateBond the candidate bond of this candidate pay structure master
	 */
	public void setCandidateBond(String candidateBond);

	/**
	 * Returns the create date of this candidate pay structure master.
	 *
	 * @return the create date of this candidate pay structure master
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate pay structure master.
	 *
	 * @param createDate the create date of this candidate pay structure master
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate pay structure master.
	 *
	 * @return the modified date of this candidate pay structure master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate pay structure master.
	 *
	 * @param modifiedDate the modified date of this candidate pay structure master
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		CandidatePayStructureMaster candidatePayStructureMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidatePayStructureMaster> toCacheModel();

	@Override
	public CandidatePayStructureMaster toEscapedModel();

	@Override
	public CandidatePayStructureMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}