/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CandidateApply service. Represents a row in the &quot;CandidateApply&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.CandidateApplyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.CandidateApplyImpl}.
 * </p>
 *
 * @author Samaresh
 * @see CandidateApply
 * @see com.liferay.famocom.erpcloud.model.impl.CandidateApplyImpl
 * @see com.liferay.famocom.erpcloud.model.impl.CandidateApplyModelImpl
 * @generated
 */
@ProviderType
public interface CandidateApplyModel extends BaseModel<CandidateApply> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate apply model instance should use the {@link CandidateApply} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate apply.
	 *
	 * @return the primary key of this candidate apply
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate apply.
	 *
	 * @param primaryKey the primary key of this candidate apply
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the apply candidate ID of this candidate apply.
	 *
	 * @return the apply candidate ID of this candidate apply
	 */
	public long getApplyCandidateId();

	/**
	 * Sets the apply candidate ID of this candidate apply.
	 *
	 * @param applyCandidateId the apply candidate ID of this candidate apply
	 */
	public void setApplyCandidateId(long applyCandidateId);

	/**
	 * Returns the first name of this candidate apply.
	 *
	 * @return the first name of this candidate apply
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this candidate apply.
	 *
	 * @param firstName the first name of this candidate apply
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this candidate apply.
	 *
	 * @return the last name of this candidate apply
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this candidate apply.
	 *
	 * @param lastName the last name of this candidate apply
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email address of this candidate apply.
	 *
	 * @return the email address of this candidate apply
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this candidate apply.
	 *
	 * @param emailAddress the email address of this candidate apply
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the phone number of this candidate apply.
	 *
	 * @return the phone number of this candidate apply
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this candidate apply.
	 *
	 * @param phoneNumber the phone number of this candidate apply
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the year of exp of this candidate apply.
	 *
	 * @return the year of exp of this candidate apply
	 */
	public int getYearOfExp();

	/**
	 * Sets the year of exp of this candidate apply.
	 *
	 * @param yearOfExp the year of exp of this candidate apply
	 */
	public void setYearOfExp(int yearOfExp);

	/**
	 * Returns the month of exp of this candidate apply.
	 *
	 * @return the month of exp of this candidate apply
	 */
	public int getMonthOfExp();

	/**
	 * Sets the month of exp of this candidate apply.
	 *
	 * @param monthOfExp the month of exp of this candidate apply
	 */
	public void setMonthOfExp(int monthOfExp);

	/**
	 * Returns the current ctc of this candidate apply.
	 *
	 * @return the current ctc of this candidate apply
	 */
	public int getCurrentCTC();

	/**
	 * Sets the current ctc of this candidate apply.
	 *
	 * @param currentCTC the current ctc of this candidate apply
	 */
	public void setCurrentCTC(int currentCTC);

	/**
	 * Returns the expected ctc of this candidate apply.
	 *
	 * @return the expected ctc of this candidate apply
	 */
	public int getExpectedCTC();

	/**
	 * Sets the expected ctc of this candidate apply.
	 *
	 * @param expectedCTC the expected ctc of this candidate apply
	 */
	public void setExpectedCTC(int expectedCTC);

	/**
	 * Returns the current company of this candidate apply.
	 *
	 * @return the current company of this candidate apply
	 */
	@AutoEscape
	public String getCurrentCompany();

	/**
	 * Sets the current company of this candidate apply.
	 *
	 * @param currentCompany the current company of this candidate apply
	 */
	public void setCurrentCompany(String currentCompany);

	/**
	 * Returns the notice period of this candidate apply.
	 *
	 * @return the notice period of this candidate apply
	 */
	public int getNoticePeriod();

	/**
	 * Sets the notice period of this candidate apply.
	 *
	 * @param noticePeriod the notice period of this candidate apply
	 */
	public void setNoticePeriod(int noticePeriod);

	/**
	 * Returns the reference employee ID of this candidate apply.
	 *
	 * @return the reference employee ID of this candidate apply
	 */
	public long getReferenceEmployeeId();

	/**
	 * Sets the reference employee ID of this candidate apply.
	 *
	 * @param referenceEmployeeId the reference employee ID of this candidate apply
	 */
	public void setReferenceEmployeeId(long referenceEmployeeId);

	/**
	 * Returns the cv file ID of this candidate apply.
	 *
	 * @return the cv file ID of this candidate apply
	 */
	public long getCvFileId();

	/**
	 * Sets the cv file ID of this candidate apply.
	 *
	 * @param cvFileId the cv file ID of this candidate apply
	 */
	public void setCvFileId(long cvFileId);

	/**
	 * Returns the job opening ID of this candidate apply.
	 *
	 * @return the job opening ID of this candidate apply
	 */
	public long getJobOpeningId();

	/**
	 * Sets the job opening ID of this candidate apply.
	 *
	 * @param jobOpeningId the job opening ID of this candidate apply
	 */
	public void setJobOpeningId(long jobOpeningId);

	/**
	 * Returns the skillset of this candidate apply.
	 *
	 * @return the skillset of this candidate apply
	 */
	@AutoEscape
	public String getSkillset();

	/**
	 * Sets the skillset of this candidate apply.
	 *
	 * @param skillset the skillset of this candidate apply
	 */
	public void setSkillset(String skillset);

	/**
	 * Returns the status of this candidate apply.
	 *
	 * @return the status of this candidate apply
	 */
	public int getStatus();

	/**
	 * Sets the status of this candidate apply.
	 *
	 * @param status the status of this candidate apply
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CandidateApply candidateApply);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidateApply> toCacheModel();

	@Override
	public CandidateApply toEscapedModel();

	@Override
	public CandidateApply toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}