/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ClientMaster service. Represents a row in the &quot;clientMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ClientMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ClientMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ClientMaster
 * @see com.liferay.famocom.erpcloud.model.impl.ClientMasterImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ClientMasterModelImpl
 * @generated
 */
@ProviderType
public interface ClientMasterModel extends BaseModel<ClientMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a client master model instance should use the {@link ClientMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this client master.
	 *
	 * @return the primary key of this client master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this client master.
	 *
	 * @param primaryKey the primary key of this client master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the client ID of this client master.
	 *
	 * @return the client ID of this client master
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this client master.
	 *
	 * @param clientId the client ID of this client master
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the client name of this client master.
	 *
	 * @return the client name of this client master
	 */
	@AutoEscape
	public String getClientName();

	/**
	 * Sets the client name of this client master.
	 *
	 * @param clientName the client name of this client master
	 */
	public void setClientName(String clientName);

	/**
	 * Returns the office address of this client master.
	 *
	 * @return the office address of this client master
	 */
	@AutoEscape
	public String getOfficeAddress();

	/**
	 * Sets the office address of this client master.
	 *
	 * @param officeAddress the office address of this client master
	 */
	public void setOfficeAddress(String officeAddress);

	/**
	 * Returns the billing address of this client master.
	 *
	 * @return the billing address of this client master
	 */
	@AutoEscape
	public String getBillingAddress();

	/**
	 * Sets the billing address of this client master.
	 *
	 * @param billingAddress the billing address of this client master
	 */
	public void setBillingAddress(String billingAddress);

	/**
	 * Returns the contact number of this client master.
	 *
	 * @return the contact number of this client master
	 */
	public int getContactNumber();

	/**
	 * Sets the contact number of this client master.
	 *
	 * @param contactNumber the contact number of this client master
	 */
	public void setContactNumber(int contactNumber);

	/**
	 * Returns the email ID of this client master.
	 *
	 * @return the email ID of this client master
	 */
	@AutoEscape
	public String getEmailId();

	/**
	 * Sets the email ID of this client master.
	 *
	 * @param emailId the email ID of this client master
	 */
	public void setEmailId(String emailId);

	/**
	 * Returns the contact person of this client master.
	 *
	 * @return the contact person of this client master
	 */
	@AutoEscape
	public String getContactPerson();

	/**
	 * Sets the contact person of this client master.
	 *
	 * @param contactPerson the contact person of this client master
	 */
	public void setContactPerson(String contactPerson);

	/**
	 * Returns the skype ID of this client master.
	 *
	 * @return the skype ID of this client master
	 */
	@AutoEscape
	public String getSkypeId();

	/**
	 * Sets the skype ID of this client master.
	 *
	 * @param skypeId the skype ID of this client master
	 */
	public void setSkypeId(String skypeId);

	/**
	 * Returns the gst no of this client master.
	 *
	 * @return the gst no of this client master
	 */
	public long getGstNo();

	/**
	 * Sets the gst no of this client master.
	 *
	 * @param gstNo the gst no of this client master
	 */
	public void setGstNo(long gstNo);

	/**
	 * Returns the pan no of this client master.
	 *
	 * @return the pan no of this client master
	 */
	@AutoEscape
	public String getPanNo();

	/**
	 * Sets the pan no of this client master.
	 *
	 * @param panNo the pan no of this client master
	 */
	public void setPanNo(String panNo);

	/**
	 * Returns the bank name of this client master.
	 *
	 * @return the bank name of this client master
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this client master.
	 *
	 * @param bankName the bank name of this client master
	 */
	public void setBankName(String bankName);

	/**
	 * Returns the branch name of this client master.
	 *
	 * @return the branch name of this client master
	 */
	@AutoEscape
	public String getBranchName();

	/**
	 * Sets the branch name of this client master.
	 *
	 * @param branchName the branch name of this client master
	 */
	public void setBranchName(String branchName);

	/**
	 * Returns the bank account number of this client master.
	 *
	 * @return the bank account number of this client master
	 */
	public long getBankAccountNumber();

	/**
	 * Sets the bank account number of this client master.
	 *
	 * @param bankAccountNumber the bank account number of this client master
	 */
	public void setBankAccountNumber(long bankAccountNumber);

	/**
	 * Returns the bank account type of this client master.
	 *
	 * @return the bank account type of this client master
	 */
	@AutoEscape
	public String getBankAccountType();

	/**
	 * Sets the bank account type of this client master.
	 *
	 * @param bankAccountType the bank account type of this client master
	 */
	public void setBankAccountType(String bankAccountType);

	/**
	 * Returns the ifsc code of this client master.
	 *
	 * @return the ifsc code of this client master
	 */
	@AutoEscape
	public String getIfscCode();

	/**
	 * Sets the ifsc code of this client master.
	 *
	 * @param ifscCode the ifsc code of this client master
	 */
	public void setIfscCode(String ifscCode);

	/**
	 * Returns the added date of this client master.
	 *
	 * @return the added date of this client master
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this client master.
	 *
	 * @param addedDate the added date of this client master
	 */
	public void setAddedDate(Date addedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ClientMaster clientMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ClientMaster> toCacheModel();

	@Override
	public ClientMaster toEscapedModel();

	@Override
	public ClientMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}