/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CompanyPolicy service. Represents a row in the &quot;companyPolicy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.CompanyPolicyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.CompanyPolicyImpl}.
 * </p>
 *
 * @author Samaresh
 * @see CompanyPolicy
 * @see com.liferay.famocom.erpcloud.model.impl.CompanyPolicyImpl
 * @see com.liferay.famocom.erpcloud.model.impl.CompanyPolicyModelImpl
 * @generated
 */
@ProviderType
public interface CompanyPolicyModel extends BaseModel<CompanyPolicy>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a company policy model instance should use the {@link CompanyPolicy} interface instead.
	 */

	/**
	 * Returns the primary key of this company policy.
	 *
	 * @return the primary key of this company policy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this company policy.
	 *
	 * @param primaryKey the primary key of this company policy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company policy ID of this company policy.
	 *
	 * @return the company policy ID of this company policy
	 */
	public long getCompanyPolicyId();

	/**
	 * Sets the company policy ID of this company policy.
	 *
	 * @param companyPolicyId the company policy ID of this company policy
	 */
	public void setCompanyPolicyId(long companyPolicyId);

	/**
	 * Returns the company ID of this company policy.
	 *
	 * @return the company ID of this company policy
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this company policy.
	 *
	 * @param companyId the company ID of this company policy
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the days locking of this company policy.
	 *
	 * @return the days locking of this company policy
	 */
	public int getDaysLocking();

	/**
	 * Sets the days locking of this company policy.
	 *
	 * @param daysLocking the days locking of this company policy
	 */
	public void setDaysLocking(int daysLocking);

	/**
	 * Returns the check status of this company policy.
	 *
	 * @return the check status of this company policy
	 */
	public int getCheckStatus();

	/**
	 * Sets the check status of this company policy.
	 *
	 * @param checkStatus the check status of this company policy
	 */
	public void setCheckStatus(int checkStatus);

	/**
	 * Returns the added date of this company policy.
	 *
	 * @return the added date of this company policy
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this company policy.
	 *
	 * @param addedDate the added date of this company policy
	 */
	public void setAddedDate(Date addedDate);

	/**
	 * Returns the modified date of this company policy.
	 *
	 * @return the modified date of this company policy
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this company policy.
	 *
	 * @param modifiedDate the modified date of this company policy
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CompanyPolicy companyPolicy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CompanyPolicy> toCacheModel();

	@Override
	public CompanyPolicy toEscapedModel();

	@Override
	public CompanyPolicy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}