/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ConferenceRoom service. Represents a row in the &quot;ConferenceRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ConferenceRoomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ConferenceRoomImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ConferenceRoom
 * @see com.liferay.famocom.erpcloud.model.impl.ConferenceRoomImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ConferenceRoomModelImpl
 * @generated
 */
@ProviderType
public interface ConferenceRoomModel extends BaseModel<ConferenceRoom> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a conference room model instance should use the {@link ConferenceRoom} interface instead.
	 */

	/**
	 * Returns the primary key of this conference room.
	 *
	 * @return the primary key of this conference room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this conference room.
	 *
	 * @param primaryKey the primary key of this conference room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the room ID of this conference room.
	 *
	 * @return the room ID of this conference room
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this conference room.
	 *
	 * @param roomId the room ID of this conference room
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the room no of this conference room.
	 *
	 * @return the room no of this conference room
	 */
	public long getRoomNo();

	/**
	 * Sets the room no of this conference room.
	 *
	 * @param roomNo the room no of this conference room
	 */
	public void setRoomNo(long roomNo);

	/**
	 * Returns the floor no of this conference room.
	 *
	 * @return the floor no of this conference room
	 */
	public long getFloorNo();

	/**
	 * Sets the floor no of this conference room.
	 *
	 * @param floorNo the floor no of this conference room
	 */
	public void setFloorNo(long floorNo);

	/**
	 * Returns the capacity of this conference room.
	 *
	 * @return the capacity of this conference room
	 */
	public long getCapacity();

	/**
	 * Sets the capacity of this conference room.
	 *
	 * @param capacity the capacity of this conference room
	 */
	public void setCapacity(long capacity);

	/**
	 * Returns the open time of this conference room.
	 *
	 * @return the open time of this conference room
	 */
	@AutoEscape
	public String getOpenTime();

	/**
	 * Sets the open time of this conference room.
	 *
	 * @param openTime the open time of this conference room
	 */
	public void setOpenTime(String openTime);

	/**
	 * Returns the close time of this conference room.
	 *
	 * @return the close time of this conference room
	 */
	@AutoEscape
	public String getCloseTime();

	/**
	 * Sets the close time of this conference room.
	 *
	 * @param closeTime the close time of this conference room
	 */
	public void setCloseTime(String closeTime);

	/**
	 * Returns the building of this conference room.
	 *
	 * @return the building of this conference room
	 */
	@AutoEscape
	public String getBuilding();

	/**
	 * Sets the building of this conference room.
	 *
	 * @param building the building of this conference room
	 */
	public void setBuilding(String building);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ConferenceRoom conferenceRoom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ConferenceRoom> toCacheModel();

	@Override
	public ConferenceRoom toEscapedModel();

	@Override
	public ConferenceRoom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}