/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DocumentUploadFile service. Represents a row in the &quot;documentUploadFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.DocumentUploadFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.DocumentUploadFileImpl}.
 * </p>
 *
 * @author Samaresh
 * @see DocumentUploadFile
 * @see com.liferay.famocom.erpcloud.model.impl.DocumentUploadFileImpl
 * @see com.liferay.famocom.erpcloud.model.impl.DocumentUploadFileModelImpl
 * @generated
 */
@ProviderType
public interface DocumentUploadFileModel extends BaseModel<DocumentUploadFile>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document upload file model instance should use the {@link DocumentUploadFile} interface instead.
	 */

	/**
	 * Returns the primary key of this document upload file.
	 *
	 * @return the primary key of this document upload file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document upload file.
	 *
	 * @param primaryKey the primary key of this document upload file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the document ID of this document upload file.
	 *
	 * @return the document ID of this document upload file
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document upload file.
	 *
	 * @param documentId the document ID of this document upload file
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the company ID of this document upload file.
	 *
	 * @return the company ID of this document upload file
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this document upload file.
	 *
	 * @param companyId the company ID of this document upload file
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee ID of this document upload file.
	 *
	 * @return the employee ID of this document upload file
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this document upload file.
	 *
	 * @param employeeId the employee ID of this document upload file
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the file entry ID of this document upload file.
	 *
	 * @return the file entry ID of this document upload file
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this document upload file.
	 *
	 * @param fileEntryId the file entry ID of this document upload file
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the document name of this document upload file.
	 *
	 * @return the document name of this document upload file
	 */
	@AutoEscape
	public String getDocumentName();

	/**
	 * Sets the document name of this document upload file.
	 *
	 * @param documentName the document name of this document upload file
	 */
	public void setDocumentName(String documentName);

	/**
	 * Returns the document path of this document upload file.
	 *
	 * @return the document path of this document upload file
	 */
	@AutoEscape
	public String getDocumentPath();

	/**
	 * Sets the document path of this document upload file.
	 *
	 * @param documentPath the document path of this document upload file
	 */
	public void setDocumentPath(String documentPath);

	/**
	 * Returns the upload date of this document upload file.
	 *
	 * @return the upload date of this document upload file
	 */
	public Date getUploadDate();

	/**
	 * Sets the upload date of this document upload file.
	 *
	 * @param uploadDate the upload date of this document upload file
	 */
	public void setUploadDate(Date uploadDate);

	/**
	 * Returns the travel details ID of this document upload file.
	 *
	 * @return the travel details ID of this document upload file
	 */
	public long getTravelDetailsId();

	/**
	 * Sets the travel details ID of this document upload file.
	 *
	 * @param travelDetailsId the travel details ID of this document upload file
	 */
	public void setTravelDetailsId(long travelDetailsId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DocumentUploadFile documentUploadFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DocumentUploadFile> toCacheModel();

	@Override
	public DocumentUploadFile toEscapedModel();

	@Override
	public DocumentUploadFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}