/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Samaresh
 * @see Employee
 * @see com.liferay.famocom.erpcloud.model.impl.EmployeeImpl
 * @see com.liferay.famocom.erpcloud.model.impl.EmployeeModelImpl
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee>, ShardedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee ID of this employee.
	 *
	 * @return the employee ID of this employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee.
	 *
	 * @param employeeId the employee ID of this employee
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this employee.
	 *
	 * @return the company ID of this employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee.
	 *
	 * @param companyId the company ID of this employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee code of this employee.
	 *
	 * @return the employee code of this employee
	 */
	public long getEmployeeCode();

	/**
	 * Sets the employee code of this employee.
	 *
	 * @param employeeCode the employee code of this employee
	 */
	public void setEmployeeCode(long employeeCode);

	/**
	 * Returns the date of joing of this employee.
	 *
	 * @return the date of joing of this employee
	 */
	public Date getDateOfJoing();

	/**
	 * Sets the date of joing of this employee.
	 *
	 * @param dateOfJoing the date of joing of this employee
	 */
	public void setDateOfJoing(Date dateOfJoing);

	/**
	 * Returns the first name of this employee.
	 *
	 * @return the first name of this employee
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this employee.
	 *
	 * @param firstName the first name of this employee
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this employee.
	 *
	 * @return the last name of this employee
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this employee.
	 *
	 * @param lastName the last name of this employee
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the designation of this employee.
	 *
	 * @return the designation of this employee
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this employee.
	 *
	 * @param designation the designation of this employee
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the date of birth of this employee.
	 *
	 * @return the date of birth of this employee
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this employee.
	 *
	 * @param dateOfBirth the date of birth of this employee
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the gender of this employee.
	 *
	 * @return the gender of this employee
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this employee.
	 *
	 * @param gender the gender of this employee
	 */
	public void setGender(String gender);

	/**
	 * Returns the marital status of this employee.
	 *
	 * @return the marital status of this employee
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this employee.
	 *
	 * @param maritalStatus the marital status of this employee
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the no of child of this employee.
	 *
	 * @return the no of child of this employee
	 */
	public long getNoOfChild();

	/**
	 * Sets the no of child of this employee.
	 *
	 * @param noOfChild the no of child of this employee
	 */
	public void setNoOfChild(long noOfChild);

	/**
	 * Returns the note of this employee.
	 *
	 * @return the note of this employee
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this employee.
	 *
	 * @param note the note of this employee
	 */
	public void setNote(String note);

	/**
	 * Returns the address of this employee.
	 *
	 * @return the address of this employee
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this employee.
	 *
	 * @param address the address of this employee
	 */
	public void setAddress(String address);

	/**
	 * Returns the state of this employee.
	 *
	 * @return the state of this employee
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this employee.
	 *
	 * @param state the state of this employee
	 */
	public void setState(String state);

	/**
	 * Returns the post code of this employee.
	 *
	 * @return the post code of this employee
	 */
	@AutoEscape
	public String getPostCode();

	/**
	 * Sets the post code of this employee.
	 *
	 * @param postCode the post code of this employee
	 */
	public void setPostCode(String postCode);

	/**
	 * Returns the home phone of this employee.
	 *
	 * @return the home phone of this employee
	 */
	public int getHomePhone();

	/**
	 * Sets the home phone of this employee.
	 *
	 * @param homePhone the home phone of this employee
	 */
	public void setHomePhone(int homePhone);

	/**
	 * Returns the mobile number of this employee.
	 *
	 * @return the mobile number of this employee
	 */
	public int getMobileNumber();

	/**
	 * Sets the mobile number of this employee.
	 *
	 * @param mobileNumber the mobile number of this employee
	 */
	public void setMobileNumber(int mobileNumber);

	/**
	 * Returns the emai address of this employee.
	 *
	 * @return the emai address of this employee
	 */
	@AutoEscape
	public String getEmaiAddress();

	/**
	 * Sets the emai address of this employee.
	 *
	 * @param emaiAddress the emai address of this employee
	 */
	public void setEmaiAddress(String emaiAddress);

	/**
	 * Returns the anniversary of this employee.
	 *
	 * @return the anniversary of this employee
	 */
	public Date getAnniversary();

	/**
	 * Sets the anniversary of this employee.
	 *
	 * @param anniversary the anniversary of this employee
	 */
	public void setAnniversary(Date anniversary);

	/**
	 * Returns the employee photo of this employee.
	 *
	 * @return the employee photo of this employee
	 */
	public Blob getEmployeePhoto();

	/**
	 * Sets the employee photo of this employee.
	 *
	 * @param employeePhoto the employee photo of this employee
	 */
	public void setEmployeePhoto(Blob employeePhoto);

	/**
	 * Returns the employee status of this employee.
	 *
	 * @return the employee status of this employee
	 */
	public int getEmployeeStatus();

	/**
	 * Sets the employee status of this employee.
	 *
	 * @param employeeStatus the employee status of this employee
	 */
	public void setEmployeeStatus(int employeeStatus);

	/**
	 * Returns the total pay of this employee.
	 *
	 * @return the total pay of this employee
	 */
	public double getTotalPay();

	/**
	 * Sets the total pay of this employee.
	 *
	 * @param totalPay the total pay of this employee
	 */
	public void setTotalPay(double totalPay);

	/**
	 * Returns the basic pay of this employee.
	 *
	 * @return the basic pay of this employee
	 */
	public double getBasicPay();

	/**
	 * Sets the basic pay of this employee.
	 *
	 * @param basicPay the basic pay of this employee
	 */
	public void setBasicPay(double basicPay);

	/**
	 * Returns the da of this employee.
	 *
	 * @return the da of this employee
	 */
	public double getDa();

	/**
	 * Sets the da of this employee.
	 *
	 * @param da the da of this employee
	 */
	public void setDa(double da);

	/**
	 * Returns the hra of this employee.
	 *
	 * @return the hra of this employee
	 */
	public double getHra();

	/**
	 * Sets the hra of this employee.
	 *
	 * @param hra the hra of this employee
	 */
	public void setHra(double hra);

	/**
	 * Returns the medical of this employee.
	 *
	 * @return the medical of this employee
	 */
	public double getMedical();

	/**
	 * Sets the medical of this employee.
	 *
	 * @param medical the medical of this employee
	 */
	public void setMedical(double medical);

	/**
	 * Returns the ta of this employee.
	 *
	 * @return the ta of this employee
	 */
	public double getTa();

	/**
	 * Sets the ta of this employee.
	 *
	 * @param ta the ta of this employee
	 */
	public void setTa(double ta);

	/**
	 * Returns the conveyance of this employee.
	 *
	 * @return the conveyance of this employee
	 */
	public double getConveyance();

	/**
	 * Sets the conveyance of this employee.
	 *
	 * @param conveyance the conveyance of this employee
	 */
	public void setConveyance(double conveyance);

	/**
	 * Returns the internet of this employee.
	 *
	 * @return the internet of this employee
	 */
	public double getInternet();

	/**
	 * Sets the internet of this employee.
	 *
	 * @param internet the internet of this employee
	 */
	public void setInternet(double internet);

	/**
	 * Returns the mobile of this employee.
	 *
	 * @return the mobile of this employee
	 */
	public double getMobile();

	/**
	 * Sets the mobile of this employee.
	 *
	 * @param mobile the mobile of this employee
	 */
	public void setMobile(double mobile);

	/**
	 * Returns the fare of this employee.
	 *
	 * @return the fare of this employee
	 */
	public double getFare();

	/**
	 * Sets the fare of this employee.
	 *
	 * @param fare the fare of this employee
	 */
	public void setFare(double fare);

	/**
	 * Returns the areas of this employee.
	 *
	 * @return the areas of this employee
	 */
	public double getAreas();

	/**
	 * Sets the areas of this employee.
	 *
	 * @param areas the areas of this employee
	 */
	public void setAreas(double areas);

	/**
	 * Returns the bouns of this employee.
	 *
	 * @return the bouns of this employee
	 */
	public double getBouns();

	/**
	 * Sets the bouns of this employee.
	 *
	 * @param bouns the bouns of this employee
	 */
	public void setBouns(double bouns);

	/**
	 * Returns the insurance of this employee.
	 *
	 * @return the insurance of this employee
	 */
	public double getInsurance();

	/**
	 * Sets the insurance of this employee.
	 *
	 * @param insurance the insurance of this employee
	 */
	public void setInsurance(double insurance);

	/**
	 * Returns the other allowance of this employee.
	 *
	 * @return the other allowance of this employee
	 */
	public double getOtherAllowance();

	/**
	 * Sets the other allowance of this employee.
	 *
	 * @param otherAllowance the other allowance of this employee
	 */
	public void setOtherAllowance(double otherAllowance);

	/**
	 * Returns the provident fund of this employee.
	 *
	 * @return the provident fund of this employee
	 */
	public double getProvidentFund();

	/**
	 * Sets the provident fund of this employee.
	 *
	 * @param providentFund the provident fund of this employee
	 */
	public void setProvidentFund(double providentFund);

	/**
	 * Returns the profession tax of this employee.
	 *
	 * @return the profession tax of this employee
	 */
	public double getProfessionTax();

	/**
	 * Sets the profession tax of this employee.
	 *
	 * @param professionTax the profession tax of this employee
	 */
	public void setProfessionTax(double professionTax);

	/**
	 * Returns the income tax of this employee.
	 *
	 * @return the income tax of this employee
	 */
	public double getIncomeTax();

	/**
	 * Sets the income tax of this employee.
	 *
	 * @param incomeTax the income tax of this employee
	 */
	public void setIncomeTax(double incomeTax);

	/**
	 * Returns the loan of this employee.
	 *
	 * @return the loan of this employee
	 */
	public double getLoan();

	/**
	 * Sets the loan of this employee.
	 *
	 * @param loan the loan of this employee
	 */
	public void setLoan(double loan);

	/**
	 * Returns the other deduction of this employee.
	 *
	 * @return the other deduction of this employee
	 */
	public double getOtherDeduction();

	/**
	 * Sets the other deduction of this employee.
	 *
	 * @param otherDeduction the other deduction of this employee
	 */
	public void setOtherDeduction(double otherDeduction);

	/**
	 * Returns the bank ID of this employee.
	 *
	 * @return the bank ID of this employee
	 */
	public long getBankId();

	/**
	 * Sets the bank ID of this employee.
	 *
	 * @param bankId the bank ID of this employee
	 */
	public void setBankId(long bankId);

	/**
	 * Returns the branch address of this employee.
	 *
	 * @return the branch address of this employee
	 */
	@AutoEscape
	public String getBranchAddress();

	/**
	 * Sets the branch address of this employee.
	 *
	 * @param branchAddress the branch address of this employee
	 */
	public void setBranchAddress(String branchAddress);

	/**
	 * Returns the account no of this employee.
	 *
	 * @return the account no of this employee
	 */
	@AutoEscape
	public String getAccountNo();

	/**
	 * Sets the account no of this employee.
	 *
	 * @param accountNo the account no of this employee
	 */
	public void setAccountNo(String accountNo);

	/**
	 * Returns the pf no of this employee.
	 *
	 * @return the pf no of this employee
	 */
	@AutoEscape
	public String getPfNo();

	/**
	 * Sets the pf no of this employee.
	 *
	 * @param pfNo the pf no of this employee
	 */
	public void setPfNo(String pfNo);

	/**
	 * Returns the aadhaar no of this employee.
	 *
	 * @return the aadhaar no of this employee
	 */
	@AutoEscape
	public String getAadhaarNo();

	/**
	 * Sets the aadhaar no of this employee.
	 *
	 * @param aadhaarNo the aadhaar no of this employee
	 */
	public void setAadhaarNo(String aadhaarNo);

	/**
	 * Returns the employeetype ID of this employee.
	 *
	 * @return the employeetype ID of this employee
	 */
	public int getEmployeetypeId();

	/**
	 * Sets the employeetype ID of this employee.
	 *
	 * @param employeetypeId the employeetype ID of this employee
	 */
	public void setEmployeetypeId(int employeetypeId);

	/**
	 * Returns the ispfdeduct of this employee.
	 *
	 * @return the ispfdeduct of this employee
	 */
	public int getIspfdeduct();

	/**
	 * Sets the ispfdeduct of this employee.
	 *
	 * @param ispfdeduct the ispfdeduct of this employee
	 */
	public void setIspfdeduct(int ispfdeduct);

	/**
	 * Returns the role ID of this employee.
	 *
	 * @return the role ID of this employee
	 */
	public int getRoleId();

	/**
	 * Sets the role ID of this employee.
	 *
	 * @param roleId the role ID of this employee
	 */
	public void setRoleId(int roleId);

	/**
	 * Returns the added date of this employee.
	 *
	 * @return the added date of this employee
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this employee.
	 *
	 * @param addedDate the added date of this employee
	 */
	public void setAddedDate(Date addedDate);

	/**
	 * Returns the photo ID of this employee.
	 *
	 * @return the photo ID of this employee
	 */
	public long getPhotoId();

	/**
	 * Sets the photo ID of this employee.
	 *
	 * @param photoId the photo ID of this employee
	 */
	public void setPhotoId(long photoId);

	/**
	 * Returns the user ID of this employee.
	 *
	 * @return the user ID of this employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee.
	 *
	 * @param userId the user ID of this employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee.
	 *
	 * @return the user uuid of this employee
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee.
	 *
	 * @param userUuid the user uuid of this employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the branch ID of this employee.
	 *
	 * @return the branch ID of this employee
	 */
	public long getBranchId();

	/**
	 * Sets the branch ID of this employee.
	 *
	 * @param branchId the branch ID of this employee
	 */
	public void setBranchId(long branchId);

	/**
	 * Returns the pan no of this employee.
	 *
	 * @return the pan no of this employee
	 */
	@AutoEscape
	public String getPanNo();

	/**
	 * Sets the pan no of this employee.
	 *
	 * @param panNo the pan no of this employee
	 */
	public void setPanNo(String panNo);

	/**
	 * Returns the pesonal emai address of this employee.
	 *
	 * @return the pesonal emai address of this employee
	 */
	@AutoEscape
	public String getPesonalEmaiAddress();

	/**
	 * Sets the pesonal emai address of this employee.
	 *
	 * @param pesonalEmaiAddress the pesonal emai address of this employee
	 */
	public void setPesonalEmaiAddress(String pesonalEmaiAddress);

	/**
	 * Returns the pay per month of this employee.
	 *
	 * @return the pay per month of this employee
	 */
	public double getPayPerMonth();

	/**
	 * Sets the pay per month of this employee.
	 *
	 * @param payPerMonth the pay per month of this employee
	 */
	public void setPayPerMonth(double payPerMonth);

	/**
	 * Returns the group ID of this employee.
	 *
	 * @return the group ID of this employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee.
	 *
	 * @param groupId the group ID of this employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the status of this employee.
	 *
	 * @return the status of this employee
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this employee.
	 *
	 * @param status the status of this employee
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this employee.
	 *
	 * @return the status by user ID of this employee
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this employee.
	 *
	 * @param statusByUserId the status by user ID of this employee
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this employee.
	 *
	 * @return the status by user uuid of this employee
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this employee.
	 *
	 * @param statusByUserUuid the status by user uuid of this employee
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this employee.
	 *
	 * @return the status by user name of this employee
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this employee.
	 *
	 * @param statusByUserName the status by user name of this employee
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this employee.
	 *
	 * @return the status date of this employee
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this employee.
	 *
	 * @param statusDate the status date of this employee
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the create date of this employee.
	 *
	 * @return the create date of this employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee.
	 *
	 * @param createDate the create date of this employee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee.
	 *
	 * @return the modified date of this employee
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee.
	 *
	 * @param modifiedDate the modified date of this employee
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns <code>true</code> if this employee is approved.
	 *
	 * @return <code>true</code> if this employee is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this employee is denied.
	 *
	 * @return <code>true</code> if this employee is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this employee is a draft.
	 *
	 * @return <code>true</code> if this employee is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this employee is expired.
	 *
	 * @return <code>true</code> if this employee is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this employee is inactive.
	 *
	 * @return <code>true</code> if this employee is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this employee is incomplete.
	 *
	 * @return <code>true</code> if this employee is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this employee is pending.
	 *
	 * @return <code>true</code> if this employee is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this employee is scheduled.
	 *
	 * @return <code>true</code> if this employee is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Employee employee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Employee> toCacheModel();

	@Override
	public Employee toEscapedModel();

	@Override
	public Employee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}