/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeType service. Represents a row in the &quot;employeeType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.EmployeeTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.EmployeeTypeImpl}.
 * </p>
 *
 * @author Samaresh
 * @see EmployeeType
 * @see com.liferay.famocom.erpcloud.model.impl.EmployeeTypeImpl
 * @see com.liferay.famocom.erpcloud.model.impl.EmployeeTypeModelImpl
 * @generated
 */
@ProviderType
public interface EmployeeTypeModel extends BaseModel<EmployeeType>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee type model instance should use the {@link EmployeeType} interface instead.
	 */

	/**
	 * Returns the primary key of this employee type.
	 *
	 * @return the primary key of this employee type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee type.
	 *
	 * @param primaryKey the primary key of this employee type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employeetype ID of this employee type.
	 *
	 * @return the employeetype ID of this employee type
	 */
	public long getEmployeetypeId();

	/**
	 * Sets the employeetype ID of this employee type.
	 *
	 * @param employeetypeId the employeetype ID of this employee type
	 */
	public void setEmployeetypeId(long employeetypeId);

	/**
	 * Returns the type name of this employee type.
	 *
	 * @return the type name of this employee type
	 */
	@AutoEscape
	public String getTypeName();

	/**
	 * Sets the type name of this employee type.
	 *
	 * @param typeName the type name of this employee type
	 */
	public void setTypeName(String typeName);

	/**
	 * Returns the pf deduct of this employee type.
	 *
	 * @return the pf deduct of this employee type
	 */
	public long getPfDeduct();

	/**
	 * Sets the pf deduct of this employee type.
	 *
	 * @param pfDeduct the pf deduct of this employee type
	 */
	public void setPfDeduct(long pfDeduct);

	/**
	 * Returns the status of this employee type.
	 *
	 * @return the status of this employee type
	 */
	public int getStatus();

	/**
	 * Sets the status of this employee type.
	 *
	 * @param status the status of this employee type
	 */
	public void setStatus(int status);

	/**
	 * Returns the company ID of this employee type.
	 *
	 * @return the company ID of this employee type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee type.
	 *
	 * @param companyId the company ID of this employee type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the addeddate of this employee type.
	 *
	 * @return the addeddate of this employee type
	 */
	public Date getAddeddate();

	/**
	 * Sets the addeddate of this employee type.
	 *
	 * @param addeddate the addeddate of this employee type
	 */
	public void setAddeddate(Date addeddate);

	/**
	 * Returns the description of this employee type.
	 *
	 * @return the description of this employee type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this employee type.
	 *
	 * @param description the description of this employee type
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeType employeeType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeType> toCacheModel();

	@Override
	public EmployeeType toEscapedModel();

	@Override
	public EmployeeType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}