/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeDocumentUpload service. Represents a row in the &quot;employeeDocumentUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.EmployeeDocumentUploadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.EmployeeDocumentUploadImpl}.
 * </p>
 *
 * @author Samaresh
 * @see EmployeeDocumentUpload
 * @see com.liferay.famocom.erpcloud.model.impl.EmployeeDocumentUploadImpl
 * @see com.liferay.famocom.erpcloud.model.impl.EmployeeDocumentUploadModelImpl
 * @generated
 */
@ProviderType
public interface EmployeeDocumentUploadModel extends BaseModel<EmployeeDocumentUpload>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee document upload model instance should use the {@link EmployeeDocumentUpload} interface instead.
	 */

	/**
	 * Returns the primary key of this employee document upload.
	 *
	 * @return the primary key of this employee document upload
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee document upload.
	 *
	 * @param primaryKey the primary key of this employee document upload
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp document ID of this employee document upload.
	 *
	 * @return the emp document ID of this employee document upload
	 */
	public long getEmpDocumentId();

	/**
	 * Sets the emp document ID of this employee document upload.
	 *
	 * @param empDocumentId the emp document ID of this employee document upload
	 */
	public void setEmpDocumentId(long empDocumentId);

	/**
	 * Returns the employee ID of this employee document upload.
	 *
	 * @return the employee ID of this employee document upload
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee document upload.
	 *
	 * @param employeeId the employee ID of this employee document upload
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this employee document upload.
	 *
	 * @return the company ID of this employee document upload
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee document upload.
	 *
	 * @param companyId the company ID of this employee document upload
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the file entry ID of this employee document upload.
	 *
	 * @return the file entry ID of this employee document upload
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this employee document upload.
	 *
	 * @param fileEntryId the file entry ID of this employee document upload
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the travel desk details ID of this employee document upload.
	 *
	 * @return the travel desk details ID of this employee document upload
	 */
	public long getTravelDeskDetailsId();

	/**
	 * Sets the travel desk details ID of this employee document upload.
	 *
	 * @param travelDeskDetailsId the travel desk details ID of this employee document upload
	 */
	public void setTravelDeskDetailsId(long travelDeskDetailsId);

	/**
	 * Returns the document name of this employee document upload.
	 *
	 * @return the document name of this employee document upload
	 */
	@AutoEscape
	public String getDocumentName();

	/**
	 * Sets the document name of this employee document upload.
	 *
	 * @param documentName the document name of this employee document upload
	 */
	public void setDocumentName(String documentName);

	/**
	 * Returns the document path of this employee document upload.
	 *
	 * @return the document path of this employee document upload
	 */
	@AutoEscape
	public String getDocumentPath();

	/**
	 * Sets the document path of this employee document upload.
	 *
	 * @param documentPath the document path of this employee document upload
	 */
	public void setDocumentPath(String documentPath);

	/**
	 * Returns the upload date of this employee document upload.
	 *
	 * @return the upload date of this employee document upload
	 */
	public Date getUploadDate();

	/**
	 * Sets the upload date of this employee document upload.
	 *
	 * @param uploadDate the upload date of this employee document upload
	 */
	public void setUploadDate(Date uploadDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeDocumentUpload employeeDocumentUpload);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeDocumentUpload> toCacheModel();

	@Override
	public EmployeeDocumentUpload toEscapedModel();

	@Override
	public EmployeeDocumentUpload toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}