/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the EmpPayStructure service. Represents a row in the &quot;empPayStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.EmpPayStructureModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.EmpPayStructureImpl}.
 * </p>
 *
 * @author Samaresh
 * @see EmpPayStructure
 * @see com.liferay.famocom.erpcloud.model.impl.EmpPayStructureImpl
 * @see com.liferay.famocom.erpcloud.model.impl.EmpPayStructureModelImpl
 * @generated
 */
@ProviderType
public interface EmpPayStructureModel extends BaseModel<EmpPayStructure> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp pay structure model instance should use the {@link EmpPayStructure} interface instead.
	 */

	/**
	 * Returns the primary key of this emp pay structure.
	 *
	 * @return the primary key of this emp pay structure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp pay structure.
	 *
	 * @param primaryKey the primary key of this emp pay structure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp pay structure ID of this emp pay structure.
	 *
	 * @return the emp pay structure ID of this emp pay structure
	 */
	public long getEmpPayStructureId();

	/**
	 * Sets the emp pay structure ID of this emp pay structure.
	 *
	 * @param empPayStructureId the emp pay structure ID of this emp pay structure
	 */
	public void setEmpPayStructureId(long empPayStructureId);

	/**
	 * Returns the pay component ID of this emp pay structure.
	 *
	 * @return the pay component ID of this emp pay structure
	 */
	public long getPayComponentId();

	/**
	 * Sets the pay component ID of this emp pay structure.
	 *
	 * @param payComponentId the pay component ID of this emp pay structure
	 */
	public void setPayComponentId(long payComponentId);

	/**
	 * Returns the component value of this emp pay structure.
	 *
	 * @return the component value of this emp pay structure
	 */
	public double getComponentValue();

	/**
	 * Sets the component value of this emp pay structure.
	 *
	 * @param componentValue the component value of this emp pay structure
	 */
	public void setComponentValue(double componentValue);

	/**
	 * Returns the employee ID of this emp pay structure.
	 *
	 * @return the employee ID of this emp pay structure
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this emp pay structure.
	 *
	 * @param employeeId the employee ID of this emp pay structure
	 */
	public void setEmployeeId(long employeeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpPayStructure empPayStructure);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpPayStructure> toCacheModel();

	@Override
	public EmpPayStructure toEscapedModel();

	@Override
	public EmpPayStructure toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}