/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ExpCategory service. Represents a row in the &quot;expCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ExpCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ExpCategoryImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ExpCategory
 * @see com.liferay.famocom.erpcloud.model.impl.ExpCategoryImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ExpCategoryModelImpl
 * @generated
 */
@ProviderType
public interface ExpCategoryModel extends BaseModel<ExpCategory>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a exp category model instance should use the {@link ExpCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this exp category.
	 *
	 * @return the primary key of this exp category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this exp category.
	 *
	 * @param primaryKey the primary key of this exp category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cat ID of this exp category.
	 *
	 * @return the cat ID of this exp category
	 */
	public long getCatId();

	/**
	 * Sets the cat ID of this exp category.
	 *
	 * @param catId the cat ID of this exp category
	 */
	public void setCatId(long catId);

	/**
	 * Returns the company ID of this exp category.
	 *
	 * @return the company ID of this exp category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this exp category.
	 *
	 * @param companyId the company ID of this exp category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the category name of this exp category.
	 *
	 * @return the category name of this exp category
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this exp category.
	 *
	 * @param categoryName the category name of this exp category
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the frequency of this exp category.
	 *
	 * @return the frequency of this exp category
	 */
	@AutoEscape
	public String getFrequency();

	/**
	 * Sets the frequency of this exp category.
	 *
	 * @param frequency the frequency of this exp category
	 */
	public void setFrequency(String frequency);

	/**
	 * Returns the salary head of this exp category.
	 *
	 * @return the salary head of this exp category
	 */
	public long getSalaryHead();

	/**
	 * Sets the salary head of this exp category.
	 *
	 * @param salaryHead the salary head of this exp category
	 */
	public void setSalaryHead(long salaryHead);

	/**
	 * Returns the final approval role ID of this exp category.
	 *
	 * @return the final approval role ID of this exp category
	 */
	public long getFinalApprovalRoleId();

	/**
	 * Sets the final approval role ID of this exp category.
	 *
	 * @param finalApprovalRoleId the final approval role ID of this exp category
	 */
	public void setFinalApprovalRoleId(long finalApprovalRoleId);

	/**
	 * Returns the attachment of this exp category.
	 *
	 * @return the attachment of this exp category
	 */
	public boolean getAttachment();

	/**
	 * Returns <code>true</code> if this exp category is attachment.
	 *
	 * @return <code>true</code> if this exp category is attachment; <code>false</code> otherwise
	 */
	public boolean isAttachment();

	/**
	 * Sets whether this exp category is attachment.
	 *
	 * @param attachment the attachment of this exp category
	 */
	public void setAttachment(boolean attachment);

	/**
	 * Returns the component ID of this exp category.
	 *
	 * @return the component ID of this exp category
	 */
	public long getComponentId();

	/**
	 * Sets the component ID of this exp category.
	 *
	 * @param componentId the component ID of this exp category
	 */
	public void setComponentId(long componentId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExpCategory expCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExpCategory> toCacheModel();

	@Override
	public ExpCategory toEscapedModel();

	@Override
	public ExpCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}