/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Expense service. Represents a row in the &quot;Expense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ExpenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ExpenseImpl}.
 * </p>
 *
 * @author Samaresh
 * @see Expense
 * @see com.liferay.famocom.erpcloud.model.impl.ExpenseImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ExpenseModelImpl
 * @generated
 */
@ProviderType
public interface ExpenseModel extends BaseModel<Expense>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expense model instance should use the {@link Expense} interface instead.
	 */

	/**
	 * Returns the primary key of this expense.
	 *
	 * @return the primary key of this expense
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expense.
	 *
	 * @param primaryKey the primary key of this expense
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the expense ID of this expense.
	 *
	 * @return the expense ID of this expense
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this expense.
	 *
	 * @param expenseId the expense ID of this expense
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the employee ID of this expense.
	 *
	 * @return the employee ID of this expense
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this expense.
	 *
	 * @param employeeId the employee ID of this expense
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this expense.
	 *
	 * @return the company ID of this expense
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this expense.
	 *
	 * @param companyId the company ID of this expense
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this expense.
	 *
	 * @return the project ID of this expense
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this expense.
	 *
	 * @param projectId the project ID of this expense
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the cat ID of this expense.
	 *
	 * @return the cat ID of this expense
	 */
	public long getCatId();

	/**
	 * Sets the cat ID of this expense.
	 *
	 * @param catId the cat ID of this expense
	 */
	public void setCatId(long catId);

	/**
	 * Returns the group ID of this expense.
	 *
	 * @return the group ID of this expense
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this expense.
	 *
	 * @param groupId the group ID of this expense
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this expense.
	 *
	 * @return the user ID of this expense
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this expense.
	 *
	 * @param userId the user ID of this expense
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this expense.
	 *
	 * @return the user uuid of this expense
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this expense.
	 *
	 * @param userUuid the user uuid of this expense
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this expense.
	 *
	 * @return the user name of this expense
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this expense.
	 *
	 * @param userName the user name of this expense
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this expense.
	 *
	 * @return the create date of this expense
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this expense.
	 *
	 * @param createDate the create date of this expense
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this expense.
	 *
	 * @return the modified date of this expense
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this expense.
	 *
	 * @param modifiedDate the modified date of this expense
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this expense.
	 *
	 * @return the title of this expense
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this expense.
	 *
	 * @param title the title of this expense
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this expense.
	 *
	 * @return the description of this expense
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this expense.
	 *
	 * @param description the description of this expense
	 */
	public void setDescription(String description);

	/**
	 * Returns the exp date of this expense.
	 *
	 * @return the exp date of this expense
	 */
	public Date getExpDate();

	/**
	 * Sets the exp date of this expense.
	 *
	 * @param expDate the exp date of this expense
	 */
	public void setExpDate(Date expDate);

	/**
	 * Returns the amount of this expense.
	 *
	 * @return the amount of this expense
	 */
	public double getAmount();

	/**
	 * Sets the amount of this expense.
	 *
	 * @param amount the amount of this expense
	 */
	public void setAmount(double amount);

	/**
	 * Returns the status of this expense.
	 *
	 * @return the status of this expense
	 */
	public int getStatus();

	/**
	 * Sets the status of this expense.
	 *
	 * @param status the status of this expense
	 */
	public void setStatus(int status);

	/**
	 * Returns the man employee ID of this expense.
	 *
	 * @return the man employee ID of this expense
	 */
	public long getManEmployeeId();

	/**
	 * Sets the man employee ID of this expense.
	 *
	 * @param manEmployeeId the man employee ID of this expense
	 */
	public void setManEmployeeId(long manEmployeeId);

	/**
	 * Returns the man commnets of this expense.
	 *
	 * @return the man commnets of this expense
	 */
	@AutoEscape
	public String getManCommnets();

	/**
	 * Sets the man commnets of this expense.
	 *
	 * @param manCommnets the man commnets of this expense
	 */
	public void setManCommnets(String manCommnets);

	/**
	 * Returns the man approved date of this expense.
	 *
	 * @return the man approved date of this expense
	 */
	public Date getManApprovedDate();

	/**
	 * Sets the man approved date of this expense.
	 *
	 * @param manApprovedDate the man approved date of this expense
	 */
	public void setManApprovedDate(Date manApprovedDate);

	/**
	 * Returns the acc comments of this expense.
	 *
	 * @return the acc comments of this expense
	 */
	@AutoEscape
	public String getAccComments();

	/**
	 * Sets the acc comments of this expense.
	 *
	 * @param accComments the acc comments of this expense
	 */
	public void setAccComments(String accComments);

	/**
	 * Returns the acc approved date of this expense.
	 *
	 * @return the acc approved date of this expense
	 */
	public Date getAccApprovedDate();

	/**
	 * Sets the acc approved date of this expense.
	 *
	 * @param accApprovedDate the acc approved date of this expense
	 */
	public void setAccApprovedDate(Date accApprovedDate);

	/**
	 * Returns the month year of this expense.
	 *
	 * @return the month year of this expense
	 */
	public long getMonthYear();

	/**
	 * Sets the month year of this expense.
	 *
	 * @param monthYear the month year of this expense
	 */
	public void setMonthYear(long monthYear);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Expense expense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Expense> toCacheModel();

	@Override
	public Expense toEscapedModel();

	@Override
	public Expense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}