/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExpenseEntryHistory service. Represents a row in the &quot;expenseEntryHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ExpenseEntryHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ExpenseEntryHistoryImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ExpenseEntryHistory
 * @see com.liferay.famocom.erpcloud.model.impl.ExpenseEntryHistoryImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ExpenseEntryHistoryModelImpl
 * @generated
 */
@ProviderType
public interface ExpenseEntryHistoryModel extends BaseModel<ExpenseEntryHistory>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expense entry history model instance should use the {@link ExpenseEntryHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this expense entry history.
	 *
	 * @return the primary key of this expense entry history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expense entry history.
	 *
	 * @param primaryKey the primary key of this expense entry history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the expense history ID of this expense entry history.
	 *
	 * @return the expense history ID of this expense entry history
	 */
	public long getExpenseHistoryId();

	/**
	 * Sets the expense history ID of this expense entry history.
	 *
	 * @param expenseHistoryId the expense history ID of this expense entry history
	 */
	public void setExpenseHistoryId(long expenseHistoryId);

	/**
	 * Returns the company ID of this expense entry history.
	 *
	 * @return the company ID of this expense entry history
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this expense entry history.
	 *
	 * @param companyId the company ID of this expense entry history
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the expense ID of this expense entry history.
	 *
	 * @return the expense ID of this expense entry history
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this expense entry history.
	 *
	 * @param expenseId the expense ID of this expense entry history
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the status of this expense entry history.
	 *
	 * @return the status of this expense entry history
	 */
	public int getStatus();

	/**
	 * Sets the status of this expense entry history.
	 *
	 * @param status the status of this expense entry history
	 */
	public void setStatus(int status);

	/**
	 * Returns the man employee ID of this expense entry history.
	 *
	 * @return the man employee ID of this expense entry history
	 */
	public long getManEmployeeId();

	/**
	 * Sets the man employee ID of this expense entry history.
	 *
	 * @param manEmployeeId the man employee ID of this expense entry history
	 */
	public void setManEmployeeId(long manEmployeeId);

	/**
	 * Returns the man comments of this expense entry history.
	 *
	 * @return the man comments of this expense entry history
	 */
	@AutoEscape
	public String getManComments();

	/**
	 * Sets the man comments of this expense entry history.
	 *
	 * @param manComments the man comments of this expense entry history
	 */
	public void setManComments(String manComments);

	/**
	 * Returns the addeddate of this expense entry history.
	 *
	 * @return the addeddate of this expense entry history
	 */
	public Date getAddeddate();

	/**
	 * Sets the addeddate of this expense entry history.
	 *
	 * @param addeddate the addeddate of this expense entry history
	 */
	public void setAddeddate(Date addeddate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExpenseEntryHistory expenseEntryHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExpenseEntryHistory> toCacheModel();

	@Override
	public ExpenseEntryHistory toEscapedModel();

	@Override
	public ExpenseEntryHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}