/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExpProofFiles service. Represents a row in the &quot;expProofFiles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ExpProofFilesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ExpProofFilesImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ExpProofFiles
 * @see com.liferay.famocom.erpcloud.model.impl.ExpProofFilesImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ExpProofFilesModelImpl
 * @generated
 */
@ProviderType
public interface ExpProofFilesModel extends BaseModel<ExpProofFiles>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a exp proof files model instance should use the {@link ExpProofFiles} interface instead.
	 */

	/**
	 * Returns the primary key of this exp proof files.
	 *
	 * @return the primary key of this exp proof files
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this exp proof files.
	 *
	 * @param primaryKey the primary key of this exp proof files
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the file ID of this exp proof files.
	 *
	 * @return the file ID of this exp proof files
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this exp proof files.
	 *
	 * @param fileId the file ID of this exp proof files
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the financial year of this exp proof files.
	 *
	 * @return the financial year of this exp proof files
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this exp proof files.
	 *
	 * @param financialYear the financial year of this exp proof files
	 */
	public void setFinancialYear(String financialYear);

	/**
	 * Returns the company ID of this exp proof files.
	 *
	 * @return the company ID of this exp proof files
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this exp proof files.
	 *
	 * @param companyId the company ID of this exp proof files
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee ID of this exp proof files.
	 *
	 * @return the employee ID of this exp proof files
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this exp proof files.
	 *
	 * @param employeeId the employee ID of this exp proof files
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the expense ID of this exp proof files.
	 *
	 * @return the expense ID of this exp proof files
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this exp proof files.
	 *
	 * @param expenseId the expense ID of this exp proof files
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the file name of this exp proof files.
	 *
	 * @return the file name of this exp proof files
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this exp proof files.
	 *
	 * @param fileName the file name of this exp proof files
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the file orig name of this exp proof files.
	 *
	 * @return the file orig name of this exp proof files
	 */
	@AutoEscape
	public String getFileOrigName();

	/**
	 * Sets the file orig name of this exp proof files.
	 *
	 * @param fileOrigName the file orig name of this exp proof files
	 */
	public void setFileOrigName(String fileOrigName);

	/**
	 * Returns the file path of this exp proof files.
	 *
	 * @return the file path of this exp proof files
	 */
	@AutoEscape
	public String getFilePath();

	/**
	 * Sets the file path of this exp proof files.
	 *
	 * @param filePath the file path of this exp proof files
	 */
	public void setFilePath(String filePath);

	/**
	 * Returns the proof name of this exp proof files.
	 *
	 * @return the proof name of this exp proof files
	 */
	@AutoEscape
	public String getProofName();

	/**
	 * Sets the proof name of this exp proof files.
	 *
	 * @param proofName the proof name of this exp proof files
	 */
	public void setProofName(String proofName);

	/**
	 * Returns the upload date of this exp proof files.
	 *
	 * @return the upload date of this exp proof files
	 */
	public Date getUploadDate();

	/**
	 * Sets the upload date of this exp proof files.
	 *
	 * @param uploadDate the upload date of this exp proof files
	 */
	public void setUploadDate(Date uploadDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExpProofFiles expProofFiles);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExpProofFiles> toCacheModel();

	@Override
	public ExpProofFiles toEscapedModel();

	@Override
	public ExpProofFiles toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}