/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FinSalary service. Represents a row in the &quot;finalSalary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.FinSalaryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.FinSalaryImpl}.
 * </p>
 *
 * @author Samaresh
 * @see FinSalary
 * @see com.liferay.famocom.erpcloud.model.impl.FinSalaryImpl
 * @see com.liferay.famocom.erpcloud.model.impl.FinSalaryModelImpl
 * @generated
 */
@ProviderType
public interface FinSalaryModel extends BaseModel<FinSalary> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fin salary model instance should use the {@link FinSalary} interface instead.
	 */

	/**
	 * Returns the primary key of this fin salary.
	 *
	 * @return the primary key of this fin salary
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fin salary.
	 *
	 * @param primaryKey the primary key of this fin salary
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fin salary ID of this fin salary.
	 *
	 * @return the fin salary ID of this fin salary
	 */
	public long getFinSalaryId();

	/**
	 * Sets the fin salary ID of this fin salary.
	 *
	 * @param finSalaryId the fin salary ID of this fin salary
	 */
	public void setFinSalaryId(long finSalaryId);

	/**
	 * Returns the month year of this fin salary.
	 *
	 * @return the month year of this fin salary
	 */
	public long getMonthYear();

	/**
	 * Sets the month year of this fin salary.
	 *
	 * @param monthYear the month year of this fin salary
	 */
	public void setMonthYear(long monthYear);

	/**
	 * Returns the total earning of this fin salary.
	 *
	 * @return the total earning of this fin salary
	 */
	public double getTotalEarning();

	/**
	 * Sets the total earning of this fin salary.
	 *
	 * @param totalEarning the total earning of this fin salary
	 */
	public void setTotalEarning(double totalEarning);

	/**
	 * Returns the total deduction of this fin salary.
	 *
	 * @return the total deduction of this fin salary
	 */
	public double getTotalDeduction();

	/**
	 * Sets the total deduction of this fin salary.
	 *
	 * @param totalDeduction the total deduction of this fin salary
	 */
	public void setTotalDeduction(double totalDeduction);

	/**
	 * Returns the total amount of this fin salary.
	 *
	 * @return the total amount of this fin salary
	 */
	public double getTotalAmount();

	/**
	 * Sets the total amount of this fin salary.
	 *
	 * @param totalAmount the total amount of this fin salary
	 */
	public void setTotalAmount(double totalAmount);

	/**
	 * Returns the is lock of this fin salary.
	 *
	 * @return the is lock of this fin salary
	 */
	public long getIsLock();

	/**
	 * Sets the is lock of this fin salary.
	 *
	 * @param isLock the is lock of this fin salary
	 */
	public void setIsLock(long isLock);

	/**
	 * Returns the created by of this fin salary.
	 *
	 * @return the created by of this fin salary
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this fin salary.
	 *
	 * @param createdBy the created by of this fin salary
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the created date of this fin salary.
	 *
	 * @return the created date of this fin salary
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this fin salary.
	 *
	 * @param createdDate the created date of this fin salary
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FinSalary finSalary);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FinSalary> toCacheModel();

	@Override
	public FinSalary toEscapedModel();

	@Override
	public FinSalary toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}