/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the FormSixteenErrorFile service. Represents a row in the &quot;FormSixteenErrorFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.FormSixteenErrorFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.FormSixteenErrorFileImpl}.
 * </p>
 *
 * @author Samaresh
 * @see FormSixteenErrorFile
 * @see com.liferay.famocom.erpcloud.model.impl.FormSixteenErrorFileImpl
 * @see com.liferay.famocom.erpcloud.model.impl.FormSixteenErrorFileModelImpl
 * @generated
 */
@ProviderType
public interface FormSixteenErrorFileModel extends BaseModel<FormSixteenErrorFile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form sixteen error file model instance should use the {@link FormSixteenErrorFile} interface instead.
	 */

	/**
	 * Returns the primary key of this form sixteen error file.
	 *
	 * @return the primary key of this form sixteen error file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form sixteen error file.
	 *
	 * @param primaryKey the primary key of this form sixteen error file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the error ID of this form sixteen error file.
	 *
	 * @return the error ID of this form sixteen error file
	 */
	public long getErrorId();

	/**
	 * Sets the error ID of this form sixteen error file.
	 *
	 * @param errorId the error ID of this form sixteen error file
	 */
	public void setErrorId(long errorId);

	/**
	 * Returns the file name of this form sixteen error file.
	 *
	 * @return the file name of this form sixteen error file
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this form sixteen error file.
	 *
	 * @param fileName the file name of this form sixteen error file
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the error msg of this form sixteen error file.
	 *
	 * @return the error msg of this form sixteen error file
	 */
	@AutoEscape
	public String getErrorMsg();

	/**
	 * Sets the error msg of this form sixteen error file.
	 *
	 * @param errorMsg the error msg of this form sixteen error file
	 */
	public void setErrorMsg(String errorMsg);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FormSixteenErrorFile formSixteenErrorFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FormSixteenErrorFile> toCacheModel();

	@Override
	public FormSixteenErrorFile toEscapedModel();

	@Override
	public FormSixteenErrorFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}