/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FormSixteen service. Represents a row in the &quot;FormSixteen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.FormSixteenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.FormSixteenImpl}.
 * </p>
 *
 * @author Samaresh
 * @see FormSixteen
 * @see com.liferay.famocom.erpcloud.model.impl.FormSixteenImpl
 * @see com.liferay.famocom.erpcloud.model.impl.FormSixteenModelImpl
 * @generated
 */
@ProviderType
public interface FormSixteenModel extends BaseModel<FormSixteen> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form sixteen model instance should use the {@link FormSixteen} interface instead.
	 */

	/**
	 * Returns the primary key of this form sixteen.
	 *
	 * @return the primary key of this form sixteen
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form sixteen.
	 *
	 * @param primaryKey the primary key of this form sixteen
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this form sixteen.
	 *
	 * @return the ID of this form sixteen
	 */
	public long getId();

	/**
	 * Sets the ID of this form sixteen.
	 *
	 * @param id the ID of this form sixteen
	 */
	public void setId(long id);

	/**
	 * Returns the employee ID of this form sixteen.
	 *
	 * @return the employee ID of this form sixteen
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this form sixteen.
	 *
	 * @param employeeId the employee ID of this form sixteen
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the financial year of this form sixteen.
	 *
	 * @return the financial year of this form sixteen
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this form sixteen.
	 *
	 * @param financialYear the financial year of this form sixteen
	 */
	public void setFinancialYear(String financialYear);

	/**
	 * Returns the file entery ID of this form sixteen.
	 *
	 * @return the file entery ID of this form sixteen
	 */
	public long getFileEnteryId();

	/**
	 * Sets the file entery ID of this form sixteen.
	 *
	 * @param fileEnteryId the file entery ID of this form sixteen
	 */
	public void setFileEnteryId(long fileEnteryId);

	/**
	 * Returns the added date of this form sixteen.
	 *
	 * @return the added date of this form sixteen
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this form sixteen.
	 *
	 * @param addedDate the added date of this form sixteen
	 */
	public void setAddedDate(Date addedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FormSixteen formSixteen);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FormSixteen> toCacheModel();

	@Override
	public FormSixteen toEscapedModel();

	@Override
	public FormSixteen toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}