/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GeoAttendance service. Represents a row in the &quot;geoAttendance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.GeoAttendanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.GeoAttendanceImpl}.
 * </p>
 *
 * @author Samaresh
 * @see GeoAttendance
 * @see com.liferay.famocom.erpcloud.model.impl.GeoAttendanceImpl
 * @see com.liferay.famocom.erpcloud.model.impl.GeoAttendanceModelImpl
 * @generated
 */
@ProviderType
public interface GeoAttendanceModel extends BaseModel<GeoAttendance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a geo attendance model instance should use the {@link GeoAttendance} interface instead.
	 */

	/**
	 * Returns the primary key of this geo attendance.
	 *
	 * @return the primary key of this geo attendance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this geo attendance.
	 *
	 * @param primaryKey the primary key of this geo attendance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the attendance ID of this geo attendance.
	 *
	 * @return the attendance ID of this geo attendance
	 */
	public long getAttendanceId();

	/**
	 * Sets the attendance ID of this geo attendance.
	 *
	 * @param attendanceId the attendance ID of this geo attendance
	 */
	public void setAttendanceId(long attendanceId);

	/**
	 * Returns the employee ID of this geo attendance.
	 *
	 * @return the employee ID of this geo attendance
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this geo attendance.
	 *
	 * @param employeeId the employee ID of this geo attendance
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the att date of this geo attendance.
	 *
	 * @return the att date of this geo attendance
	 */
	public Date getAttDate();

	/**
	 * Sets the att date of this geo attendance.
	 *
	 * @param attDate the att date of this geo attendance
	 */
	public void setAttDate(Date attDate);

	/**
	 * Returns the in time of this geo attendance.
	 *
	 * @return the in time of this geo attendance
	 */
	@AutoEscape
	public String getInTime();

	/**
	 * Sets the in time of this geo attendance.
	 *
	 * @param inTime the in time of this geo attendance
	 */
	public void setInTime(String inTime);

	/**
	 * Returns the out time of this geo attendance.
	 *
	 * @return the out time of this geo attendance
	 */
	@AutoEscape
	public String getOutTime();

	/**
	 * Sets the out time of this geo attendance.
	 *
	 * @param outTime the out time of this geo attendance
	 */
	public void setOutTime(String outTime);

	/**
	 * Returns the work hour of this geo attendance.
	 *
	 * @return the work hour of this geo attendance
	 */
	@AutoEscape
	public String getWorkHour();

	/**
	 * Sets the work hour of this geo attendance.
	 *
	 * @param workHour the work hour of this geo attendance
	 */
	public void setWorkHour(String workHour);

	/**
	 * Returns the latitude of this geo attendance.
	 *
	 * @return the latitude of this geo attendance
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this geo attendance.
	 *
	 * @param latitude the latitude of this geo attendance
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the longitude of this geo attendance.
	 *
	 * @return the longitude of this geo attendance
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this geo attendance.
	 *
	 * @param longitude the longitude of this geo attendance
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the out latitude of this geo attendance.
	 *
	 * @return the out latitude of this geo attendance
	 */
	@AutoEscape
	public String getOutLatitude();

	/**
	 * Sets the out latitude of this geo attendance.
	 *
	 * @param outLatitude the out latitude of this geo attendance
	 */
	public void setOutLatitude(String outLatitude);

	/**
	 * Returns the out longitude of this geo attendance.
	 *
	 * @return the out longitude of this geo attendance
	 */
	@AutoEscape
	public String getOutLongitude();

	/**
	 * Sets the out longitude of this geo attendance.
	 *
	 * @param outLongitude the out longitude of this geo attendance
	 */
	public void setOutLongitude(String outLongitude);

	/**
	 * Returns the geo address of this geo attendance.
	 *
	 * @return the geo address of this geo attendance
	 */
	@AutoEscape
	public String getGeoAddress();

	/**
	 * Sets the geo address of this geo attendance.
	 *
	 * @param geoAddress the geo address of this geo attendance
	 */
	public void setGeoAddress(String geoAddress);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GeoAttendance geoAttendance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GeoAttendance> toCacheModel();

	@Override
	public GeoAttendance toEscapedModel();

	@Override
	public GeoAttendance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}