/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GoalMaster service. Represents a row in the &quot;goalMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.GoalMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.GoalMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see GoalMaster
 * @see com.liferay.famocom.erpcloud.model.impl.GoalMasterImpl
 * @see com.liferay.famocom.erpcloud.model.impl.GoalMasterModelImpl
 * @generated
 */
@ProviderType
public interface GoalMasterModel extends BaseModel<GoalMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a goal master model instance should use the {@link GoalMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this goal master.
	 *
	 * @return the primary key of this goal master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this goal master.
	 *
	 * @param primaryKey the primary key of this goal master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the goal ID of this goal master.
	 *
	 * @return the goal ID of this goal master
	 */
	public long getGoalId();

	/**
	 * Sets the goal ID of this goal master.
	 *
	 * @param goalId the goal ID of this goal master
	 */
	public void setGoalId(long goalId);

	/**
	 * Returns the employee ID of this goal master.
	 *
	 * @return the employee ID of this goal master
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this goal master.
	 *
	 * @param employeeId the employee ID of this goal master
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the project ID of this goal master.
	 *
	 * @return the project ID of this goal master
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this goal master.
	 *
	 * @param projectId the project ID of this goal master
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the goal name of this goal master.
	 *
	 * @return the goal name of this goal master
	 */
	@AutoEscape
	public String getGoalName();

	/**
	 * Sets the goal name of this goal master.
	 *
	 * @param goalName the goal name of this goal master
	 */
	public void setGoalName(String goalName);

	/**
	 * Returns the goal description of this goal master.
	 *
	 * @return the goal description of this goal master
	 */
	@AutoEscape
	public String getGoalDescription();

	/**
	 * Sets the goal description of this goal master.
	 *
	 * @param goalDescription the goal description of this goal master
	 */
	public void setGoalDescription(String goalDescription);

	/**
	 * Returns the added date of this goal master.
	 *
	 * @return the added date of this goal master
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this goal master.
	 *
	 * @param addedDate the added date of this goal master
	 */
	public void setAddedDate(Date addedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GoalMaster goalMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GoalMaster> toCacheModel();

	@Override
	public GoalMaster toEscapedModel();

	@Override
	public GoalMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}