/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HolidayCalenderManagement service. Represents a row in the &quot;holidayCalenderManagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.HolidayCalenderManagementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.HolidayCalenderManagementImpl}.
 * </p>
 *
 * @author Samaresh
 * @see HolidayCalenderManagement
 * @see com.liferay.famocom.erpcloud.model.impl.HolidayCalenderManagementImpl
 * @see com.liferay.famocom.erpcloud.model.impl.HolidayCalenderManagementModelImpl
 * @generated
 */
@ProviderType
public interface HolidayCalenderManagementModel extends BaseModel<HolidayCalenderManagement>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a holiday calender management model instance should use the {@link HolidayCalenderManagement} interface instead.
	 */

	/**
	 * Returns the primary key of this holiday calender management.
	 *
	 * @return the primary key of this holiday calender management
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this holiday calender management.
	 *
	 * @param primaryKey the primary key of this holiday calender management
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the holiday ID of this holiday calender management.
	 *
	 * @return the holiday ID of this holiday calender management
	 */
	public long getHolidayId();

	/**
	 * Sets the holiday ID of this holiday calender management.
	 *
	 * @param holidayId the holiday ID of this holiday calender management
	 */
	public void setHolidayId(long holidayId);

	/**
	 * Returns the holiday date of this holiday calender management.
	 *
	 * @return the holiday date of this holiday calender management
	 */
	public Date getHolidayDate();

	/**
	 * Sets the holiday date of this holiday calender management.
	 *
	 * @param holidayDate the holiday date of this holiday calender management
	 */
	public void setHolidayDate(Date holidayDate);

	/**
	 * Returns the holiday name of this holiday calender management.
	 *
	 * @return the holiday name of this holiday calender management
	 */
	@AutoEscape
	public String getHolidayName();

	/**
	 * Sets the holiday name of this holiday calender management.
	 *
	 * @param holidayName the holiday name of this holiday calender management
	 */
	public void setHolidayName(String holidayName);

	/**
	 * Returns the holiday start date of this holiday calender management.
	 *
	 * @return the holiday start date of this holiday calender management
	 */
	public Date getHolidayStartDate();

	/**
	 * Sets the holiday start date of this holiday calender management.
	 *
	 * @param holidayStartDate the holiday start date of this holiday calender management
	 */
	public void setHolidayStartDate(Date holidayStartDate);

	/**
	 * Returns the holiday end date of this holiday calender management.
	 *
	 * @return the holiday end date of this holiday calender management
	 */
	public Date getHolidayEndDate();

	/**
	 * Sets the holiday end date of this holiday calender management.
	 *
	 * @param holidayEndDate the holiday end date of this holiday calender management
	 */
	public void setHolidayEndDate(Date holidayEndDate);

	/**
	 * Returns the company ID of this holiday calender management.
	 *
	 * @return the company ID of this holiday calender management
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this holiday calender management.
	 *
	 * @param companyId the company ID of this holiday calender management
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HolidayCalenderManagement holidayCalenderManagement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HolidayCalenderManagement> toCacheModel();

	@Override
	public HolidayCalenderManagement toEscapedModel();

	@Override
	public HolidayCalenderManagement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}