/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the IncomeTaxSlab service. Represents a row in the &quot;incomeTaxSlab&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.IncomeTaxSlabModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.IncomeTaxSlabImpl}.
 * </p>
 *
 * @author Samaresh
 * @see IncomeTaxSlab
 * @see com.liferay.famocom.erpcloud.model.impl.IncomeTaxSlabImpl
 * @see com.liferay.famocom.erpcloud.model.impl.IncomeTaxSlabModelImpl
 * @generated
 */
@ProviderType
public interface IncomeTaxSlabModel extends BaseModel<IncomeTaxSlab>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a income tax slab model instance should use the {@link IncomeTaxSlab} interface instead.
	 */

	/**
	 * Returns the primary key of this income tax slab.
	 *
	 * @return the primary key of this income tax slab
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this income tax slab.
	 *
	 * @param primaryKey the primary key of this income tax slab
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the income tax slab ID of this income tax slab.
	 *
	 * @return the income tax slab ID of this income tax slab
	 */
	public long getIncomeTaxSlabId();

	/**
	 * Sets the income tax slab ID of this income tax slab.
	 *
	 * @param incomeTaxSlabId the income tax slab ID of this income tax slab
	 */
	public void setIncomeTaxSlabId(long incomeTaxSlabId);

	/**
	 * Returns the financial year of this income tax slab.
	 *
	 * @return the financial year of this income tax slab
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this income tax slab.
	 *
	 * @param financialYear the financial year of this income tax slab
	 */
	public void setFinancialYear(String financialYear);

	/**
	 * Returns the company ID of this income tax slab.
	 *
	 * @return the company ID of this income tax slab
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this income tax slab.
	 *
	 * @param companyId the company ID of this income tax slab
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the income from of this income tax slab.
	 *
	 * @return the income from of this income tax slab
	 */
	public int getIncomeFrom();

	/**
	 * Sets the income from of this income tax slab.
	 *
	 * @param incomeFrom the income from of this income tax slab
	 */
	public void setIncomeFrom(int incomeFrom);

	/**
	 * Returns the income to of this income tax slab.
	 *
	 * @return the income to of this income tax slab
	 */
	public int getIncomeTo();

	/**
	 * Sets the income to of this income tax slab.
	 *
	 * @param incomeTo the income to of this income tax slab
	 */
	public void setIncomeTo(int incomeTo);

	/**
	 * Returns the tax rate of this income tax slab.
	 *
	 * @return the tax rate of this income tax slab
	 */
	public double getTaxRate();

	/**
	 * Sets the tax rate of this income tax slab.
	 *
	 * @param taxRate the tax rate of this income tax slab
	 */
	public void setTaxRate(double taxRate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(IncomeTaxSlab incomeTaxSlab);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IncomeTaxSlab> toCacheModel();

	@Override
	public IncomeTaxSlab toEscapedModel();

	@Override
	public IncomeTaxSlab toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}