/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobPost service. Represents a row in the &quot;JobPost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.JobPostModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.JobPostImpl}.
 * </p>
 *
 * @author Samaresh
 * @see JobPost
 * @see com.liferay.famocom.erpcloud.model.impl.JobPostImpl
 * @see com.liferay.famocom.erpcloud.model.impl.JobPostModelImpl
 * @generated
 */
@ProviderType
public interface JobPostModel extends BaseModel<JobPost> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job post model instance should use the {@link JobPost} interface instead.
	 */

	/**
	 * Returns the primary key of this job post.
	 *
	 * @return the primary key of this job post
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job post.
	 *
	 * @param primaryKey the primary key of this job post
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job post ID of this job post.
	 *
	 * @return the job post ID of this job post
	 */
	public long getJobPostId();

	/**
	 * Sets the job post ID of this job post.
	 *
	 * @param jobPostId the job post ID of this job post
	 */
	public void setJobPostId(long jobPostId);

	/**
	 * Returns the post name of this job post.
	 *
	 * @return the post name of this job post
	 */
	@AutoEscape
	public String getPostName();

	/**
	 * Sets the post name of this job post.
	 *
	 * @param postName the post name of this job post
	 */
	public void setPostName(String postName);

	/**
	 * Returns the post description of this job post.
	 *
	 * @return the post description of this job post
	 */
	@AutoEscape
	public String getPostDescription();

	/**
	 * Sets the post description of this job post.
	 *
	 * @param postDescription the post description of this job post
	 */
	public void setPostDescription(String postDescription);

	/**
	 * Returns the created date of this job post.
	 *
	 * @return the created date of this job post
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this job post.
	 *
	 * @param createdDate the created date of this job post
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this job post.
	 *
	 * @return the modified date of this job post
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job post.
	 *
	 * @param modifiedDate the modified date of this job post
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobPost jobPost);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobPost> toCacheModel();

	@Override
	public JobPost toEscapedModel();

	@Override
	public JobPost toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}