/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LeaveOb service. Represents a row in the &quot;leaveOb&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.LeaveObModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.LeaveObImpl}.
 * </p>
 *
 * @author Samaresh
 * @see LeaveOb
 * @see com.liferay.famocom.erpcloud.model.impl.LeaveObImpl
 * @see com.liferay.famocom.erpcloud.model.impl.LeaveObModelImpl
 * @generated
 */
@ProviderType
public interface LeaveObModel extends BaseModel<LeaveOb> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave ob model instance should use the {@link LeaveOb} interface instead.
	 */

	/**
	 * Returns the primary key of this leave ob.
	 *
	 * @return the primary key of this leave ob
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave ob.
	 *
	 * @param primaryKey the primary key of this leave ob
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the leaveob ID of this leave ob.
	 *
	 * @return the leaveob ID of this leave ob
	 */
	public long getLeaveobId();

	/**
	 * Sets the leaveob ID of this leave ob.
	 *
	 * @param leaveobId the leaveob ID of this leave ob
	 */
	public void setLeaveobId(long leaveobId);

	/**
	 * Returns the employee ID of this leave ob.
	 *
	 * @return the employee ID of this leave ob
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this leave ob.
	 *
	 * @param employeeId the employee ID of this leave ob
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the leave type ID of this leave ob.
	 *
	 * @return the leave type ID of this leave ob
	 */
	public long getLeaveTypeId();

	/**
	 * Sets the leave type ID of this leave ob.
	 *
	 * @param leaveTypeId the leave type ID of this leave ob
	 */
	public void setLeaveTypeId(long leaveTypeId);

	/**
	 * Returns the ob val of this leave ob.
	 *
	 * @return the ob val of this leave ob
	 */
	public int getObVal();

	/**
	 * Sets the ob val of this leave ob.
	 *
	 * @param obVal the ob val of this leave ob
	 */
	public void setObVal(int obVal);

	/**
	 * Returns the is approve of this leave ob.
	 *
	 * @return the is approve of this leave ob
	 */
	public boolean getIsApprove();

	/**
	 * Returns <code>true</code> if this leave ob is is approve.
	 *
	 * @return <code>true</code> if this leave ob is is approve; <code>false</code> otherwise
	 */
	public boolean isIsApprove();

	/**
	 * Sets whether this leave ob is is approve.
	 *
	 * @param isApprove the is approve of this leave ob
	 */
	public void setIsApprove(boolean isApprove);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LeaveOb leaveOb);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LeaveOb> toCacheModel();

	@Override
	public LeaveOb toEscapedModel();

	@Override
	public LeaveOb toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}