/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Milestone service. Represents a row in the &quot;Milestone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.MilestoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.MilestoneImpl}.
 * </p>
 *
 * @author Samaresh
 * @see Milestone
 * @see com.liferay.famocom.erpcloud.model.impl.MilestoneImpl
 * @see com.liferay.famocom.erpcloud.model.impl.MilestoneModelImpl
 * @generated
 */
@ProviderType
public interface MilestoneModel extends BaseModel<Milestone> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a milestone model instance should use the {@link Milestone} interface instead.
	 */

	/**
	 * Returns the primary key of this milestone.
	 *
	 * @return the primary key of this milestone
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this milestone.
	 *
	 * @param primaryKey the primary key of this milestone
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the milestone ID of this milestone.
	 *
	 * @return the milestone ID of this milestone
	 */
	public long getMilestoneId();

	/**
	 * Sets the milestone ID of this milestone.
	 *
	 * @param milestoneId the milestone ID of this milestone
	 */
	public void setMilestoneId(long milestoneId);

	/**
	 * Returns the project ID of this milestone.
	 *
	 * @return the project ID of this milestone
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this milestone.
	 *
	 * @param projectId the project ID of this milestone
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the client ID of this milestone.
	 *
	 * @return the client ID of this milestone
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this milestone.
	 *
	 * @param clientId the client ID of this milestone
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the milestone name of this milestone.
	 *
	 * @return the milestone name of this milestone
	 */
	@AutoEscape
	public String getMilestoneName();

	/**
	 * Sets the milestone name of this milestone.
	 *
	 * @param milestoneName the milestone name of this milestone
	 */
	public void setMilestoneName(String milestoneName);

	/**
	 * Returns the due date of this milestone.
	 *
	 * @return the due date of this milestone
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this milestone.
	 *
	 * @param dueDate the due date of this milestone
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the check gst of this milestone.
	 *
	 * @return the check gst of this milestone
	 */
	public int getCheckGST();

	/**
	 * Sets the check gst of this milestone.
	 *
	 * @param checkGST the check gst of this milestone
	 */
	public void setCheckGST(int checkGST);

	/**
	 * Returns the amount of this milestone.
	 *
	 * @return the amount of this milestone
	 */
	public double getAmount();

	/**
	 * Sets the amount of this milestone.
	 *
	 * @param amount the amount of this milestone
	 */
	public void setAmount(double amount);

	/**
	 * Returns the status of this milestone.
	 *
	 * @return the status of this milestone
	 */
	public int getStatus();

	/**
	 * Sets the status of this milestone.
	 *
	 * @param status the status of this milestone
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Milestone milestone);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Milestone> toCacheModel();

	@Override
	public Milestone toEscapedModel();

	@Override
	public Milestone toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}