/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the MonthlyAdjustment service. Represents a row in the &quot;MonthlyAdjustment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.MonthlyAdjustmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.MonthlyAdjustmentImpl}.
 * </p>
 *
 * @author Samaresh
 * @see MonthlyAdjustment
 * @see com.liferay.famocom.erpcloud.model.impl.MonthlyAdjustmentImpl
 * @see com.liferay.famocom.erpcloud.model.impl.MonthlyAdjustmentModelImpl
 * @generated
 */
@ProviderType
public interface MonthlyAdjustmentModel extends BaseModel<MonthlyAdjustment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a monthly adjustment model instance should use the {@link MonthlyAdjustment} interface instead.
	 */

	/**
	 * Returns the primary key of this monthly adjustment.
	 *
	 * @return the primary key of this monthly adjustment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this monthly adjustment.
	 *
	 * @param primaryKey the primary key of this monthly adjustment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the monthly adjustment ID of this monthly adjustment.
	 *
	 * @return the monthly adjustment ID of this monthly adjustment
	 */
	public long getMonthlyAdjustmentId();

	/**
	 * Sets the monthly adjustment ID of this monthly adjustment.
	 *
	 * @param monthlyAdjustmentId the monthly adjustment ID of this monthly adjustment
	 */
	public void setMonthlyAdjustmentId(long monthlyAdjustmentId);

	/**
	 * Returns the pay component ID of this monthly adjustment.
	 *
	 * @return the pay component ID of this monthly adjustment
	 */
	public long getPayComponentId();

	/**
	 * Sets the pay component ID of this monthly adjustment.
	 *
	 * @param payComponentId the pay component ID of this monthly adjustment
	 */
	public void setPayComponentId(long payComponentId);

	/**
	 * Returns the amount of this monthly adjustment.
	 *
	 * @return the amount of this monthly adjustment
	 */
	public double getAmount();

	/**
	 * Sets the amount of this monthly adjustment.
	 *
	 * @param amount the amount of this monthly adjustment
	 */
	public void setAmount(double amount);

	/**
	 * Returns the month year of this monthly adjustment.
	 *
	 * @return the month year of this monthly adjustment
	 */
	public long getMonthYear();

	/**
	 * Sets the month year of this monthly adjustment.
	 *
	 * @param monthYear the month year of this monthly adjustment
	 */
	public void setMonthYear(long monthYear);

	/**
	 * Returns the employee ID of this monthly adjustment.
	 *
	 * @return the employee ID of this monthly adjustment
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this monthly adjustment.
	 *
	 * @param employeeId the employee ID of this monthly adjustment
	 */
	public void setEmployeeId(long employeeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MonthlyAdjustment monthlyAdjustment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MonthlyAdjustment> toCacheModel();

	@Override
	public MonthlyAdjustment toEscapedModel();

	@Override
	public MonthlyAdjustment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}