/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PayComponent service. Represents a row in the &quot;PayComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.PayComponentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.PayComponentImpl}.
 * </p>
 *
 * @author Samaresh
 * @see PayComponent
 * @see com.liferay.famocom.erpcloud.model.impl.PayComponentImpl
 * @see com.liferay.famocom.erpcloud.model.impl.PayComponentModelImpl
 * @generated
 */
@ProviderType
public interface PayComponentModel extends BaseModel<PayComponent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pay component model instance should use the {@link PayComponent} interface instead.
	 */

	/**
	 * Returns the primary key of this pay component.
	 *
	 * @return the primary key of this pay component
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pay component.
	 *
	 * @param primaryKey the primary key of this pay component
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the component ID of this pay component.
	 *
	 * @return the component ID of this pay component
	 */
	public long getComponentId();

	/**
	 * Sets the component ID of this pay component.
	 *
	 * @param componentId the component ID of this pay component
	 */
	public void setComponentId(long componentId);

	/**
	 * Returns the employee type ID of this pay component.
	 *
	 * @return the employee type ID of this pay component
	 */
	public long getEmployeeTypeId();

	/**
	 * Sets the employee type ID of this pay component.
	 *
	 * @param employeeTypeId the employee type ID of this pay component
	 */
	public void setEmployeeTypeId(long employeeTypeId);

	/**
	 * Returns the name of this pay component.
	 *
	 * @return the name of this pay component
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this pay component.
	 *
	 * @param name the name of this pay component
	 */
	public void setName(String name);

	/**
	 * Returns the abbreviation of this pay component.
	 *
	 * @return the abbreviation of this pay component
	 */
	@AutoEscape
	public String getAbbreviation();

	/**
	 * Sets the abbreviation of this pay component.
	 *
	 * @param abbreviation the abbreviation of this pay component
	 */
	public void setAbbreviation(String abbreviation);

	/**
	 * Returns the tax status of this pay component.
	 *
	 * @return the tax status of this pay component
	 */
	public int getTaxStatus();

	/**
	 * Sets the tax status of this pay component.
	 *
	 * @param taxStatus the tax status of this pay component
	 */
	public void setTaxStatus(int taxStatus);

	/**
	 * Returns the pay type of this pay component.
	 *
	 * @return the pay type of this pay component
	 */
	@AutoEscape
	public String getPayType();

	/**
	 * Sets the pay type of this pay component.
	 *
	 * @param payType the pay type of this pay component
	 */
	public void setPayType(String payType);

	/**
	 * Returns the component type of this pay component.
	 *
	 * @return the component type of this pay component
	 */
	public int getComponentType();

	/**
	 * Sets the component type of this pay component.
	 *
	 * @param componentType the component type of this pay component
	 */
	public void setComponentType(int componentType);

	/**
	 * Returns the component value formula of this pay component.
	 *
	 * @return the component value formula of this pay component
	 */
	@AutoEscape
	public String getComponentValueFormula();

	/**
	 * Sets the component value formula of this pay component.
	 *
	 * @param componentValueFormula the component value formula of this pay component
	 */
	public void setComponentValueFormula(String componentValueFormula);

	/**
	 * Returns the part of ctc of this pay component.
	 *
	 * @return the part of ctc of this pay component
	 */
	public int getPartOfCtc();

	/**
	 * Sets the part of ctc of this pay component.
	 *
	 * @param partOfCtc the part of ctc of this pay component
	 */
	public void setPartOfCtc(int partOfCtc);

	/**
	 * Returns the effective date of this pay component.
	 *
	 * @return the effective date of this pay component
	 */
	public Date getEffectiveDate();

	/**
	 * Sets the effective date of this pay component.
	 *
	 * @param effectiveDate the effective date of this pay component
	 */
	public void setEffectiveDate(Date effectiveDate);

	/**
	 * Returns the islock of this pay component.
	 *
	 * @return the islock of this pay component
	 */
	public long getIslock();

	/**
	 * Sets the islock of this pay component.
	 *
	 * @param islock the islock of this pay component
	 */
	public void setIslock(long islock);

	/**
	 * Returns the create date of this pay component.
	 *
	 * @return the create date of this pay component
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this pay component.
	 *
	 * @param createDate the create date of this pay component
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pay component.
	 *
	 * @return the modified date of this pay component
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pay component.
	 *
	 * @param modifiedDate the modified date of this pay component
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the amount of this pay component.
	 *
	 * @return the amount of this pay component
	 */
	public double getAmount();

	/**
	 * Sets the amount of this pay component.
	 *
	 * @param amount the amount of this pay component
	 */
	public void setAmount(double amount);

	/**
	 * Returns the pay component order of this pay component.
	 *
	 * @return the pay component order of this pay component
	 */
	public long getPayComponentOrder();

	/**
	 * Sets the pay component order of this pay component.
	 *
	 * @param payComponentOrder the pay component order of this pay component
	 */
	public void setPayComponentOrder(long payComponentOrder);

	/**
	 * Returns the auto add pay structure of this pay component.
	 *
	 * @return the auto add pay structure of this pay component
	 */
	public int getAutoAddPayStructure();

	/**
	 * Sets the auto add pay structure of this pay component.
	 *
	 * @param autoAddPayStructure the auto add pay structure of this pay component
	 */
	public void setAutoAddPayStructure(int autoAddPayStructure);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PayComponent payComponent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PayComponent> toCacheModel();

	@Override
	public PayComponent toEscapedModel();

	@Override
	public PayComponent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}