/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the PayrollIncrement service. Represents a row in the &quot;payrollIncrement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.PayrollIncrementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.PayrollIncrementImpl}.
 * </p>
 *
 * @author Samaresh
 * @see PayrollIncrement
 * @see com.liferay.famocom.erpcloud.model.impl.PayrollIncrementImpl
 * @see com.liferay.famocom.erpcloud.model.impl.PayrollIncrementModelImpl
 * @generated
 */
@ProviderType
public interface PayrollIncrementModel extends BaseModel<PayrollIncrement>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payroll increment model instance should use the {@link PayrollIncrement} interface instead.
	 */

	/**
	 * Returns the primary key of this payroll increment.
	 *
	 * @return the primary key of this payroll increment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payroll increment.
	 *
	 * @param primaryKey the primary key of this payroll increment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the payroll increment ID of this payroll increment.
	 *
	 * @return the payroll increment ID of this payroll increment
	 */
	public long getPayrollIncrementId();

	/**
	 * Sets the payroll increment ID of this payroll increment.
	 *
	 * @param payrollIncrementId the payroll increment ID of this payroll increment
	 */
	public void setPayrollIncrementId(long payrollIncrementId);

	/**
	 * Returns the appraisal setting ID of this payroll increment.
	 *
	 * @return the appraisal setting ID of this payroll increment
	 */
	public long getAppraisalSettingId();

	/**
	 * Sets the appraisal setting ID of this payroll increment.
	 *
	 * @param appraisalSettingId the appraisal setting ID of this payroll increment
	 */
	public void setAppraisalSettingId(long appraisalSettingId);

	/**
	 * Returns the employee ID of this payroll increment.
	 *
	 * @return the employee ID of this payroll increment
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this payroll increment.
	 *
	 * @param employeeId the employee ID of this payroll increment
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this payroll increment.
	 *
	 * @return the company ID of this payroll increment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this payroll increment.
	 *
	 * @param companyId the company ID of this payroll increment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee code of this payroll increment.
	 *
	 * @return the employee code of this payroll increment
	 */
	public long getEmployeeCode();

	/**
	 * Sets the employee code of this payroll increment.
	 *
	 * @param employeeCode the employee code of this payroll increment
	 */
	public void setEmployeeCode(long employeeCode);

	/**
	 * Returns the overall rating man of this payroll increment.
	 *
	 * @return the overall rating man of this payroll increment
	 */
	public long getOverallRatingMan();

	/**
	 * Sets the overall rating man of this payroll increment.
	 *
	 * @param overallRatingMan the overall rating man of this payroll increment
	 */
	public void setOverallRatingMan(long overallRatingMan);

	/**
	 * Returns the pre ctc of this payroll increment.
	 *
	 * @return the pre ctc of this payroll increment
	 */
	public double getPreCtc();

	/**
	 * Sets the pre ctc of this payroll increment.
	 *
	 * @param preCtc the pre ctc of this payroll increment
	 */
	public void setPreCtc(double preCtc);

	/**
	 * Returns the post ctc of this payroll increment.
	 *
	 * @return the post ctc of this payroll increment
	 */
	public double getPostCtc();

	/**
	 * Sets the post ctc of this payroll increment.
	 *
	 * @param postCtc the post ctc of this payroll increment
	 */
	public void setPostCtc(double postCtc);

	/**
	 * Returns the component ID of this payroll increment.
	 *
	 * @return the component ID of this payroll increment
	 */
	public long getComponentId();

	/**
	 * Sets the component ID of this payroll increment.
	 *
	 * @param componentId the component ID of this payroll increment
	 */
	public void setComponentId(long componentId);

	/**
	 * Returns the pre head component val of this payroll increment.
	 *
	 * @return the pre head component val of this payroll increment
	 */
	public double getPreHeadComponentVal();

	/**
	 * Sets the pre head component val of this payroll increment.
	 *
	 * @param preHeadComponentVal the pre head component val of this payroll increment
	 */
	public void setPreHeadComponentVal(double preHeadComponentVal);

	/**
	 * Returns the post head component val of this payroll increment.
	 *
	 * @return the post head component val of this payroll increment
	 */
	public double getPostHeadComponentVal();

	/**
	 * Sets the post head component val of this payroll increment.
	 *
	 * @param postHeadComponentVal the post head component val of this payroll increment
	 */
	public void setPostHeadComponentVal(double postHeadComponentVal);

	/**
	 * Returns the bonus val of this payroll increment.
	 *
	 * @return the bonus val of this payroll increment
	 */
	public double getBonusVal();

	/**
	 * Sets the bonus val of this payroll increment.
	 *
	 * @param bonusVal the bonus val of this payroll increment
	 */
	public void setBonusVal(double bonusVal);

	/**
	 * Returns the financial year of this payroll increment.
	 *
	 * @return the financial year of this payroll increment
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this payroll increment.
	 *
	 * @param financialYear the financial year of this payroll increment
	 */
	public void setFinancialYear(String financialYear);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PayrollIncrement payrollIncrement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PayrollIncrement> toCacheModel();

	@Override
	public PayrollIncrement toEscapedModel();

	@Override
	public PayrollIncrement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}