/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PerformanceMaster service. Represents a row in the &quot;performanceMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.PerformanceMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.PerformanceMasterImpl}.
 * </p>
 *
 * @author Samaresh
 * @see PerformanceMaster
 * @see com.liferay.famocom.erpcloud.model.impl.PerformanceMasterImpl
 * @see com.liferay.famocom.erpcloud.model.impl.PerformanceMasterModelImpl
 * @generated
 */
@ProviderType
public interface PerformanceMasterModel extends BaseModel<PerformanceMaster>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a performance master model instance should use the {@link PerformanceMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this performance master.
	 *
	 * @return the primary key of this performance master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this performance master.
	 *
	 * @param primaryKey the primary key of this performance master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the performance ID of this performance master.
	 *
	 * @return the performance ID of this performance master
	 */
	public long getPerformanceId();

	/**
	 * Sets the performance ID of this performance master.
	 *
	 * @param performanceId the performance ID of this performance master
	 */
	public void setPerformanceId(long performanceId);

	/**
	 * Returns the company ID of this performance master.
	 *
	 * @return the company ID of this performance master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this performance master.
	 *
	 * @param companyId the company ID of this performance master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the performance heading of this performance master.
	 *
	 * @return the performance heading of this performance master
	 */
	@AutoEscape
	public String getPerformanceHeading();

	/**
	 * Sets the performance heading of this performance master.
	 *
	 * @param performanceHeading the performance heading of this performance master
	 */
	public void setPerformanceHeading(String performanceHeading);

	/**
	 * Returns the performance description of this performance master.
	 *
	 * @return the performance description of this performance master
	 */
	@AutoEscape
	public String getPerformanceDescription();

	/**
	 * Sets the performance description of this performance master.
	 *
	 * @param performanceDescription the performance description of this performance master
	 */
	public void setPerformanceDescription(String performanceDescription);

	/**
	 * Returns the added date of this performance master.
	 *
	 * @return the added date of this performance master
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this performance master.
	 *
	 * @param addedDate the added date of this performance master
	 */
	public void setAddedDate(Date addedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PerformanceMaster performanceMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PerformanceMaster> toCacheModel();

	@Override
	public PerformanceMaster toEscapedModel();

	@Override
	public PerformanceMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}