/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectReport service. Represents a row in the &quot;projectReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ProjectReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ProjectReportImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ProjectReport
 * @see com.liferay.famocom.erpcloud.model.impl.ProjectReportImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ProjectReportModelImpl
 * @generated
 */
@ProviderType
public interface ProjectReportModel extends BaseModel<ProjectReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project report model instance should use the {@link ProjectReport} interface instead.
	 */

	/**
	 * Returns the primary key of this project report.
	 *
	 * @return the primary key of this project report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project report.
	 *
	 * @param primaryKey the primary key of this project report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the report template ID of this project report.
	 *
	 * @return the report template ID of this project report
	 */
	public long getReportTemplateId();

	/**
	 * Sets the report template ID of this project report.
	 *
	 * @param reportTemplateId the report template ID of this project report
	 */
	public void setReportTemplateId(long reportTemplateId);

	/**
	 * Returns the project ID of this project report.
	 *
	 * @return the project ID of this project report
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project report.
	 *
	 * @param projectId the project ID of this project report
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the employee ID of this project report.
	 *
	 * @return the employee ID of this project report
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this project report.
	 *
	 * @param employeeId the employee ID of this project report
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the timesheet ID of this project report.
	 *
	 * @return the timesheet ID of this project report
	 */
	public long getTimesheetId();

	/**
	 * Sets the timesheet ID of this project report.
	 *
	 * @param timesheetId the timesheet ID of this project report
	 */
	public void setTimesheetId(long timesheetId);

	/**
	 * Returns the project task ID of this project report.
	 *
	 * @return the project task ID of this project report
	 */
	public long getProjectTaskId();

	/**
	 * Sets the project task ID of this project report.
	 *
	 * @param projectTaskId the project task ID of this project report
	 */
	public void setProjectTaskId(long projectTaskId);

	/**
	 * Returns the from date of this project report.
	 *
	 * @return the from date of this project report
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this project report.
	 *
	 * @param fromDate the from date of this project report
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this project report.
	 *
	 * @return the to date of this project report
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this project report.
	 *
	 * @param toDate the to date of this project report
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the template nm of this project report.
	 *
	 * @return the template nm of this project report
	 */
	@AutoEscape
	public String getTemplateNm();

	/**
	 * Sets the template nm of this project report.
	 *
	 * @param templateNm the template nm of this project report
	 */
	public void setTemplateNm(String templateNm);

	/**
	 * Returns the added date of this project report.
	 *
	 * @return the added date of this project report
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this project report.
	 *
	 * @param addedDate the added date of this project report
	 */
	public void setAddedDate(Date addedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProjectReport projectReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectReport> toCacheModel();

	@Override
	public ProjectReport toEscapedModel();

	@Override
	public ProjectReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}