/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectStatus service. Represents a row in the &quot;projectStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.ProjectStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.ProjectStatusImpl}.
 * </p>
 *
 * @author Samaresh
 * @see ProjectStatus
 * @see com.liferay.famocom.erpcloud.model.impl.ProjectStatusImpl
 * @see com.liferay.famocom.erpcloud.model.impl.ProjectStatusModelImpl
 * @generated
 */
@ProviderType
public interface ProjectStatusModel extends BaseModel<ProjectStatus>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project status model instance should use the {@link ProjectStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this project status.
	 *
	 * @return the primary key of this project status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project status.
	 *
	 * @param primaryKey the primary key of this project status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project status ID of this project status.
	 *
	 * @return the project status ID of this project status
	 */
	public long getProjectStatusId();

	/**
	 * Sets the project status ID of this project status.
	 *
	 * @param projectStatusId the project status ID of this project status
	 */
	public void setProjectStatusId(long projectStatusId);

	/**
	 * Returns the company ID of this project status.
	 *
	 * @return the company ID of this project status
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project status.
	 *
	 * @param companyId the company ID of this project status
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the status name of this project status.
	 *
	 * @return the status name of this project status
	 */
	@AutoEscape
	public String getStatusName();

	/**
	 * Sets the status name of this project status.
	 *
	 * @param statusName the status name of this project status
	 */
	public void setStatusName(String statusName);

	/**
	 * Returns the status color of this project status.
	 *
	 * @return the status color of this project status
	 */
	@AutoEscape
	public String getStatusColor();

	/**
	 * Sets the status color of this project status.
	 *
	 * @param statusColor the status color of this project status
	 */
	public void setStatusColor(String statusColor);

	/**
	 * Returns the added date of this project status.
	 *
	 * @return the added date of this project status
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this project status.
	 *
	 * @param addedDate the added date of this project status
	 */
	public void setAddedDate(Date addedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProjectStatus projectStatus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectStatus> toCacheModel();

	@Override
	public ProjectStatus toEscapedModel();

	@Override
	public ProjectStatus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}