/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PushNotification service. Represents a row in the &quot;pushNotification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.PushNotificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.PushNotificationImpl}.
 * </p>
 *
 * @author Samaresh
 * @see PushNotification
 * @see com.liferay.famocom.erpcloud.model.impl.PushNotificationImpl
 * @see com.liferay.famocom.erpcloud.model.impl.PushNotificationModelImpl
 * @generated
 */
@ProviderType
public interface PushNotificationModel extends BaseModel<PushNotification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a push notification model instance should use the {@link PushNotification} interface instead.
	 */

	/**
	 * Returns the primary key of this push notification.
	 *
	 * @return the primary key of this push notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this push notification.
	 *
	 * @param primaryKey the primary key of this push notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the push notification ID of this push notification.
	 *
	 * @return the push notification ID of this push notification
	 */
	public long getPushNotificationId();

	/**
	 * Sets the push notification ID of this push notification.
	 *
	 * @param pushNotificationId the push notification ID of this push notification
	 */
	public void setPushNotificationId(long pushNotificationId);

	/**
	 * Returns the subject of this push notification.
	 *
	 * @return the subject of this push notification
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this push notification.
	 *
	 * @param subject the subject of this push notification
	 */
	public void setSubject(String subject);

	/**
	 * Returns the message of this push notification.
	 *
	 * @return the message of this push notification
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this push notification.
	 *
	 * @param message the message of this push notification
	 */
	public void setMessage(String message);

	/**
	 * Returns the file ID of this push notification.
	 *
	 * @return the file ID of this push notification
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this push notification.
	 *
	 * @param fileId the file ID of this push notification
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the file url of this push notification.
	 *
	 * @return the file url of this push notification
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this push notification.
	 *
	 * @param fileUrl the file url of this push notification
	 */
	public void setFileUrl(String fileUrl);

	/**
	 * Returns the create date of this push notification.
	 *
	 * @return the create date of this push notification
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this push notification.
	 *
	 * @param createDate the create date of this push notification
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this push notification.
	 *
	 * @return the modified date of this push notification
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this push notification.
	 *
	 * @param modifiedDate the modified date of this push notification
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PushNotification pushNotification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PushNotification> toCacheModel();

	@Override
	public PushNotification toEscapedModel();

	@Override
	public PushNotification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}