/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RecruitProcess service. Represents a row in the &quot;RecruitProcess&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.RecruitProcessModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.RecruitProcessImpl}.
 * </p>
 *
 * @author Samaresh
 * @see RecruitProcess
 * @see com.liferay.famocom.erpcloud.model.impl.RecruitProcessImpl
 * @see com.liferay.famocom.erpcloud.model.impl.RecruitProcessModelImpl
 * @generated
 */
@ProviderType
public interface RecruitProcessModel extends BaseModel<RecruitProcess> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a recruit process model instance should use the {@link RecruitProcess} interface instead.
	 */

	/**
	 * Returns the primary key of this recruit process.
	 *
	 * @return the primary key of this recruit process
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this recruit process.
	 *
	 * @param primaryKey the primary key of this recruit process
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the recruit process ID of this recruit process.
	 *
	 * @return the recruit process ID of this recruit process
	 */
	public long getRecruitProcessId();

	/**
	 * Sets the recruit process ID of this recruit process.
	 *
	 * @param recruitProcessId the recruit process ID of this recruit process
	 */
	public void setRecruitProcessId(long recruitProcessId);

	/**
	 * Returns the first name of this recruit process.
	 *
	 * @return the first name of this recruit process
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this recruit process.
	 *
	 * @param firstName the first name of this recruit process
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this recruit process.
	 *
	 * @return the last name of this recruit process
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this recruit process.
	 *
	 * @param lastName the last name of this recruit process
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the employee ID of this recruit process.
	 *
	 * @return the employee ID of this recruit process
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this recruit process.
	 *
	 * @param employeeId the employee ID of this recruit process
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the interview date of this recruit process.
	 *
	 * @return the interview date of this recruit process
	 */
	public Date getInterviewDate();

	/**
	 * Sets the interview date of this recruit process.
	 *
	 * @param interviewDate the interview date of this recruit process
	 */
	public void setInterviewDate(Date interviewDate);

	/**
	 * Returns the interview time of this recruit process.
	 *
	 * @return the interview time of this recruit process
	 */
	@AutoEscape
	public String getInterviewTime();

	/**
	 * Sets the interview time of this recruit process.
	 *
	 * @param interviewTime the interview time of this recruit process
	 */
	public void setInterviewTime(String interviewTime);

	/**
	 * Returns the file entry ID of this recruit process.
	 *
	 * @return the file entry ID of this recruit process
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this recruit process.
	 *
	 * @param fileEntryId the file entry ID of this recruit process
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the file url of this recruit process.
	 *
	 * @return the file url of this recruit process
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this recruit process.
	 *
	 * @param fileUrl the file url of this recruit process
	 */
	public void setFileUrl(String fileUrl);

	/**
	 * Returns the create date of this recruit process.
	 *
	 * @return the create date of this recruit process
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this recruit process.
	 *
	 * @param createDate the create date of this recruit process
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this recruit process.
	 *
	 * @return the modified date of this recruit process
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this recruit process.
	 *
	 * @param modifiedDate the modified date of this recruit process
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the interviewer remarks of this recruit process.
	 *
	 * @return the interviewer remarks of this recruit process
	 */
	@AutoEscape
	public String getInterviewerRemarks();

	/**
	 * Sets the interviewer remarks of this recruit process.
	 *
	 * @param interviewerRemarks the interviewer remarks of this recruit process
	 */
	public void setInterviewerRemarks(String interviewerRemarks);

	/**
	 * Returns the hr remarks of this recruit process.
	 *
	 * @return the hr remarks of this recruit process
	 */
	@AutoEscape
	public String getHrRemarks();

	/**
	 * Sets the hr remarks of this recruit process.
	 *
	 * @param hrRemarks the hr remarks of this recruit process
	 */
	public void setHrRemarks(String hrRemarks);

	/**
	 * Returns the is selected of this recruit process.
	 *
	 * @return the is selected of this recruit process
	 */
	public int getIsSelected();

	/**
	 * Sets the is selected of this recruit process.
	 *
	 * @param isSelected the is selected of this recruit process
	 */
	public void setIsSelected(int isSelected);

	/**
	 * Returns the status of this recruit process.
	 *
	 * @return the status of this recruit process
	 */
	public long getStatus();

	/**
	 * Sets the status of this recruit process.
	 *
	 * @param status the status of this recruit process
	 */
	public void setStatus(long status);

	/**
	 * Returns the dob of this recruit process.
	 *
	 * @return the dob of this recruit process
	 */
	public Date getDOB();

	/**
	 * Sets the dob of this recruit process.
	 *
	 * @param DOB the dob of this recruit process
	 */
	public void setDOB(Date DOB);

	/**
	 * Returns the email of this recruit process.
	 *
	 * @return the email of this recruit process
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this recruit process.
	 *
	 * @param email the email of this recruit process
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone number of this recruit process.
	 *
	 * @return the phone number of this recruit process
	 */
	public long getPhoneNumber();

	/**
	 * Sets the phone number of this recruit process.
	 *
	 * @param phoneNumber the phone number of this recruit process
	 */
	public void setPhoneNumber(long phoneNumber);

	/**
	 * Returns the skillset of this recruit process.
	 *
	 * @return the skillset of this recruit process
	 */
	@AutoEscape
	public String getSkillset();

	/**
	 * Sets the skillset of this recruit process.
	 *
	 * @param skillset the skillset of this recruit process
	 */
	public void setSkillset(String skillset);

	/**
	 * Returns the experience of this recruit process.
	 *
	 * @return the experience of this recruit process
	 */
	public double getExperience();

	/**
	 * Sets the experience of this recruit process.
	 *
	 * @param experience the experience of this recruit process
	 */
	public void setExperience(double experience);

	/**
	 * Returns the notice period of this recruit process.
	 *
	 * @return the notice period of this recruit process
	 */
	public int getNoticePeriod();

	/**
	 * Sets the notice period of this recruit process.
	 *
	 * @param noticePeriod the notice period of this recruit process
	 */
	public void setNoticePeriod(int noticePeriod);

	/**
	 * Returns the current ctc of this recruit process.
	 *
	 * @return the current ctc of this recruit process
	 */
	public double getCurrentCTC();

	/**
	 * Sets the current ctc of this recruit process.
	 *
	 * @param currentCTC the current ctc of this recruit process
	 */
	public void setCurrentCTC(double currentCTC);

	/**
	 * Returns the expexted ctc of this recruit process.
	 *
	 * @return the expexted ctc of this recruit process
	 */
	public double getExpextedCTC();

	/**
	 * Sets the expexted ctc of this recruit process.
	 *
	 * @param expextedCTC the expexted ctc of this recruit process
	 */
	public void setExpextedCTC(double expextedCTC);

	/**
	 * Returns the project role ID of this recruit process.
	 *
	 * @return the project role ID of this recruit process
	 */
	public long getProjectRoleId();

	/**
	 * Sets the project role ID of this recruit process.
	 *
	 * @param projectRoleId the project role ID of this recruit process
	 */
	public void setProjectRoleId(long projectRoleId);

	/**
	 * Returns the reference of this recruit process.
	 *
	 * @return the reference of this recruit process
	 */
	public long getReference();

	/**
	 * Sets the reference of this recruit process.
	 *
	 * @param reference the reference of this recruit process
	 */
	public void setReference(long reference);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RecruitProcess recruitProcess);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RecruitProcess> toCacheModel();

	@Override
	public RecruitProcess toEscapedModel();

	@Override
	public RecruitProcess toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}