/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SalDetails service. Represents a row in the &quot;payDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.SalDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.SalDetailsImpl}.
 * </p>
 *
 * @author Samaresh
 * @see SalDetails
 * @see com.liferay.famocom.erpcloud.model.impl.SalDetailsImpl
 * @see com.liferay.famocom.erpcloud.model.impl.SalDetailsModelImpl
 * @generated
 */
@ProviderType
public interface SalDetailsModel extends BaseModel<SalDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sal details model instance should use the {@link SalDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this sal details.
	 *
	 * @return the primary key of this sal details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sal details.
	 *
	 * @param primaryKey the primary key of this sal details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sal details ID of this sal details.
	 *
	 * @return the sal details ID of this sal details
	 */
	public long getSalDetailsId();

	/**
	 * Sets the sal details ID of this sal details.
	 *
	 * @param SalDetailsId the sal details ID of this sal details
	 */
	public void setSalDetailsId(long SalDetailsId);

	/**
	 * Returns the month year of this sal details.
	 *
	 * @return the month year of this sal details
	 */
	public long getMonthYear();

	/**
	 * Sets the month year of this sal details.
	 *
	 * @param monthYear the month year of this sal details
	 */
	public void setMonthYear(long monthYear);

	/**
	 * Returns the component ID of this sal details.
	 *
	 * @return the component ID of this sal details
	 */
	public long getComponentId();

	/**
	 * Sets the component ID of this sal details.
	 *
	 * @param componentId the component ID of this sal details
	 */
	public void setComponentId(long componentId);

	/**
	 * Returns the employee ID of this sal details.
	 *
	 * @return the employee ID of this sal details
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this sal details.
	 *
	 * @param employeeId the employee ID of this sal details
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the value of this sal details.
	 *
	 * @return the value of this sal details
	 */
	public double getValue();

	/**
	 * Sets the value of this sal details.
	 *
	 * @param value the value of this sal details
	 */
	public void setValue(double value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SalDetails salDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SalDetails> toCacheModel();

	@Override
	public SalDetails toEscapedModel();

	@Override
	public SalDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}