/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SchedulesDetails service. Represents a row in the &quot;SchedulesDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.SchedulesDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.SchedulesDetailsImpl}.
 * </p>
 *
 * @author Samaresh
 * @see SchedulesDetails
 * @see com.liferay.famocom.erpcloud.model.impl.SchedulesDetailsImpl
 * @see com.liferay.famocom.erpcloud.model.impl.SchedulesDetailsModelImpl
 * @generated
 */
@ProviderType
public interface SchedulesDetailsModel extends BaseModel<SchedulesDetails>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a schedules details model instance should use the {@link SchedulesDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this schedules details.
	 *
	 * @return the primary key of this schedules details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this schedules details.
	 *
	 * @param primaryKey the primary key of this schedules details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the schedules details ID of this schedules details.
	 *
	 * @return the schedules details ID of this schedules details
	 */
	public long getSchedulesDetailsId();

	/**
	 * Sets the schedules details ID of this schedules details.
	 *
	 * @param schedulesDetailsId the schedules details ID of this schedules details
	 */
	public void setSchedulesDetailsId(long schedulesDetailsId);

	/**
	 * Returns the schedules date of this schedules details.
	 *
	 * @return the schedules date of this schedules details
	 */
	public Date getSchedulesDate();

	/**
	 * Sets the schedules date of this schedules details.
	 *
	 * @param schedulesDate the schedules date of this schedules details
	 */
	public void setSchedulesDate(Date schedulesDate);

	/**
	 * Returns the works schedules ID of this schedules details.
	 *
	 * @return the works schedules ID of this schedules details
	 */
	public long getWorksSchedulesId();

	/**
	 * Sets the works schedules ID of this schedules details.
	 *
	 * @param worksSchedulesId the works schedules ID of this schedules details
	 */
	public void setWorksSchedulesId(long worksSchedulesId);

	/**
	 * Returns the employee ID of this schedules details.
	 *
	 * @return the employee ID of this schedules details
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this schedules details.
	 *
	 * @param employeeId the employee ID of this schedules details
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this schedules details.
	 *
	 * @return the company ID of this schedules details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this schedules details.
	 *
	 * @param companyId the company ID of this schedules details
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SchedulesDetails schedulesDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SchedulesDetails> toCacheModel();

	@Override
	public SchedulesDetails toEscapedModel();

	@Override
	public SchedulesDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}