/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SelectedCandidatePayStructure service. Represents a row in the &quot;SelectedCandidatePayStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.SelectedCandidatePayStructureModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.SelectedCandidatePayStructureImpl}.
 * </p>
 *
 * @author Samaresh
 * @see SelectedCandidatePayStructure
 * @see com.liferay.famocom.erpcloud.model.impl.SelectedCandidatePayStructureImpl
 * @see com.liferay.famocom.erpcloud.model.impl.SelectedCandidatePayStructureModelImpl
 * @generated
 */
@ProviderType
public interface SelectedCandidatePayStructureModel extends BaseModel<SelectedCandidatePayStructure> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a selected candidate pay structure model instance should use the {@link SelectedCandidatePayStructure} interface instead.
	 */

	/**
	 * Returns the primary key of this selected candidate pay structure.
	 *
	 * @return the primary key of this selected candidate pay structure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this selected candidate pay structure.
	 *
	 * @param primaryKey the primary key of this selected candidate pay structure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the candidate pay structure ID of this selected candidate pay structure.
	 *
	 * @return the candidate pay structure ID of this selected candidate pay structure
	 */
	public long getCandidatePayStructureId();

	/**
	 * Sets the candidate pay structure ID of this selected candidate pay structure.
	 *
	 * @param candidatePayStructureId the candidate pay structure ID of this selected candidate pay structure
	 */
	public void setCandidatePayStructureId(long candidatePayStructureId);

	/**
	 * Returns the pay component ID of this selected candidate pay structure.
	 *
	 * @return the pay component ID of this selected candidate pay structure
	 */
	public long getPayComponentId();

	/**
	 * Sets the pay component ID of this selected candidate pay structure.
	 *
	 * @param payComponentId the pay component ID of this selected candidate pay structure
	 */
	public void setPayComponentId(long payComponentId);

	/**
	 * Returns the component value of this selected candidate pay structure.
	 *
	 * @return the component value of this selected candidate pay structure
	 */
	public double getComponentValue();

	/**
	 * Sets the component value of this selected candidate pay structure.
	 *
	 * @param componentValue the component value of this selected candidate pay structure
	 */
	public void setComponentValue(double componentValue);

	/**
	 * Returns the recruitment process ID of this selected candidate pay structure.
	 *
	 * @return the recruitment process ID of this selected candidate pay structure
	 */
	public long getRecruitmentProcessId();

	/**
	 * Sets the recruitment process ID of this selected candidate pay structure.
	 *
	 * @param recruitmentProcessId the recruitment process ID of this selected candidate pay structure
	 */
	public void setRecruitmentProcessId(long recruitmentProcessId);

	/**
	 * Returns the pay status of this selected candidate pay structure.
	 *
	 * @return the pay status of this selected candidate pay structure
	 */
	public int getPayStatus();

	/**
	 * Sets the pay status of this selected candidate pay structure.
	 *
	 * @param payStatus the pay status of this selected candidate pay structure
	 */
	public void setPayStatus(int payStatus);

	/**
	 * Returns the create date of this selected candidate pay structure.
	 *
	 * @return the create date of this selected candidate pay structure
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this selected candidate pay structure.
	 *
	 * @param createDate the create date of this selected candidate pay structure
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this selected candidate pay structure.
	 *
	 * @return the modified date of this selected candidate pay structure
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this selected candidate pay structure.
	 *
	 * @param modifiedDate the modified date of this selected candidate pay structure
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		SelectedCandidatePayStructure selectedCandidatePayStructure);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SelectedCandidatePayStructure> toCacheModel();

	@Override
	public SelectedCandidatePayStructure toEscapedModel();

	@Override
	public SelectedCandidatePayStructure toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}