/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StopPay service. Represents a row in the &quot;StopPay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.StopPayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.StopPayImpl}.
 * </p>
 *
 * @author Samaresh
 * @see StopPay
 * @see com.liferay.famocom.erpcloud.model.impl.StopPayImpl
 * @see com.liferay.famocom.erpcloud.model.impl.StopPayModelImpl
 * @generated
 */
@ProviderType
public interface StopPayModel extends BaseModel<StopPay> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stop pay model instance should use the {@link StopPay} interface instead.
	 */

	/**
	 * Returns the primary key of this stop pay.
	 *
	 * @return the primary key of this stop pay
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stop pay.
	 *
	 * @param primaryKey the primary key of this stop pay
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the stop pay ID of this stop pay.
	 *
	 * @return the stop pay ID of this stop pay
	 */
	public long getStopPayId();

	/**
	 * Sets the stop pay ID of this stop pay.
	 *
	 * @param stopPayId the stop pay ID of this stop pay
	 */
	public void setStopPayId(long stopPayId);

	/**
	 * Returns the month year of this stop pay.
	 *
	 * @return the month year of this stop pay
	 */
	public long getMonthYear();

	/**
	 * Sets the month year of this stop pay.
	 *
	 * @param monthYear the month year of this stop pay
	 */
	public void setMonthYear(long monthYear);

	/**
	 * Returns the employee ID of this stop pay.
	 *
	 * @return the employee ID of this stop pay
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this stop pay.
	 *
	 * @param employeeId the employee ID of this stop pay
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the reason of this stop pay.
	 *
	 * @return the reason of this stop pay
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this stop pay.
	 *
	 * @param reason the reason of this stop pay
	 */
	public void setReason(String reason);

	/**
	 * Returns the created by of this stop pay.
	 *
	 * @return the created by of this stop pay
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this stop pay.
	 *
	 * @param createdBy the created by of this stop pay
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the created date of this stop pay.
	 *
	 * @return the created date of this stop pay
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this stop pay.
	 *
	 * @param createdDate the created date of this stop pay
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this stop pay.
	 *
	 * @return the modified date of this stop pay
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this stop pay.
	 *
	 * @param modifiedDate the modified date of this stop pay
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this stop pay.
	 *
	 * @return the modified by of this stop pay
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this stop pay.
	 *
	 * @param modifiedBy the modified by of this stop pay
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the status of this stop pay.
	 *
	 * @return the status of this stop pay
	 */
	public long getStatus();

	/**
	 * Sets the status of this stop pay.
	 *
	 * @param status the status of this stop pay
	 */
	public void setStatus(long status);

	/**
	 * Returns the is lock of this stop pay.
	 *
	 * @return the is lock of this stop pay
	 */
	public long getIsLock();

	/**
	 * Sets the is lock of this stop pay.
	 *
	 * @param isLock the is lock of this stop pay
	 */
	public void setIsLock(long isLock);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StopPay stopPay);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StopPay> toCacheModel();

	@Override
	public StopPay toEscapedModel();

	@Override
	public StopPay toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}