/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaxDeclarationMonthly service. Represents a row in the &quot;taxDeclarationMonthly&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.TaxDeclarationMonthlyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.TaxDeclarationMonthlyImpl}.
 * </p>
 *
 * @author Samaresh
 * @see TaxDeclarationMonthly
 * @see com.liferay.famocom.erpcloud.model.impl.TaxDeclarationMonthlyImpl
 * @see com.liferay.famocom.erpcloud.model.impl.TaxDeclarationMonthlyModelImpl
 * @generated
 */
@ProviderType
public interface TaxDeclarationMonthlyModel extends BaseModel<TaxDeclarationMonthly>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tax declaration monthly model instance should use the {@link TaxDeclarationMonthly} interface instead.
	 */

	/**
	 * Returns the primary key of this tax declaration monthly.
	 *
	 * @return the primary key of this tax declaration monthly
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tax declaration monthly.
	 *
	 * @param primaryKey the primary key of this tax declaration monthly
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tax declaration monthly ID of this tax declaration monthly.
	 *
	 * @return the tax declaration monthly ID of this tax declaration monthly
	 */
	public long getTaxDeclarationMonthlyId();

	/**
	 * Sets the tax declaration monthly ID of this tax declaration monthly.
	 *
	 * @param taxDeclarationMonthlyId the tax declaration monthly ID of this tax declaration monthly
	 */
	public void setTaxDeclarationMonthlyId(long taxDeclarationMonthlyId);

	/**
	 * Returns the tax declaration ID of this tax declaration monthly.
	 *
	 * @return the tax declaration ID of this tax declaration monthly
	 */
	public long getTaxDeclarationId();

	/**
	 * Sets the tax declaration ID of this tax declaration monthly.
	 *
	 * @param taxDeclarationId the tax declaration ID of this tax declaration monthly
	 */
	public void setTaxDeclarationId(long taxDeclarationId);

	/**
	 * Returns the company ID of this tax declaration monthly.
	 *
	 * @return the company ID of this tax declaration monthly
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tax declaration monthly.
	 *
	 * @param companyId the company ID of this tax declaration monthly
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the financial year of this tax declaration monthly.
	 *
	 * @return the financial year of this tax declaration monthly
	 */
	@AutoEscape
	public String getFinancialYear();

	/**
	 * Sets the financial year of this tax declaration monthly.
	 *
	 * @param financialYear the financial year of this tax declaration monthly
	 */
	public void setFinancialYear(String financialYear);

	/**
	 * Returns the month year of this tax declaration monthly.
	 *
	 * @return the month year of this tax declaration monthly
	 */
	public long getMonthYear();

	/**
	 * Sets the month year of this tax declaration monthly.
	 *
	 * @param monthYear the month year of this tax declaration monthly
	 */
	public void setMonthYear(long monthYear);

	/**
	 * Returns the employee ID of this tax declaration monthly.
	 *
	 * @return the employee ID of this tax declaration monthly
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this tax declaration monthly.
	 *
	 * @param employeeId the employee ID of this tax declaration monthly
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the hra from date of this tax declaration monthly.
	 *
	 * @return the hra from date of this tax declaration monthly
	 */
	@AutoEscape
	public String getHraFromDate();

	/**
	 * Sets the hra from date of this tax declaration monthly.
	 *
	 * @param hraFromDate the hra from date of this tax declaration monthly
	 */
	public void setHraFromDate(String hraFromDate);

	/**
	 * Returns the hra to date of this tax declaration monthly.
	 *
	 * @return the hra to date of this tax declaration monthly
	 */
	@AutoEscape
	public String getHraToDate();

	/**
	 * Sets the hra to date of this tax declaration monthly.
	 *
	 * @param hraToDate the hra to date of this tax declaration monthly
	 */
	public void setHraToDate(String hraToDate);

	/**
	 * Returns the hra city of this tax declaration monthly.
	 *
	 * @return the hra city of this tax declaration monthly
	 */
	@AutoEscape
	public String getHraCity();

	/**
	 * Sets the hra city of this tax declaration monthly.
	 *
	 * @param hraCity the hra city of this tax declaration monthly
	 */
	public void setHraCity(String hraCity);

	/**
	 * Returns the hra ismetro of this tax declaration monthly.
	 *
	 * @return the hra ismetro of this tax declaration monthly
	 */
	@AutoEscape
	public String getHraIsmetro();

	/**
	 * Sets the hra ismetro of this tax declaration monthly.
	 *
	 * @param hraIsmetro the hra ismetro of this tax declaration monthly
	 */
	public void setHraIsmetro(String hraIsmetro);

	/**
	 * Returns the hra landlord pan of this tax declaration monthly.
	 *
	 * @return the hra landlord pan of this tax declaration monthly
	 */
	@AutoEscape
	public String getHraLandlordPan();

	/**
	 * Sets the hra landlord pan of this tax declaration monthly.
	 *
	 * @param hraLandlordPan the hra landlord pan of this tax declaration monthly
	 */
	public void setHraLandlordPan(String hraLandlordPan);

	/**
	 * Returns the hra rent of this tax declaration monthly.
	 *
	 * @return the hra rent of this tax declaration monthly
	 */
	public double getHraRent();

	/**
	 * Sets the hra rent of this tax declaration monthly.
	 *
	 * @param hraRent the hra rent of this tax declaration monthly
	 */
	public void setHraRent(double hraRent);

	/**
	 * Returns the medical individual of this tax declaration monthly.
	 *
	 * @return the medical individual of this tax declaration monthly
	 */
	public double getMedicalIndividual();

	/**
	 * Sets the medical individual of this tax declaration monthly.
	 *
	 * @param medicalIndividual the medical individual of this tax declaration monthly
	 */
	public void setMedicalIndividual(double medicalIndividual);

	/**
	 * Returns the medical parents of this tax declaration monthly.
	 *
	 * @return the medical parents of this tax declaration monthly
	 */
	public double getMedicalParents();

	/**
	 * Sets the medical parents of this tax declaration monthly.
	 *
	 * @param medicalParents the medical parents of this tax declaration monthly
	 */
	public void setMedicalParents(double medicalParents);

	/**
	 * Returns the medical parents senior of this tax declaration monthly.
	 *
	 * @return the medical parents senior of this tax declaration monthly
	 */
	public double getMedicalParentsSenior();

	/**
	 * Sets the medical parents senior of this tax declaration monthly.
	 *
	 * @param medicalParentsSenior the medical parents senior of this tax declaration monthly
	 */
	public void setMedicalParentsSenior(double medicalParentsSenior);

	/**
	 * Returns the medical handi less80 of this tax declaration monthly.
	 *
	 * @return the medical handi less80 of this tax declaration monthly
	 */
	public double getMedicalHandiLess80();

	/**
	 * Sets the medical handi less80 of this tax declaration monthly.
	 *
	 * @param medicalHandiLess80 the medical handi less80 of this tax declaration monthly
	 */
	public void setMedicalHandiLess80(double medicalHandiLess80);

	/**
	 * Returns the medical handi gater80 of this tax declaration monthly.
	 *
	 * @return the medical handi gater80 of this tax declaration monthly
	 */
	public double getMedicalHandiGater80();

	/**
	 * Sets the medical handi gater80 of this tax declaration monthly.
	 *
	 * @param medicalHandiGater80 the medical handi gater80 of this tax declaration monthly
	 */
	public void setMedicalHandiGater80(double medicalHandiGater80);

	/**
	 * Returns the medical gater60 less80 of this tax declaration monthly.
	 *
	 * @return the medical gater60 less80 of this tax declaration monthly
	 */
	public double getMedicalGater60Less80();

	/**
	 * Sets the medical gater60 less80 of this tax declaration monthly.
	 *
	 * @param medicalGater60Less80 the medical gater60 less80 of this tax declaration monthly
	 */
	public void setMedicalGater60Less80(double medicalGater60Less80);

	/**
	 * Returns the medical gater80 of this tax declaration monthly.
	 *
	 * @return the medical gater80 of this tax declaration monthly
	 */
	public double getMedicalGater80();

	/**
	 * Sets the medical gater80 of this tax declaration monthly.
	 *
	 * @param medicalGater80 the medical gater80 of this tax declaration monthly
	 */
	public void setMedicalGater80(double medicalGater80);

	/**
	 * Returns the education loan of this tax declaration monthly.
	 *
	 * @return the education loan of this tax declaration monthly
	 */
	public double getEducationLoan();

	/**
	 * Sets the education loan of this tax declaration monthly.
	 *
	 * @param educationLoan the education loan of this tax declaration monthly
	 */
	public void setEducationLoan(double educationLoan);

	/**
	 * Returns the physical disability of this tax declaration monthly.
	 *
	 * @return the physical disability of this tax declaration monthly
	 */
	public double getPhysicalDisability();

	/**
	 * Sets the physical disability of this tax declaration monthly.
	 *
	 * @param physicalDisability the physical disability of this tax declaration monthly
	 */
	public void setPhysicalDisability(double physicalDisability);

	/**
	 * Returns the physical disability severe of this tax declaration monthly.
	 *
	 * @return the physical disability severe of this tax declaration monthly
	 */
	public double getPhysicalDisabilitySevere();

	/**
	 * Sets the physical disability severe of this tax declaration monthly.
	 *
	 * @param physicalDisabilitySevere the physical disability severe of this tax declaration monthly
	 */
	public void setPhysicalDisabilitySevere(double physicalDisabilitySevere);

	/**
	 * Returns the equity savings of this tax declaration monthly.
	 *
	 * @return the equity savings of this tax declaration monthly
	 */
	public double getEquitySavings();

	/**
	 * Sets the equity savings of this tax declaration monthly.
	 *
	 * @param equitySavings the equity savings of this tax declaration monthly
	 */
	public void setEquitySavings(double equitySavings);

	/**
	 * Returns the interest on deposit of this tax declaration monthly.
	 *
	 * @return the interest on deposit of this tax declaration monthly
	 */
	public double getInterestOnDeposit();

	/**
	 * Sets the interest on deposit of this tax declaration monthly.
	 *
	 * @param interestOnDeposit the interest on deposit of this tax declaration monthly
	 */
	public void setInterestOnDeposit(double interestOnDeposit);

	/**
	 * Returns the national pension of this tax declaration monthly.
	 *
	 * @return the national pension of this tax declaration monthly
	 */
	public double getNationalPension();

	/**
	 * Sets the national pension of this tax declaration monthly.
	 *
	 * @param nationalPension the national pension of this tax declaration monthly
	 */
	public void setNationalPension(double nationalPension);

	/**
	 * Returns the lic of this tax declaration monthly.
	 *
	 * @return the lic of this tax declaration monthly
	 */
	public double getLic();

	/**
	 * Sets the lic of this tax declaration monthly.
	 *
	 * @param lic the lic of this tax declaration monthly
	 */
	public void setLic(double lic);

	/**
	 * Returns the ppf of this tax declaration monthly.
	 *
	 * @return the ppf of this tax declaration monthly
	 */
	public double getPpf();

	/**
	 * Sets the ppf of this tax declaration monthly.
	 *
	 * @param ppf the ppf of this tax declaration monthly
	 */
	public void setPpf(double ppf);

	/**
	 * Returns the nsc of this tax declaration monthly.
	 *
	 * @return the nsc of this tax declaration monthly
	 */
	public double getNsc();

	/**
	 * Sets the nsc of this tax declaration monthly.
	 *
	 * @param nsc the nsc of this tax declaration monthly
	 */
	public void setNsc(double nsc);

	/**
	 * Returns the infra bonds of this tax declaration monthly.
	 *
	 * @return the infra bonds of this tax declaration monthly
	 */
	public double getInfraBonds();

	/**
	 * Sets the infra bonds of this tax declaration monthly.
	 *
	 * @param infraBonds the infra bonds of this tax declaration monthly
	 */
	public void setInfraBonds(double infraBonds);

	/**
	 * Returns the tuition fees of this tax declaration monthly.
	 *
	 * @return the tuition fees of this tax declaration monthly
	 */
	public double getTuitionFees();

	/**
	 * Sets the tuition fees of this tax declaration monthly.
	 *
	 * @param tuitionFees the tuition fees of this tax declaration monthly
	 */
	public void setTuitionFees(double tuitionFees);

	/**
	 * Returns the mutual funds of this tax declaration monthly.
	 *
	 * @return the mutual funds of this tax declaration monthly
	 */
	public double getMutualFunds();

	/**
	 * Sets the mutual funds of this tax declaration monthly.
	 *
	 * @param mutualFunds the mutual funds of this tax declaration monthly
	 */
	public void setMutualFunds(double mutualFunds);

	/**
	 * Returns the sukanya of this tax declaration monthly.
	 *
	 * @return the sukanya of this tax declaration monthly
	 */
	public double getSukanya();

	/**
	 * Sets the sukanya of this tax declaration monthly.
	 *
	 * @param sukanya the sukanya of this tax declaration monthly
	 */
	public void setSukanya(double sukanya);

	/**
	 * Returns the ulip of this tax declaration monthly.
	 *
	 * @return the ulip of this tax declaration monthly
	 */
	public double getUlip();

	/**
	 * Sets the ulip of this tax declaration monthly.
	 *
	 * @param ulip the ulip of this tax declaration monthly
	 */
	public void setUlip(double ulip);

	/**
	 * Returns the time deposit of this tax declaration monthly.
	 *
	 * @return the time deposit of this tax declaration monthly
	 */
	public double getTimeDeposit();

	/**
	 * Sets the time deposit of this tax declaration monthly.
	 *
	 * @param timeDeposit the time deposit of this tax declaration monthly
	 */
	public void setTimeDeposit(double timeDeposit);

	/**
	 * Returns the housing loan of this tax declaration monthly.
	 *
	 * @return the housing loan of this tax declaration monthly
	 */
	public double getHousingLoan();

	/**
	 * Sets the housing loan of this tax declaration monthly.
	 *
	 * @param housingLoan the housing loan of this tax declaration monthly
	 */
	public void setHousingLoan(double housingLoan);

	/**
	 * Returns the fixed deposit of this tax declaration monthly.
	 *
	 * @return the fixed deposit of this tax declaration monthly
	 */
	public double getFixedDeposit();

	/**
	 * Sets the fixed deposit of this tax declaration monthly.
	 *
	 * @param fixedDeposit the fixed deposit of this tax declaration monthly
	 */
	public void setFixedDeposit(double fixedDeposit);

	/**
	 * Returns the nsc interest of this tax declaration monthly.
	 *
	 * @return the nsc interest of this tax declaration monthly
	 */
	public double getNscInterest();

	/**
	 * Sets the nsc interest of this tax declaration monthly.
	 *
	 * @param nscInterest the nsc interest of this tax declaration monthly
	 */
	public void setNscInterest(double nscInterest);

	/**
	 * Returns the housing loan interest of this tax declaration monthly.
	 *
	 * @return the housing loan interest of this tax declaration monthly
	 */
	public double getHousingLoanInterest();

	/**
	 * Sets the housing loan interest of this tax declaration monthly.
	 *
	 * @param housingLoanInterest the housing loan interest of this tax declaration monthly
	 */
	public void setHousingLoanInterest(double housingLoanInterest);

	/**
	 * Returns the housing address of this tax declaration monthly.
	 *
	 * @return the housing address of this tax declaration monthly
	 */
	@AutoEscape
	public String getHousingAddress();

	/**
	 * Sets the housing address of this tax declaration monthly.
	 *
	 * @param housingAddress the housing address of this tax declaration monthly
	 */
	public void setHousingAddress(String housingAddress);

	/**
	 * Returns the previous income of this tax declaration monthly.
	 *
	 * @return the previous income of this tax declaration monthly
	 */
	public double getPreviousIncome();

	/**
	 * Sets the previous income of this tax declaration monthly.
	 *
	 * @param previousIncome the previous income of this tax declaration monthly
	 */
	public void setPreviousIncome(double previousIncome);

	/**
	 * Returns the previous pf of this tax declaration monthly.
	 *
	 * @return the previous pf of this tax declaration monthly
	 */
	public double getPreviousPf();

	/**
	 * Sets the previous pf of this tax declaration monthly.
	 *
	 * @param previousPf the previous pf of this tax declaration monthly
	 */
	public void setPreviousPf(double previousPf);

	/**
	 * Returns the previous pt of this tax declaration monthly.
	 *
	 * @return the previous pt of this tax declaration monthly
	 */
	public double getPreviousPt();

	/**
	 * Sets the previous pt of this tax declaration monthly.
	 *
	 * @param previousPt the previous pt of this tax declaration monthly
	 */
	public void setPreviousPt(double previousPt);

	/**
	 * Returns the previous tds of this tax declaration monthly.
	 *
	 * @return the previous tds of this tax declaration monthly
	 */
	public double getPreviousTds();

	/**
	 * Sets the previous tds of this tax declaration monthly.
	 *
	 * @param previousTds the previous tds of this tax declaration monthly
	 */
	public void setPreviousTds(double previousTds);

	/**
	 * Returns the islock of this tax declaration monthly.
	 *
	 * @return the islock of this tax declaration monthly
	 */
	public boolean getIslock();

	/**
	 * Returns <code>true</code> if this tax declaration monthly is islock.
	 *
	 * @return <code>true</code> if this tax declaration monthly is islock; <code>false</code> otherwise
	 */
	public boolean isIslock();

	/**
	 * Sets whether this tax declaration monthly is islock.
	 *
	 * @param islock the islock of this tax declaration monthly
	 */
	public void setIslock(boolean islock);

	/**
	 * Returns the final submission of this tax declaration monthly.
	 *
	 * @return the final submission of this tax declaration monthly
	 */
	public boolean getFinalSubmission();

	/**
	 * Returns <code>true</code> if this tax declaration monthly is final submission.
	 *
	 * @return <code>true</code> if this tax declaration monthly is final submission; <code>false</code> otherwise
	 */
	public boolean isFinalSubmission();

	/**
	 * Sets whether this tax declaration monthly is final submission.
	 *
	 * @param finalSubmission the final submission of this tax declaration monthly
	 */
	public void setFinalSubmission(boolean finalSubmission);

	/**
	 * Returns the hra exempt of this tax declaration monthly.
	 *
	 * @return the hra exempt of this tax declaration monthly
	 */
	public double getHraExempt();

	/**
	 * Sets the hra exempt of this tax declaration monthly.
	 *
	 * @param hraExempt the hra exempt of this tax declaration monthly
	 */
	public void setHraExempt(double hraExempt);

	/**
	 * Returns the section b exempt of this tax declaration monthly.
	 *
	 * @return the section b exempt of this tax declaration monthly
	 */
	public double getSectionBExempt();

	/**
	 * Sets the section b exempt of this tax declaration monthly.
	 *
	 * @param sectionBExempt the section b exempt of this tax declaration monthly
	 */
	public void setSectionBExempt(double sectionBExempt);

	/**
	 * Returns the section c exempt of this tax declaration monthly.
	 *
	 * @return the section c exempt of this tax declaration monthly
	 */
	public double getSectionCExempt();

	/**
	 * Sets the section c exempt of this tax declaration monthly.
	 *
	 * @param sectionCExempt the section c exempt of this tax declaration monthly
	 */
	public void setSectionCExempt(double sectionCExempt);

	/**
	 * Returns the section d exempt of this tax declaration monthly.
	 *
	 * @return the section d exempt of this tax declaration monthly
	 */
	public double getSectionDExempt();

	/**
	 * Sets the section d exempt of this tax declaration monthly.
	 *
	 * @param sectionDExempt the section d exempt of this tax declaration monthly
	 */
	public void setSectionDExempt(double sectionDExempt);

	/**
	 * Returns the salary after exempt of this tax declaration monthly.
	 *
	 * @return the salary after exempt of this tax declaration monthly
	 */
	public double getSalaryAfterExempt();

	/**
	 * Sets the salary after exempt of this tax declaration monthly.
	 *
	 * @param salaryAfterExempt the salary after exempt of this tax declaration monthly
	 */
	public void setSalaryAfterExempt(double salaryAfterExempt);

	/**
	 * Returns the salary before exempt of this tax declaration monthly.
	 *
	 * @return the salary before exempt of this tax declaration monthly
	 */
	public double getSalaryBeforeExempt();

	/**
	 * Sets the salary before exempt of this tax declaration monthly.
	 *
	 * @param salaryBeforeExempt the salary before exempt of this tax declaration monthly
	 */
	public void setSalaryBeforeExempt(double salaryBeforeExempt);

	/**
	 * Returns the tax rate of this tax declaration monthly.
	 *
	 * @return the tax rate of this tax declaration monthly
	 */
	public double getTaxRate();

	/**
	 * Sets the tax rate of this tax declaration monthly.
	 *
	 * @param taxRate the tax rate of this tax declaration monthly
	 */
	public void setTaxRate(double taxRate);

	/**
	 * Returns the gross tds of this tax declaration monthly.
	 *
	 * @return the gross tds of this tax declaration monthly
	 */
	public double getGrossTds();

	/**
	 * Sets the gross tds of this tax declaration monthly.
	 *
	 * @param grossTds the gross tds of this tax declaration monthly
	 */
	public void setGrossTds(double grossTds);

	/**
	 * Returns the total tds of this tax declaration monthly.
	 *
	 * @return the total tds of this tax declaration monthly
	 */
	public double getTotalTds();

	/**
	 * Sets the total tds of this tax declaration monthly.
	 *
	 * @param totalTds the total tds of this tax declaration monthly
	 */
	public void setTotalTds(double totalTds);

	/**
	 * Returns the tds deducted of this tax declaration monthly.
	 *
	 * @return the tds deducted of this tax declaration monthly
	 */
	public double getTdsDeducted();

	/**
	 * Sets the tds deducted of this tax declaration monthly.
	 *
	 * @param tdsDeducted the tds deducted of this tax declaration monthly
	 */
	public void setTdsDeducted(double tdsDeducted);

	/**
	 * Returns the tds due per month of this tax declaration monthly.
	 *
	 * @return the tds due per month of this tax declaration monthly
	 */
	public double getTdsDuePerMonth();

	/**
	 * Sets the tds due per month of this tax declaration monthly.
	 *
	 * @param tdsDuePerMonth the tds due per month of this tax declaration monthly
	 */
	public void setTdsDuePerMonth(double tdsDuePerMonth);

	/**
	 * Returns the education cess of this tax declaration monthly.
	 *
	 * @return the education cess of this tax declaration monthly
	 */
	public double getEducationCess();

	/**
	 * Sets the education cess of this tax declaration monthly.
	 *
	 * @param educationCess the education cess of this tax declaration monthly
	 */
	public void setEducationCess(double educationCess);

	/**
	 * Returns the total ptax of this tax declaration monthly.
	 *
	 * @return the total ptax of this tax declaration monthly
	 */
	public double getTotalPtax();

	/**
	 * Sets the total ptax of this tax declaration monthly.
	 *
	 * @param totalPtax the total ptax of this tax declaration monthly
	 */
	public void setTotalPtax(double totalPtax);

	/**
	 * Returns the total provident fund of this tax declaration monthly.
	 *
	 * @return the total provident fund of this tax declaration monthly
	 */
	public double getTotalProvidentFund();

	/**
	 * Sets the total provident fund of this tax declaration monthly.
	 *
	 * @param totalProvidentFund the total provident fund of this tax declaration monthly
	 */
	public void setTotalProvidentFund(double totalProvidentFund);

	/**
	 * Returns the total conveyance of this tax declaration monthly.
	 *
	 * @return the total conveyance of this tax declaration monthly
	 */
	public double getTotalConveyance();

	/**
	 * Sets the total conveyance of this tax declaration monthly.
	 *
	 * @param totalConveyance the total conveyance of this tax declaration monthly
	 */
	public void setTotalConveyance(double totalConveyance);

	/**
	 * Returns the added date of this tax declaration monthly.
	 *
	 * @return the added date of this tax declaration monthly
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this tax declaration monthly.
	 *
	 * @param addedDate the added date of this tax declaration monthly
	 */
	public void setAddedDate(Date addedDate);

	/**
	 * Returns the current month tax of this tax declaration monthly.
	 *
	 * @return the current month tax of this tax declaration monthly
	 */
	public double getCurrentMonthTax();

	/**
	 * Sets the current month tax of this tax declaration monthly.
	 *
	 * @param currentMonthTax the current month tax of this tax declaration monthly
	 */
	public void setCurrentMonthTax(double currentMonthTax);

	/**
	 * Returns the section e exempt of this tax declaration monthly.
	 *
	 * @return the section e exempt of this tax declaration monthly
	 */
	public double getSectionEExempt();

	/**
	 * Sets the section e exempt of this tax declaration monthly.
	 *
	 * @param sectionEExempt the section e exempt of this tax declaration monthly
	 */
	public void setSectionEExempt(double sectionEExempt);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaxDeclarationMonthly taxDeclarationMonthly);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaxDeclarationMonthly> toCacheModel();

	@Override
	public TaxDeclarationMonthly toEscapedModel();

	@Override
	public TaxDeclarationMonthly toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}