/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TravelDeskDetails service. Represents a row in the &quot;TravelDesk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.TravelDeskDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.TravelDeskDetailsImpl}.
 * </p>
 *
 * @author Samaresh
 * @see TravelDeskDetails
 * @see com.liferay.famocom.erpcloud.model.impl.TravelDeskDetailsImpl
 * @see com.liferay.famocom.erpcloud.model.impl.TravelDeskDetailsModelImpl
 * @generated
 */
@ProviderType
public interface TravelDeskDetailsModel extends BaseModel<TravelDeskDetails>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a travel desk details model instance should use the {@link TravelDeskDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this travel desk details.
	 *
	 * @return the primary key of this travel desk details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this travel desk details.
	 *
	 * @param primaryKey the primary key of this travel desk details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the travel details ID of this travel desk details.
	 *
	 * @return the travel details ID of this travel desk details
	 */
	public long getTravelDetailsId();

	/**
	 * Sets the travel details ID of this travel desk details.
	 *
	 * @param travelDetailsId the travel details ID of this travel desk details
	 */
	public void setTravelDetailsId(long travelDetailsId);

	/**
	 * Returns the employee ID of this travel desk details.
	 *
	 * @return the employee ID of this travel desk details
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this travel desk details.
	 *
	 * @param employeeId the employee ID of this travel desk details
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this travel desk details.
	 *
	 * @return the company ID of this travel desk details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this travel desk details.
	 *
	 * @param companyId the company ID of this travel desk details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this travel desk details.
	 *
	 * @return the user ID of this travel desk details
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this travel desk details.
	 *
	 * @param userId the user ID of this travel desk details
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this travel desk details.
	 *
	 * @return the user uuid of this travel desk details
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this travel desk details.
	 *
	 * @param userUuid the user uuid of this travel desk details
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the project ID of this travel desk details.
	 *
	 * @return the project ID of this travel desk details
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this travel desk details.
	 *
	 * @param projectId the project ID of this travel desk details
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the project teams ID of this travel desk details.
	 *
	 * @return the project teams ID of this travel desk details
	 */
	public long getProjectTeamsId();

	/**
	 * Sets the project teams ID of this travel desk details.
	 *
	 * @param projectTeamsId the project teams ID of this travel desk details
	 */
	public void setProjectTeamsId(long projectTeamsId);

	/**
	 * Returns the ticket type of this travel desk details.
	 *
	 * @return the ticket type of this travel desk details
	 */
	@AutoEscape
	public String getTicketType();

	/**
	 * Sets the ticket type of this travel desk details.
	 *
	 * @param ticketType the ticket type of this travel desk details
	 */
	public void setTicketType(String ticketType);

	/**
	 * Returns the hotel of this travel desk details.
	 *
	 * @return the hotel of this travel desk details
	 */
	public boolean getHotel();

	/**
	 * Returns <code>true</code> if this travel desk details is hotel.
	 *
	 * @return <code>true</code> if this travel desk details is hotel; <code>false</code> otherwise
	 */
	public boolean isHotel();

	/**
	 * Sets whether this travel desk details is hotel.
	 *
	 * @param hotel the hotel of this travel desk details
	 */
	public void setHotel(boolean hotel);

	/**
	 * Returns the from date of this travel desk details.
	 *
	 * @return the from date of this travel desk details
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this travel desk details.
	 *
	 * @param fromDate the from date of this travel desk details
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this travel desk details.
	 *
	 * @return the to date of this travel desk details
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this travel desk details.
	 *
	 * @param toDate the to date of this travel desk details
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the from time of this travel desk details.
	 *
	 * @return the from time of this travel desk details
	 */
	@AutoEscape
	public String getFromTime();

	/**
	 * Sets the from time of this travel desk details.
	 *
	 * @param fromTime the from time of this travel desk details
	 */
	public void setFromTime(String fromTime);

	/**
	 * Returns the to time of this travel desk details.
	 *
	 * @return the to time of this travel desk details
	 */
	@AutoEscape
	public String getToTime();

	/**
	 * Sets the to time of this travel desk details.
	 *
	 * @param toTime the to time of this travel desk details
	 */
	public void setToTime(String toTime);

	/**
	 * Returns the location of this travel desk details.
	 *
	 * @return the location of this travel desk details
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this travel desk details.
	 *
	 * @param location the location of this travel desk details
	 */
	public void setLocation(String location);

	/**
	 * Returns the purpose of this travel desk details.
	 *
	 * @return the purpose of this travel desk details
	 */
	@AutoEscape
	public String getPurpose();

	/**
	 * Sets the purpose of this travel desk details.
	 *
	 * @param purpose the purpose of this travel desk details
	 */
	public void setPurpose(String purpose);

	/**
	 * Returns the special instraction of this travel desk details.
	 *
	 * @return the special instraction of this travel desk details
	 */
	@AutoEscape
	public String getSpecialInstraction();

	/**
	 * Sets the special instraction of this travel desk details.
	 *
	 * @param specialInstraction the special instraction of this travel desk details
	 */
	public void setSpecialInstraction(String specialInstraction);

	/**
	 * Returns the create date of this travel desk details.
	 *
	 * @return the create date of this travel desk details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this travel desk details.
	 *
	 * @param createDate the create date of this travel desk details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this travel desk details.
	 *
	 * @return the modified date of this travel desk details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this travel desk details.
	 *
	 * @param modifiedDate the modified date of this travel desk details
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this travel desk details.
	 *
	 * @return the status of this travel desk details
	 */
	public int getStatus();

	/**
	 * Sets the status of this travel desk details.
	 *
	 * @param status the status of this travel desk details
	 */
	public void setStatus(int status);

	/**
	 * Returns the manager comment of this travel desk details.
	 *
	 * @return the manager comment of this travel desk details
	 */
	@AutoEscape
	public String getManagerComment();

	/**
	 * Sets the manager comment of this travel desk details.
	 *
	 * @param managerComment the manager comment of this travel desk details
	 */
	public void setManagerComment(String managerComment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TravelDeskDetails travelDeskDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TravelDeskDetails> toCacheModel();

	@Override
	public TravelDeskDetails toEscapedModel();

	@Override
	public TravelDeskDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}