/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.famocom.erpcloud.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the YearSetting service. Represents a row in the &quot;YearSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.famocom.erpcloud.model.impl.YearSettingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.famocom.erpcloud.model.impl.YearSettingImpl}.
 * </p>
 *
 * @author Samaresh
 * @see YearSetting
 * @see com.liferay.famocom.erpcloud.model.impl.YearSettingImpl
 * @see com.liferay.famocom.erpcloud.model.impl.YearSettingModelImpl
 * @generated
 */
@ProviderType
public interface YearSettingModel extends BaseModel<YearSetting> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a year setting model instance should use the {@link YearSetting} interface instead.
	 */

	/**
	 * Returns the primary key of this year setting.
	 *
	 * @return the primary key of this year setting
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this year setting.
	 *
	 * @param primaryKey the primary key of this year setting
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the year setting ID of this year setting.
	 *
	 * @return the year setting ID of this year setting
	 */
	public long getYearSettingId();

	/**
	 * Sets the year setting ID of this year setting.
	 *
	 * @param yearSettingId the year setting ID of this year setting
	 */
	public void setYearSettingId(long yearSettingId);

	/**
	 * Returns the financial year start date of this year setting.
	 *
	 * @return the financial year start date of this year setting
	 */
	public Date getFinancialYearStartDate();

	/**
	 * Sets the financial year start date of this year setting.
	 *
	 * @param financialYearStartDate the financial year start date of this year setting
	 */
	public void setFinancialYearStartDate(Date financialYearStartDate);

	/**
	 * Returns the financial year end date of this year setting.
	 *
	 * @return the financial year end date of this year setting
	 */
	public Date getFinancialYearEndDate();

	/**
	 * Sets the financial year end date of this year setting.
	 *
	 * @param financialYearEndDate the financial year end date of this year setting
	 */
	public void setFinancialYearEndDate(Date financialYearEndDate);

	/**
	 * Returns the calendar start date of this year setting.
	 *
	 * @return the calendar start date of this year setting
	 */
	public Date getCalendarStartDate();

	/**
	 * Sets the calendar start date of this year setting.
	 *
	 * @param calendarStartDate the calendar start date of this year setting
	 */
	public void setCalendarStartDate(Date calendarStartDate);

	/**
	 * Returns the calendar end date of this year setting.
	 *
	 * @return the calendar end date of this year setting
	 */
	public Date getCalendarEndDate();

	/**
	 * Sets the calendar end date of this year setting.
	 *
	 * @param calendarEndDate the calendar end date of this year setting
	 */
	public void setCalendarEndDate(Date calendarEndDate);

	/**
	 * Returns the is active of this year setting.
	 *
	 * @return the is active of this year setting
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this year setting.
	 *
	 * @param isActive the is active of this year setting
	 */
	public void setIsActive(int isActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(YearSetting yearSetting);

	@Override
	public int hashCode();

	@Override
	public CacheModel<YearSetting> toCacheModel();

	@Override
	public YearSetting toEscapedModel();

	@Override
	public YearSetting toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}